apache/lucenenet

src/Lucene.Net.TestFramework/Support/RandomizedTest.cs, src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
20 tests were failing in TestLucene40DocValuesFormat with "Lucene 4.0 does not support SortedSet docvalues". Lucene40 codec does not support sorted set but the tests ran anyway. What is happening is that the base class, BaseDocValuesFormatTestCase, uses the following test to see if it should run the test:
AssumeTrue("Codec does not support SORTED_SET", DefaultCodecSupportsSortedSet());
It looks like AssumeTrue internally had commented out RandomizedTests call that was supposed to mark the test as "inconclusive" with NUnit's Assume.That.
Uncommented the call, now the tests are not marked as failures.
=> Fix test lucene40 doc values format

src/Lucene.Net.TestFramework/Index/BaseTermVectorsFormatTestCase.cs
There are ~20 tests failing with this type of message:
Expected and actual are both &lt;System.Collections.Generic.HashSet`1[System.String]&gt;
Values differ at index [0]
Expected string length 16 but was 12. Strings differ at index 0.
Expected: "fjdcqoqrmvtmfupr"
But was:  "dsncorcvbzne"
After debugging through, it looked like assertion was comparing two sets that actually contained the same values but they were in different order. In Java Set implementations appear to override Equals so that AreEqual assertion passes there. In .NET we have to use SetEquals method to compare two sets if the intention is to make sure sets are of the same size and have the same elements.
Took forever to track down and seconds to fix, sigh...
=> Use Set equality check

src/Lucene.Net.Core/Support/Inflater.cs
Fixes null reference exception that can be observed at times in some of the TestCompressingStoredFieldsFormat and TestCompressingTermVectorsFormat tests. The issue is that those tests set Codec to CompressingCodec using CompressingCodec.RandomInstance which can result in HighCompressionCompressingCodec being used. HighCompressionCompressingCodec in turn uses decompressor that has a bug. The fix removes instantiation of a separate byte buffer in the Inflater and instead uses the buffer that was provided in the call. Instantiating a new buffer essentially wrote bits to an array that no upstream code used. So the callers were getting empty bytes buffer back always. There might be more test that were affected by this.
=> remove unnecessary byte buffer

src/Lucene.Net.Core/Util/IOUtils.cs
UnauthorizedAccessException is being thrown when FSDirectory uses fsync for files and then tries to fsync a directory. The current implementation does not work for directories, and it is not entirely clear what to do in those cases in a way that works across all platforms.
It seems like Lucene version is failing for directories as well and they are handing it by capturing IOException (which won't work with UnauthorizedAccessException):
https://issues.apache.org/jira/browse/LUCENE-5588
The discussion is still on going on the mailing list, checking this in and will adjust based on feedback received.
=> IOUtils fsync for directory fix

src/Lucene.Net.Core/Codecs/DocValuesConsumer.cs, src/Lucene.Net.Core/Codecs/Lucene42/Lucene42NormsConsumer.cs, src/Lucene.Net.Core/Codecs/Lucene45/Lucene45DocValuesConsumer.cs, src/Lucene.Net.Core/Codecs/Perfield/PerFieldDocValuesFormat.cs, src/Lucene.Net.Core/Index/NumericDocValuesWriter.cs, src/Lucene.Net.Core/Index/ReadersAndUpdates.cs, src/Lucene.Net.Core/Index/SortedDocValuesWriter.cs, src/Lucene.Net.Core/Index/SortedSetDocValuesWriter.cs, src/Lucene.Net.TestFramework/Codecs/MissingOrdRemapper.cs, src/Lucene.Net.TestFramework/Codecs/asserting/AssertingDocValuesFormat.cs, src/Lucene.Net.TestFramework/Codecs/lucene3x/PreFlexRWNormsConsumer.cs, src/Lucene.Net.TestFramework/Codecs/lucene40/Lucene40DocValuesWriter.cs, src/Lucene.Net.TestFramework/Codecs/lucene42/Lucene42DocValuesConsumer.cs
Introduce a nullable long in DocValuesConsumer, instead of using just long. The need for this is best illustrated if you look at the changes in Lucene45DocValuesConsumer and in NumericDocValuesWriter. The Writer had iterator implementation that did not match Lucene version, ignoring cases of DocsWithField.Get(doc) evaluating to false in which case a null value needs to be returned. Null value executes a code branch in Lucene45DocValuesConsumer that was simply ignored before. The result of that is the resulting index structure being incorrect, and requests such as DocsWithFields would return true for all documents even though the index had documents that did not have a field in question. 
The tests that used to break are in TestLucene45DocValuesFormat and TestPerFieldDocValuesFormat, e.g. …
=> Use reference instead of value type to match Lucene's logic

src/Lucene.Net.Core/Codecs/Lucene42/Lucene42FieldInfosReader.cs
Lucene42FieldInfosReader was incorrectly treating "0" docValueType byte and returning essentially NUMERIC when it should have returned null. You can see the writer Lucene42FieldInfosWriter (https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.TestFramework/Codecs/lucene42/Lucene42FieldInfosWriter.cs#L118) writing null for 0.
Fixes "Check Index Failed" failures that can be seen in tests whenever Lucene42 codec is used.
=> handle null DocValuesType appropriately

src/Lucene.Net.Core/Util/Fst/BytesStore.cs
Part of the code that belonged in Forward reader had ended up in Reverse reader during port. Reviewed bot iterators to make sure they match what exists https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/util/fst/BytesStore.java 
This also now passes a bunch of failures in Lucene42Codec tests.
=> fix ReverseByteReader Position setter

src/Lucene.Net.Core/Codecs/Lucene42/Lucene42DocValuesProducer.cs, src/Lucene.Net.Core/Util/Fst/Builder.cs, src/Lucene.Net.Core/Util/Fst/BytesStore.cs, src/Lucene.Net.Core/Util/Fst/FST.cs, src/Lucene.Net.Core/Util/Fst/PairOutputs.cs, src/Lucene.Net.Core/Util/Fst/PositiveIntOutputs.cs, src/Lucene.Net.Core/Util/Fst/Util.cs, src/Lucene.Net.TestFramework/Codecs/lucene42/Lucene42DocValuesConsumer.cs, src/Lucene.Net.TestFramework/Util/fst/FSTTester.cs, src/Lucene.Net.Tests/core/Util/Fst/Test2BFST.cs
This PR contains fixes for numerous bugs in Lucene42 codec port, especially around FST functionality. 
First commit is all about changing from long to long? for FST instances to make sure that code branches such as this one https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Core/Util/Fst/FST.cs#L465 evaluate properly. With long, Outputs.Merge gets called when it should not have and then an exception "Specified method is not supported." is thrown. (here is one example in TC: http://teamcity.codebetter.com/viewLog.html?buildId=178533&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNameId8117509285720903580)
Then once the fix allowed further code execution, noticed that FST and some other classes related to it use cast to object when comparing generic type values. Equals …
=> Lucene42 codec fixes

src/Lucene.Net.TestFramework/Codecs/MissingOrdRemapper.cs
This makes several tests in Lucene45/Lucene40 namespace pass. The issue was with how the logic in "insertEmptyValue" iterator was rewritten in .NET. Here is Lucene source:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/test-framework/src/java/org/apache/lucene/codecs/MissingOrdRemapper.java#L40
The goal of this iterator was to first add empty byte array to the enumeration followed by the actual elements returned by  "@in.MoveNext()". The port instead returned empty byte array and then stopped: if seenEmpty OR @in.MoveNext() needs to be, if not seen empty, move next and return empty, otherwise defer to wrapped iterator.
=> fix enumerator port to use appropriate logic

src/Lucene.Net.Tests.Classification/Lucene.Net.Tests.Classification.csproj, src/Lucene.Net.Tests.Facet/Lucene.Net.Tests.Facet.csproj
Trying to keep up with development I tested the build on TeamCity and I found that things did not quite build correctly in that environment. The project files for Lucene.net.Tests.Queries and Lucene.net.Tests.Classification needed a slight tweak to make msbuild look in the right place all the time.
Once we get these added I can turn on the build / tests for those libraries on the CI server.
=> Fixing Compilation for Build Server

src/Lucene.Net.Tests.Facet/Lucene.Net.Tests.Facet.csproj
Fixing a little error that was prevent CI for the Lucene.Net.Tests.Facet project.
=> fixing the Facet tests so that they use the right assembly name and default namespace.

src/Lucene.Net.Core/Index/LogByteSizeMergePolicy.cs
Noticed while debugging failing Lucene42/45 codec tests that sometimes when a test ran ForceMerge(1) on an index writer, the merge of segments did not occur and the directory contained whatever the number of segments existed before the merge. The tests then proceeded to fail as they expected only one segment to be in the index.
The issue is LogByteSizeMergePolicy. It does not occur all the time in the tests as its selection is random (https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs#L977). LogByteSizeMergePolicy policy in constructor sets the max size of the segment for forced merges. The value always ends up being too large for the long type and gets overflown, ie set to a negative value. This then caused LogMergePolicy to …
=> Fix overflow resulting in negative values

src/Lucene.Net.Core/Codecs/DocValuesConsumer.cs, src/Lucene.Net.Core/Index/BinaryDocValuesWriter.cs, src/Lucene.Net.Core/Index/SegmentMerger.cs
This PR contains fixes for segment merging logic for numeric and binary fields. Lucene.Net port was ignoring docsWithField parameter and as a result the merged segment had incorrect values in field infos.  
SegmentMerger needs to pass docsWithField downstream so that the iterators could use it to determine which value to return for byte or numeric fields. Here is the Lucene version, https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/index/SegmentMerger.java#L159, you can see how docsWithField is passed to Merge* calls.
Subsequently, re-introduced docsWithField usage in DocValuesConsumer. Here is the Lucene version for reference: https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/codecs/DocValu …
=> Merge logic fixes

src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
CI builds are timing out after running for an hour. I have tracked down the issue to the use of LogByteSizeMergePolicy for merges. Lucene tests randomly select merge policy from the two choices, one of them being LogByteSize. There are two conditions necessary for the issue to be triggered:
- LogByteSizeMergePolicy needs to be selected by random switches
- mergePolicy.NoCFSRatio needs to be set to something between 0.0 and 1.0
When these two conditions are true, segment merge keeps on running merges over and over and over again until out of memory is reached or segments to be merged list is greater than max long.
While I check on the issue with this merge policy, we can disable it from being used so that the rest of the PRs can be pulled in and immediate feedback from CI received.
=> Use only LogDocMergePolicy while fixing LogByteSizeMergePolicy

src/Lucene.Net.Core/Index/LogMergePolicy.cs, src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
This fixes the issue where if LogByteSizeMergePolicy is used, the merges run "forever". At the end of the day the issue was not with the byte size policy, but with the LogMergePolicy "IsMerged" logic. segmentIsOriginal check was inverted, forcing the evaluation to continue and check IsMerged on already merged index and for LogByteSizeMergePolicy that returned false when in reality that check should have never happened. Changed the code to match Lucene:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/index/LogMergePolicy.java#L181
=> fix LogMergePolicy IsMerged logic

src/Lucene.Net.Core/Codecs/DocValuesConsumer.cs
When merging segments with sorted or sortedset values, incorrect data was written to the index:
- GetMergeSortValuesEnumerable was ignoring ordinal value of -1. Here is Lucene code for the same iterator: https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/codecs/DocValuesConsumer.java#L390
- GetMergeSortedSetValuesEnumerable was skipping one value. Here is the relevant part in Lucene: https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/codecs/DocValuesConsumer.java#L583
Lucene45, Lucene41, and Perfield codecs are now all green with a few runs that I did locally.
=> fix enumerators to use appropriate logic

src/Lucene.Net.Core/Codecs/Lucene40/Lucene40DocValuesReader.cs
Lucene40 codec picks different methods of storing numeric values based on what data type is large enough to represent them. The issue was with the numbers that can fit in sbyte, they were being returned as byte due to our migration. Negative numbers -128 or greater were being returned as positive numbers.
This passes all remaining failing Lucene40 codec tests. Here is one example:
http://teamcity.codebetter.com/viewLog.html?buildId=180212&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNameId-8934306368705483624
Test expects to get back -10 but is getting back 246 instead.
=> Support negative numbers in Lucene40 codec

src/Lucene.Net.Core/Index/BufferedUpdates.cs, src/Lucene.Net.Core/Index/FrozenBufferedUpdates.cs
BufferedUpdates in Lucene use LinkedHashMap which preserves the order of the insertion of values when the collection is iterated over. During the port LinkedHashMap was switched to HashMap and order was lost. Without order preserved, there are cases when multiple updates to a field value will not always have the latest update in the index.
This fixes failures in Lucene.Net.Index.TestBinaryDocValuesUpdates / TestNumericDocValuesUpdates and possible other tests.
=> BufferedUpdates fix

src/Lucene.Net.Tests/core/Index/TestFieldsReader.cs
FaultyFSDirectory was using a setter to set lock factory when it should have assigned directly to a class variable. Using a setter executes logic that should have never been run. 
Lucene is not using setLockFactory there:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/test/org/apache/lucene/index/TestFieldsReader.java#L113
This fixes failure in TestFieldsReader.TestExceptions
=> Set lock factory directly and not through setter

src/Lucene.Net.Tests/core/Analysis/TestLookaheadTokenFilter.cs, src/Lucene.Net.Tests/core/Analysis/TestMockAnalyzer.cs, src/Lucene.Net.Tests/core/Index/TestIndexWriterUnicode.cs, src/Lucene.Net.Tests/core/Index/TestStressIndexing.cs, src/Lucene.Net.Tests/core/Index/TestTermsEnum.cs, src/Lucene.Net.Tests/core/Util/TestPagedBytes.cs
Marking a few tests that always take 20 seconds long running, expanding timeouts on a few for good measure.
=> Marking Long Running Tests

src/Lucene.Net.Tests/core/Index/TestFilterAtomicReader.cs
Test was failing because it was invoking a method by name but without any parameters so if any overloaded methods existed on a type, the exception was thrown about the ambiguous match.
=> pass parameter types to avoid ambigious match exception

src/Lucene.Net.Tests/core/Index/TestSegmentTermDocs.cs
In Java each test run initializes a new TestDoc instance, while in .NET version that is initialized once and all the other per test inits are done in SetUp. Moved the doc init into SetUp as well. This fixes failures in Lucene.Net.Index.TestSegmentTermDocs
=> Initialize doc before each test run

src/Lucene.Net.TestFramework/Analysis/MockTokenizer.cs, src/Lucene.Net.Tests/core/Index/TestIndexWriter.cs, src/Lucene.Net.Tests/core/Index/TestIndexWriterExceptions.cs, src/Lucene.Net.Tests/core/Index/TestIndexWriterReader.cs
This PR marks several IncrementToken methods as sealed that allow some tests to pass. Also contains fixes for TestIndexWriterReader where "ShouldFail" flag was totally ignored and exception were simulated at the times when tests did not expect it. The same with TestIndexWriterExceptions. 
TestIndexWriterExceptions has an additional fix where tests handled generic exception as an "unexpected" exception and treated "CorruptIndexException" as the expected type That does not match the Lucene version:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/test/org/apache/lucene/index/TestIndexWriterExceptions.java#L185
Fixed that and used a more explicit exception type to make sure that we are handling only the expected exception and nothing else.
=> Index fixes

src/Lucene.Net.Tests/core/Analysis/TestCachingTokenFilter.cs, src/Lucene.Net.Tests/core/Analysis/TestGraphTokenizers.cs, src/Lucene.Net.Tests/core/Analysis/TestLookaheadTokenFilter.cs, src/Lucene.Net.Tests/core/Search/Payloads/TestPayloadTermQuery.cs, src/Lucene.Net.Tests/core/Util/TestQueryBuilder.cs
Different unit tests failing as the test related classes do not have IncrementToken marked as sealed.
=> more sealed increment token

src/Lucene.Net.Tests/core/Index/TestIndexWriterExceptions.cs
TestIndexWriterExceptions was failing because deletes were not reflected when the index was opened with the reader. The reason for that was that the documents were being sent with leading 0 in the id (e.g. "id:01" instead of "id:1") but deletes were executed against id without leading zero. Simple oversight of .NET port, Lucene adds the base and i first before converting to string.
=> make sure base is not appended as char

src/Lucene.Net.Tests/core/Index/TestParallelCompositeReader.cs
The ParallelCompositComposit reader now has a ParallelCompositReaderAnonymousInnerClassHelper for the inner instance instead of ParallelCompositReader. Looking back at the history, it has been this way for a long time but this test does not exist in the java version. Is this test in place to show there is something that needs to be fixed in ParallelCompositComposit reader?
=> Moving to a separate branch for independent PR.

src/Lucene.Net.Tests/core/Codecs/Compressing/AbstractTestLZ4CompressionMode.cs
This fixes TestLongLiterals for Codec.Compressing.TestFastCompressionMode and TestFastDecompressionMode tests. sbyte cast changed comparison logic where compressed[off] evaluated to 255.
Example failure on TC: http://teamcity.codebetter.com/viewLog.html?buildId=182801&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNameId-5764249506196176847
=> don't convert to sbyte

src/Lucene.Net.Tests/core/Index/TestSegmentReader.cs
TestSegmentReader.TestDocument is failing because TestDoc instance is not initialized for each test run. Java's test runner seems to run SetUp method as well as initialize all instance variables on each run without having to have that code live in SetUp method.
=> initialize test doc on each test run

src/Lucene.Net.Core/Search/TopTermsRewrite.cs, src/Lucene.Net.Core/Util/PriorityQueue.cs, src/Lucene.Net.Tests/core/Util/TestPriorityQueue.cs
Added a resizing functionality. Now the PQ resizes when it runs out of space. Since the former version was more restrictive (the size was fixed from the beginning) it should be backwards compatible. Nevertheless, it should be checked that no previous usage was expecting an IndexOutOfRangeException when adding elements to the queue.
Added a ToArray method.
Added tests.
With this change, TestsFuzzyQuery/TestFuzziness and TestFuzzyQuery/TestTieBreaker, from the Search package, now succeed.
=> Port from Support's to Util's PQ.

src/Lucene.Net.Core/Util/VirtualMethod.cs, src/Lucene.Net.Core/Util/WeakIdentityMap.cs
The java version uses a concurrent hash map so I updated VirtualMethod to use that.
After that change, we no longer needed the lock on the Reap() function.
Next the Get() needed to use a tryGet() and return the default if there was nothing in the collection.
=> Fix for TestDirectoryReaderReopen.TestThreadSafety

src/Lucene.Net.Tests/core/Index/TestSegmentMerger.cs
Doc1/doc2 need to be initialized on each test run otherwise there is state left over from previous test runs and TestSegmentMerger tests fail.
=> initialize docs on each test run

src/Lucene.Net.Tests/core/Search/Payloads/TestPayloadNearQuery.cs
Java's string.split accepts regular expression, the behavior which was lost when code was translated to .NET. Replaced string.split with regex.split call. This is for TestPayloadNearQuery tests which currently all fail because of this.
=> use regex as logic expects

src/Lucene.Net.Core/Util/Automaton/RegExp.cs, src/Lucene.Net.Tests/core/Search/TestRegexpRandom.cs, src/Lucene.Net.Tests/core/Search/TestWildcardRandom.cs
Searches that use RegExp queries were failing because RegExp implementation had a bug in how it dealt with simple character regular expressions. Lucene version makes sure to append characters based on the codepoint value, while .NET version was simply appending code point value that would get translated into string. (if code point value was set to 48 which is 0, resulting expression was "48" and not "0").
Here is Lucene code for reference https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java, note the places it uses appendCodePoint.
This fixes failures in the tests that use RegExp, e.g. http://teamcity.codebetter.com/viewLog.html?buildId=185033&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNameId39780784687729061 …
=> Regexp fixes

src/Lucene.Net.TestFramework/Index/ThreadedIndexingAndSearchingTestCase.cs, src/Lucene.Net.TestFramework/Util/LineFileDocs.cs
Test helper class LineFileDocs generates test documents with the smallest id set to 1 instead of 0. Tests that expected docId:0 to be in the index failed as a result. Changed the implementation to get the value of id first and then increment, which matches what Lucene is doing:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/test-framework/src/java/org/apache/lucene/util/LineFileDocs.java#L237
With the fix TestNRTThreads.TestNRTThreads_Mem and TestSearcherManager.TestSearcherManager_Mem now pass. Here are the failures in TC:
http://teamcity.codebetter.com/viewLog.html?buildId=185350&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNameId5653300530033422727
http://teamcity.codebetter.com/viewLog.html?buildId=185350&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNam …
=> LineFileDocs fix

src/Lucene.Net.Tests/core/Search/TestMultiPhraseQuery.cs, src/Lucene.Net.Tests/core/Search/TestMultiValuedNumericRangeQuery.cs
TestMultiPhraseQuery.TestMultiSloppyWithRepeats appears to be ignored in Lucene and I can confirm it fails there as well. https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/test/org/apache/lucene/search/TestMultiPhraseQuery.java#L162
TestMultiValuedNumericRangeQuery.TestMultiValuedNRQ was using incorrect digit format, corrected to match what Lucene is doing.
=> Query fixes

src/Lucene.Net.Core/Util/OpenBitSet.cs
TestOpenBitSet.TestSmall test was failing with out of memory exception which you can see here: http://teamcity.codebetter.com/viewLog.html?buildId=185366&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNameId-1093084322476268678). Trying to run it locally with timeout restriction removed resulted in the test process using 4 or more GB of RAM within seconds. After looking into it more, narrowed down what was triggering the condition: bug in Bits2words logic which would get triggered when numBits parameter was set to 0.
To reproduce and observe the results, run TestOpenBitSet.TestSmall test and put a breakpoint here https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Tests/core/Util/TestOpenBitSet.cs#L174 with condition of sz == 0 so that it triggers when random int generation …
=> fix Bits2words logic

src/Lucene.Net.Core/Index/BinaryDocValuesWriter.cs
Fixes a bug where bytes were written to the index incorrectly if Lucene40Codec was used. The issue can be observed by following the data flow starting here:
https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.TestFramework/Codecs/lucene40/Lucene40DocValuesWriter.cs#L176
values.ToArray() enumeration instead of returning an array of different values, it returns an array with all members pointing to the same bytesref instance. This broke logic to detect min / max Lengths down the stream and as a result incorrect bytes were written to an index.
This bug did not show up until the Lucene40DocValuesWriter was rewritten to call ToArray(). Here is a gist illustrating the difference between the two usages with bug in place: https://gist.github.com/laimis/d49291d2f02a7f4830bf
The fix …
=> init bytesref on each iteration

src/Lucene.Net.Core/Codecs/DocValuesConsumer.cs, src/Lucene.Net.Core/Index/ReadersAndUpdates.cs, src/Lucene.Net.Core/Index/SortedDocValuesWriter.cs, src/Lucene.Net.Core/Index/SortedSetDocValuesWriter.cs, src/Lucene.Net.Core/Util/Fst/BytesStore.cs, src/Lucene.Net.TestFramework/Codecs/lucene42/Lucene42DocValuesConsumer.cs, src/Lucene.Net.TestFramework/Index/BaseDocValuesFormatTestCase.cs
Two fixes in this commit as the both are needed to fix the bug discovered in the failing BaseDocValuesFormatTestCase.TestVeryLargeButLegalSortedBytes when run with Lucene42DocValuesFormat.
First commit replaces all the enumerables that reused the same instance variable to return enumeration values.
Second commit fixes a bug with reverse byte reader anonymous class to match Lucene's version:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/util/fst/BytesStore.java#L419
Note how a private byte[] current pointer is used to keep track of the current byte block that the iterator is traveling through. In Lucene.Net port the private array was left unused and instead the higher level "current" was modified which is used and modified by other …
=> Enumerable fixes and ReverseByteReader fix

src/Lucene.Net.Core/Support/Number.cs, src/Lucene.Net.Core/Util/NumericUtils.cs, src/Lucene.Net.Tests/core/Util/TestNumericUtils.cs
Lucene.Net versions of FloatToIntBits and DoubleToLongBits are returning incorrect values if the input is NaN. It seems like it returns correct values in all other cases but in NaN returns negative of what it should. Added code to detect if the input is NaN and return the value that matches Lucene version and what is specified in Java docs: 
https://docs.oracle.com/javase/7/docs/api/java/lang/Float.html#floatToIntBits(float)
https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#doubleToLongBits(double)
This passes TestNumericRangeQuery32/64 failing tests.
=> detect NaN and return appropriate value

src/Lucene.Net.Core/Lucene.Net.csproj, src/Lucene.Net.Core/Search/ITopTermsRewrite.cs, src/Lucene.Net.Core/Search/Spans/SpanMultiTermQueryWrapper.cs, src/Lucene.Net.Core/Search/TopTermsRewrite.cs
Changing the logic that checks if rewrite method is an instance of some sort of TopTermsRewrite to match Lucene. Key change is here:
https://github.com/apache/lucenenet/compare/master...laimis:fuzzyquery_fix?expand=1#diff-605c6558db33049a7e4d93482e5432aeL67
Instead of checking for TopTermsRewrite< Q >, it seems like Lucene cares only if it is TopTermsRewrite based class but does not care what parameter type is used and it does not need to match SpanMultiTermQueryWrapper parameter type:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/search/spans/SpanMultiTermQueryWrapper.java#L68
At least that's how interpreted it. The tests seem to pass and this also fixes failing test in TestSpanMultiTermQueryWrapper. TestFuzzy2
=> change how TopTermsRewrite instance of is checked

src/Lucene.Net.Core/Search/FieldComparator.cs, src/Lucene.Net.Core/Search/FieldDoc.cs, src/Lucene.Net.Tests/core/Search/TestElevationComparator.cs
.NET port introduced FieldComparator that generic FieldComparator<T> inherits from. The issue is that the CompareValues it introduced does not properly propagate CompareValues calls to subclasses of FieldComparator<T>.
To see the bug in action, look at the failing tests in TestTopDocsMerge.TestSort_1 or TestTopDocsMerge. TestSort_2 (does not fail always, but can be repro with a few runs). Here is the link on TC: http://teamcity.codebetter.com/viewLog.html?buildId=189195&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNameId-8365680837810961892
The call invoked here:
https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Core/Search/TopDocs.cs#L207
Results in execution of:
https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Core/Search/FieldComparator.cs#L318
Instead …
=> make sure to invoke appropriate CompareValues via FieldComparator

src/Lucene.Net.Tests/core/Util/TestIndexableBinaryStringTools.cs
TestIndexableBinaryStringTools.TestEncodedSortability is failing because of the comparison method that C# port was using. Just to make sure, captured a few failing test case data and reran the same data in Lucene test and the values generated by C# port match what Lucene generates. The bug was in the test that did comparison, Java calls CompareTo which appears to be equivalent to C# string's CompareOrdinal call.
=> use CompareOrdinal vs CompareTo

src/Lucene.Net.Core/Index/SortedSetDocValuesWriter.cs, src/Lucene.Net.Core/Util/Fst/BytesStore.cs
Lucene42 tests were passing but still showing assert failures occasionally with Fail: frozenHash=xxxxx vs h=xxxx" messages. SkipBytes had a bug where Position value was being read from BytesStore (outer instance) and not using reverse reader logic. Here is the method in Lucene:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/util/fst/BytesStore.java#L434 
The other commit was to eliminate assert messages showing up that were actually not valid failures. There was a bug where Pending.Size() was used instead of PendingCounts.Size() call, as Lucene is doing:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/index/SortedSetDocValuesWriter.java#L284
=> Fix SkipBytes in the reverse reader

src/Lucene.Net.Core/Store/FSDirectory.cs, src/Lucene.Net.Core/Store/MMapDirectory.cs, src/Lucene.Net.Core/Store/NIOFSDirectory.cs, src/Lucene.Net.Core/Store/SimpleFSDirectory.cs, src/Lucene.Net.Tests/core/Store/TestBufferedIndexInput.cs
A good number of tests fail with the error message stating that certain file cannot be accessed. Side by side comparison with what Lucene is doing while using Filemon showed that Lucene.Net version was opening the filestreams with correct FileAccess flag but incorrect FileShare flag. Instead of read it should have been ReadWrite.
The failure would occur when writer was disposed and it called IOUtils fsync. Fsync opens the stream again in FileAccess ReadWrite mode while at the same time there were readers that have the file opened with FileShare set to Read only.
Here is the screenshot of the file handle opened when Lucene is running:
And here is the Lucene.Net:
(hopefully these images come through).
Also was using the TestBufferedIndexInput to confirm the fix and noticed that it was …
=> Fix "The process cannot access the file '...' because it is being used by another process." issues

src/Lucene.Net.Core/Util/DocIdBitSet.cs
Discovered this issue while diagnosing why TestFilteredQuery.TestFilteredQuery_Mem was failing randomly. It came down to a specific filter that needs to be selected with random at this point:
https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.TestFramework/Util/TestUtil.cs#L1303
that gets selected together with "MatchAllDocs" query, called from here:
https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Tests/core/Search/TestFilteredQuery.cs#L170
The test fails with:
Test(s) failed. System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.Collections.BitArray.Get(Int32 index)
at Lucene.Net.Util.DocIdBitSet.Get(Int32 index) in …
=> use GetSafe instead of Get to match java behavior

src/Lucene.Net.Codecs/Memory/FSTOrdTermsReader.cs, src/Lucene.Net.Codecs/Memory/FSTTermsReader.cs, src/Lucene.Net.Codecs/SimpleText/SimpleTextLiveDocsFormat.cs, src/Lucene.Net.Core/Support/BitSetSupport.cs, src/Lucene.Net.Core/Util/Automaton/Automaton.cs, src/Lucene.Net.Core/Util/Automaton/BasicOperations.cs, src/Lucene.Net.Core/Util/Automaton/MinimizationOperations.cs, src/Lucene.Net.Core/Util/Automaton/SpecialOperations.cs, src/Lucene.Net.Core/Util/Fst/Util.cs, src/Lucene.Net.TestFramework/Search/SearchEquivalenceTestBase.cs, src/Lucene.Net.TestFramework/Util/BaseDocIdSetTestCase.cs, src/Lucene.Net.Tests/core/Index/TestTransactionRollback.cs, src/Lucene.Net.Tests/core/Search/TestFilteredQuery.cs, src/Lucene.Net.Tests/core/Search/TestScorerPerf.cs, src/Lucene.Net.Tests/core/Util/TestBytesRefHash.cs, src/Lucene.Net.Tests/core/Util/TestFixedBitSet.cs, src/Lucene.Net.Tests/core/Util/TestLongBitSet.cs, src/Lucene.Net.Tests/core/Util/TestOpenBitSet.cs, src/Lucene.Net.Tests/core/Util/TestWAH8DocIdSet.cs
Lucene.Net port uses BitArray as a replacement for BitSet that Lucene uses. However BitArray behaves differently from BitSet when the bit index is greater than the length of the bit set in Get and Set methods. Adjust all the places where Get/Set is used and use extension methods SafeGet/SafeSet.
=> Use SafeGet and SafeSet for BitArray to match Lucene behavior

src/Lucene.Net.TestFramework/Analysis/MockAnalyzer.cs, src/Lucene.Net.Tests/core/Index/TestTermVectorsWriter.cs
When MockAnalyzer is used, in certain cases the index could have incorrect values written to it. GetOffsetGap does a comparison of OffsetGap_Renamed to null which is always false if OffsetGap_Renamed is not nullable int. Corrected the logic.
To see the bug in action, refer to the following failing test:
http://teamcity.codebetter.com/viewLog.html?buildId=190073&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNameId778192460553334183
=> Make sure offsetGap is nullable int

src/Lucene.Net.Tests/core/Index/TestDirectoryReader.cs
TestDirectoryReader.TestNoDir was failing because catch was catching a wrong exception type. Changed it to match Lucene: https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/test/org/apache/lucene/index/TestDirectoryReader.java#L724
=> check for the appropriate exception

src/Lucene.Net.TestFramework/Index/BaseStoredFieldsFormatTestCase.cs
Occasionally tests TestConcurrentReads fail with expected hit 1 but getting back 0. The issue is that the field values being added to the document are 0 to numDocs - 1 and the random queries are generated using 0 to numDocs. So if random hits the numDocs value, that document is not in the index and test fails. Adjusted test to match what Lucene is doing:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/test-framework/src/java/org/apache/lucene/index/BaseStoredFieldsFormatTestCase.java#L439
=> use proper random.next

src/Lucene.Net.Core/Util/IOUtils.cs, src/Lucene.Net.Tests/core/Index/TestIndexWriter.cs
ReThrowUnchecked in IOUtils is wrapping exceptions when it should not. Doing that causes issues with upstream code that handles a specific type of exception but "Exception" is thrown instead. Looking at the Lucene code, the fixed version matches what Lucene is trying to do:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/util/IOUtils.java#L360
- if null, don't throw
- otherwise throw exception itself
- unless it is not of RuntimeException type or Error type in which case wrap it - but this does not apply in .NET world.
At the very least the following test was failing because of this that now passes (unless there is another "rand" situation that I had not encountered):
http://teamcity.codebetter.com/viewLog.html?buildId=190499&tab=buildRes …
=> IOUtils fix

src/Lucene.Net.Core/Analysis/TokenStream.cs, src/Lucene.Net.Core/Index/DocumentsWriterStallControl.cs, src/Lucene.Net.Core/Index/IndexWriter.cs
TestDocumentsWriterStallControl fails in Release mode but not in Debug builds. Looks like Lucene is performing logic when calling assert, which translated to Debug.Assert in Lucene.Net. Debug.Assert is removed at the compile time if compiled in release mode.
Took out the logic from the Debug.Assert.
Here is the failing test that this fixes:
http://teamcity.codebetter.com/viewLog.html?buildId=190748&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNameId-5834889155160949386
There are more places in the code base that suffer from this, I believe. Looking for them.
=> Debug.Assert with side effects fix

src/Lucene.Net.Tests/core/Codecs/Lucene41/TestBlockPostingsFormat2.cs
Lucene41.TestBlockPostingsFormat2 teardown is failing because the cleanup is not run after each test. Instead it is run after all test cases finish. Use setup / teardown after each test instead.
=> use setup/teardown instead of fixture setup/teardown

src/Lucene.Net.Core/Lucene.Net.csproj, src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyWriter.cs, src/Lucene.Net.Tests.Facet/Taxonomy/Directory/TestDirectoryTaxonomyWriter.cs, src/Lucene.Net.Tests/core/Index/TestIndexWriter.cs, src/Lucene.Net.Tests/core/Index/TestTermdocPerf.cs
Couple more places where incrementtoken was not sealed. 
Also match target platform for release builds to what is set in debug builds. This was preventing tests to run on 64 bit machines when compiled in release mode.
=> Incrementtoken fixes

src/Lucene.Net.Core/Search/LiveFieldValues.cs, src/Lucene.Net.Tests/core/Search/TestLiveFieldValues.cs
TestLiveFieldValues test is not failing but console contains several failures in that test that are getting ignored.
First match the test to use nullable integer like Lucene does:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/test/org/apache/lucene/search/TestLiveFieldValues.java) 
And then correct string format usage:
https://github.com/apache/lucenenet/compare/master...laimis:livefieldvalues_fixes?expand=1#diff-db6d92460fa820ed96ad430d1c338012R180
=> use nullable int to matche Lucene, proper string format usage

src/Lucene.Net.Core/Store/NIOFSDirectory.cs, src/Lucene.Net.Core/Support/FileStreamExtensions.cs
It seems like Lucene.Net NIOFSDirectory port has an issue when used in multiple threads for reading. Any test that is based on BasePostingsFormatTestCase, which runs multiple threads that read from directory, has a lot of errors in the logs when NIOFSDirectory is used as an implementation type of FSDirectory.
You can see the failures from the TC build logs, here are some of the highlights:
System.Exception: Index was outside the bounds of the array. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
at System.IO.FileStream.ReadByte()
at Lucene.Net.Support.FileStreamExtensions.Read(FileStream file, ByteBuffer dst, Int64 position) in z:\Builds\work\bcdbe6b8cc677a49\src\Lucene.Net.Core\Support\FileStreamExtensions.cs:line 22
at …
=> synchronize access to underlying file stream for NIOFSDirectory

src/Lucene.Net.Tests/core/Search/TestDateFilter.cs
Use DateTime.UtcNow.Ticks instead of Environment.TickCount, otherwise test can fail with low Environment.TickCount value resulting in negative value passed to DateTools.TimeToString method. UtcNow.Ticks match closer what Lucene is doing by calling System.currentTimeMillis();
Lucene: https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/test/org/apache/lucene/search/TestDateFilter.java#L46
Failing test:
http://teamcity.codebetter.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=192345#_focus=5607
=> Use DateTime.UtcNow.Ticks instead of Environment.TickCount

src/Lucene.Net.TestFramework/Lucene.Net.TestFramework.csproj, src/Lucene.Net.TestFramework/Support/FloatUtils.cs, src/Lucene.Net.TestFramework/Util/LuceneTestCaseWithReducedFloatPrecision.cs, src/Lucene.Net.Tests/core/Search/TestExplanations.cs, src/Lucene.Net.Tests/core/Search/TestFuzzyQuery.cs, src/Lucene.Net.Tests/core/Search/TestQueryRescorer.cs, src/Lucene.Net.Tests/core/Search/TestSearchAfter.cs, src/Lucene.Net.Tests/core/Search/TestTopDocsMerge.cs
We noticed that running tests in 32 bit CPUs was introducing floating point rounding issues and tests were failing as the same calculation could produce different result if executed multiple times in a single test. After some discussions on the mailing list it was determined that on 32 bit machines different instructions are used from 64 bit machines to process floating point numbers. Intermediate results when transferred with higher precision to the next operations eventually lead to rounding errors once a final calculation is returned as float.
From all the reading and trying several approaches so far, the only way I was able to consistently to get floating point conversion issues to go away is to pinvoke _controlfp_s to set floating point precision to 24 bits.
I got the idea from …
=> use reduced precision float base class

src/Lucene.Net.Core/Search/Grouping/AbstractDistinctValuesCollector.cs, src/Lucene.Net.Core/Search/Grouping/TermDistinctValuesCollector.cs, src/Lucene.Net.Core/Support/Arrays.cs
Added AbstractDistinctValuesCollector and TermDistinctValuesCollector, and modified Arrays object to have some helper methods Java has in Arrays. 
I added an interface to allow AbstractDistinctValuesCollector to only have one type parameter, without it we'd have had to say "AbstractDistinctValuesCollector<T,U> : Collector where T : AbstractDistinctValuesCollector.GroupCount<U>", which is redundant but necessary in C#.
=> Adding two Grouping classes and supporting Arrays.cs methods.

.gitignore, src/Lucene.Net.Core/Codecs/Compressing/CompressionMode.cs, src/Lucene.Net.Core/Document/CompressionTools.cs, src/Lucene.Net.Core/Lucene.Net.csproj, src/Lucene.Net.TestFramework/Util/TestUtil.cs
- Modifying CompressionMode to use System.IO.Compression.DeflateStream and remove dependency on external zip library.  Verfied AbstractCompressionMode tests passed.
- Modifying CompressionTools to use System.IO.Compression.DeflateStream and remove dependency on external zip library.
- Removing unused fuction in TestUtils that depended on external zip library.
- Adding ignore for project.lock.json files.
=> LUCENET-555 Removing dependency on external zip library.

src/Lucene.Net.Core/Codecs/Codec.cs, src/Lucene.Net.Core/Util/NamedSPILoader.cs, src/Lucene.Net.Tests/Lucene.Net.Tests.csproj, src/Lucene.Net.Tests/core/Codecs/TestCodec.cs, src/Lucene.Net.Tests/core/Util/TestNamedSPILoader.cs
NamedSPILoader and Codec classes used original Java based texts in exception messages that referenced JAR files and Java method names. This commit rewords these messages to be more .NET friendly.
It also fixes bug in the exception message in NamedSPILoader.Lookup() method that did not list the names of available services properly.
I refactored unit tests for the NamedSPILoader class to be more reliable. Original tests were moved to TestCodec class.
=> Fixed exception messages in NamedSPILoader and Codec classes

src/Lucene.Net.Facet/Taxonomy/WriterCache/CollisionMap.cs, src/Lucene.Net.Tests.Codecs/Lucene.Net.Codecs.Tests.csproj
It will be great to keep LuceneNet cross platform and compatible with Mono.
This is just a simple fix to make the build pass on Mono\Linux.
=> replace InstanceNotFoundException to allow building on Mono

src/Lucene.Net.Tests.Expressions/Lucene.Net.Tests.Expressions.csproj, src/Lucene.Net.Tests.Expressions/packages.config
Super simple PR just to fix the nuget package reference for  Lucene.Net.Tests.Expressions for Nunit since it wasn't using a real Nuget reference.
=> Fixes the Nuget Nunit reference for Lucene.Net.Tests.Expressions

src/Lucene.Net.TestFramework/Codecs/MockSep/MockSepPostingsFormat.cs, src/Lucene.Net.TestFramework/Codecs/MockSep/MockSingleIntFactory.cs, src/Lucene.Net.TestFramework/Codecs/MockSep/MockSingleIntIndexInput.cs, src/Lucene.Net.TestFramework/Codecs/MockSep/MockSingleIntIndexOutput.cs, src/Lucene.Net.TestFramework/Lucene.Net.TestFramework.csproj, src/Lucene.Net.Tests/Lucene.Net.Tests.csproj, src/Lucene.Net.Tests/core/Codecs/Perfield/TestPerFieldPostingsFormat2.cs, src/Lucene.Net.Tests/core/Index/TestCrashCausesCorruptIndex.cs
Ported the Core.Codecs.Perfield.TestPerFieldPostingsFormat2 tests and removed [Test] attribute from a couple of methods where it didn't belong (methods that are called from other tests).
=> Ported Core.Codecs.Perfield.TestPerFieldPostingsFormat2

src/Lucene.Net.Core/Util/SPIClassIterator.cs, src/Lucene.Net.TestFramework/Codecs/lucene3x/PreFlexRWCodec.cs, src/Lucene.Net.TestFramework/Codecs/lucene40/Lucene40RWCodec.cs, src/Lucene.Net.TestFramework/Codecs/lucene40/Lucene40RWDocValuesFormat.cs, src/Lucene.Net.TestFramework/Codecs/lucene40/Lucene40RWNormsFormat.cs, src/Lucene.Net.TestFramework/Codecs/lucene40/Lucene40RWPostingsFormat.cs, src/Lucene.Net.TestFramework/Codecs/lucene41/Lucene41RWCodec.cs, src/Lucene.Net.TestFramework/Codecs/lucene42/Lucene42RWCodec.cs, src/Lucene.Net.TestFramework/Codecs/lucene42/Lucene42RWDocValuesFormat.cs, src/Lucene.Net.TestFramework/Codecs/lucene45/Lucene45RWCodec.cs, src/Lucene.Net.Tests/core/Codecs/Perfield/TestPerFieldPostingsFormat2.cs
* Improve loading performance:
* Filtering out Microsoft/System assemblies
* Only iterating through distinct assemblies
* Only adding public classes to the iterator:
* This fixed test failures where [MockCodec](https://github.com/apache/lucenenet/blob/8ce8e81fb06d43a44974436d79dadd33197bf0e0/src/Lucene.Net.Tests/core/Codecs/Perfield/TestPerFieldPostingsFormat2.cs#L200) (which had a codec name "Lucene46") was being loaded instead of [Lucene46Codec](https://github.com/apache/lucenenet/blob/c6d7bec47383919793721ecf9ca5f6966fb86033/src/Lucene.Net.Core/Codecs/Lucene46/Lucene46Codec.cs#L83) because it was being found first in the iterator
* Consolidated assembly loading code
*  Adding a default ctor to the Codecs that were not being found because SPIClassIterator was skipping over them
I tested …
=> Fix test failures and making SPIClassIterator more performant

src/Lucene.Net.Tests/core/Search/JustCompileSearch.cs, src/Lucene.Net.Tests/core/Search/TestDocIdSet.cs
Currently compiling master results in build errors:
```
core\Search\JustCompileSearch.cs(204,46): error CS0507: 'JustCompileSearch.JustCompileFilteredDocIdSet.Match(int)': cannot change access modifiers when overriding 'protected' inherited member 'FilteredDocIdSet.Match(int)' [D:\git\conniey\lucenenet\src\Lucene.Net.Tests\Lucene.Net.Tests.csproj]`
```
This is due to changes in [FilteredDocIdSet](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Core/Search/FilteredDocIdSet.cs#L95) from: 
`protected internal abstract bool Match(int docid);` to `protected abstract bool Match(int docid);`
This fixes those errors.  An alternative would be to add the `internal` modifier back to FilteredDocIdSet.
@NightOwl888 Do you know why it was removed in the first place?
=> Fixing build errors

src/Lucene.Net.Analysis.Common/Properties/AssemblyInfo.cs, src/Lucene.Net.Analysis.Stempel/Properties/AssemblyInfo.cs, src/Lucene.Net.Classification/Properties/AssemblyInfo.cs, src/Lucene.Net.Codecs/Properties/AssemblyInfo.cs, src/Lucene.Net.Core/AssemblyInfo.cs, src/Lucene.Net.Expressions/Properties/AssemblyInfo.cs, src/Lucene.Net.Facet/Properties/AssemblyInfo.cs, src/Lucene.Net.Grouping/Properties/AssemblyInfo.cs, src/Lucene.Net.Join/Properties/AssemblyInfo.cs, src/Lucene.Net.Memory/Properties/AssemblyInfo.cs, src/Lucene.Net.Misc/Properties/AssemblyInfo.cs, src/Lucene.Net.Queries/Properties/AssemblyInfo.cs, src/Lucene.Net.QueryParser/Properties/AssemblyInfo.cs, src/Lucene.Net.Sandbox/Properties/AssemblyInfo.cs, src/Lucene.Net.Spatial/Properties/AssemblyInfo.cs, src/Lucene.Net.Suggest/Properties/AssemblyInfo.cs
Updating the AssemblyInfo files to provide better myget metadata for now. This should not conflict w/ #191.
=> updating assemblyinfo files for nuget package metadata.

src/Lucene.Net.Tests/Store/TestDirectory.cs, src/Lucene.Net/Store/FSDirectory.cs
`FSDirectory` has a hash set to track stale files. In the original Lucene source at e.g. https://github.com/apache/lucene-solr/blob/b7047694256a8e5808b9a9ddf480643ff768d8a9/lucene/core/src/java/org/apache/lucene/store/FSDirectory.java#L126, this is a synchronized set. In the .NET version, it's not, causing unsynchronized access to this set.
Changed to a `Lucene.Net.Support.ConcurrentHashSet<>`.
=> Made FSDirectory stale files set synchronized.

websites/apidocs/docfx.json, websites/apidocs/toc.yml, websites/site/contributing/documentation.md, websites/site/contributing/toc.yml, websites/site/docfx.json, websites/site/lucenetemplate/doap_Lucene_Net.rdf, websites/site/lucenetemplate/index.html.tmpl
Commits some small pending changes that i forgot to previously push and adds the DOAP file to the website repo files so it's included in the build output.
If you want to test, run the powershell site build script: `/websites/site/site.ps1 -ServeDocs 0` then check the output directory `/websites/site/_site` and you'll see the `doap_Lucene_Net.rdf` there.
=> Website updates - DOAP file and copy changes

src/Lucene.Net/Util/StringHelper.cs
StringHelper.GOOD_FAST_HASH_SEED property is not thread-safe and could return different values if called in severeal threads in one moment, so it could result in duplicate values in BytesRefHash (same values return different hashes because hashes were calcucated with different seeds).
There is another issue with GOOD_FAST_HASH_SEED. DateTime.Now.Millisecond is used to randomize the seed, but DateTime.Now.Millisecond could return 0 and this value is treated an "uninitialized" and the second GOOD_FAST_HASH_SEED call will return another value.
=> https://issues.apache.org/jira/browse/LUCENENET-607

src/dotnet/tools/JavaDocToMarkdownConverter/JavaDocToMarkdownConverter/JavaDocToMarkdownConverter.csproj, src/dotnet/tools/JavaDocToMarkdownConverter/JavaDocToMarkdownConverter/Program.cs, src/dotnet/tools/JavaDocToMarkdownConverter/JavaDocToMarkdownConverter/StringExtensions.cs, src/dotnet/tools/JavaDocToMarkdownConverter/JavaDocToMarkdownConverter/packages.config
Also exit when no args passed to prevent exception showing
This should fix the following issues raised in https://github.com/apache/lucenenet/pull/231 :
* Issues with namespaces
* Lists rendering incorrectly
=> JavaDocToMarkdownConverter: Map Lucene.Net.Search.Join and Grouping correctly, upgrade Html2Markdown

src/Lucene.Net.Analysis.Common/Analysis/Util/OpenStringBuilder.cs
Implement IAppendable on OpenStringBuilder as per J2N
https://github.com/NightOwl888/J2N/blob/master/src/J2N/Text/StringBuffer.cs
=> Implemented IAppendable as per J2N 

src/Lucene.Net/Codecs/package.md, src/Lucene.Net/Support/Codecs/DefaultCodecFactory.cs, src/Lucene.Net/Support/Codecs/DefaultDocValuesFormatFactory.cs, src/Lucene.Net/Support/Codecs/DefaultPostingsFormatFactory.cs, src/Lucene.Net/Support/Codecs/ICodecFactory.cs, src/Lucene.Net/Support/Codecs/IDocValuesFormatFactory.cs, src/Lucene.Net/Support/Codecs/IPostingsFormatFactory.cs
Added documentation demonstrating how codec factories can be subclassed, custom built, and registered to include custom codec types, as well as testing examples, and default registered codecs. (closes #266, closes LUCENENET-625)
=> Fully document Codec Factories and include usage samples (addresses #266)

src/Lucene.Net.Queries/Function/DocValues/DoubleDocValues.cs, src/Lucene.Net.Queries/Function/DocValues/FloatDocValues.cs, src/Lucene.Net.Queries/Function/DocValues/IntDocValues.cs, src/Lucene.Net.Queries/Function/DocValues/LongDocValues.cs, src/Lucene.Net.Queries/Function/FunctionValues.cs, src/Lucene.Net.Queries/Function/ValueSources/ByteFieldSource.cs, src/Lucene.Net.Queries/Function/ValueSources/DocFreqValueSource.cs, src/Lucene.Net.Queries/Function/ValueSources/DoubleConstValueSource.cs, src/Lucene.Net.Queries/Function/ValueSources/EnumFieldSource.cs, src/Lucene.Net.Queries/Function/ValueSources/IntFieldSource.cs, src/Lucene.Net.Queries/Function/ValueSources/LinearFloatFunction.cs, src/Lucene.Net.Queries/Function/ValueSources/LongFieldSource.cs, src/Lucene.Net.Queries/Function/ValueSources/ReciprocalFloatFunction.cs, src/Lucene.Net.Queries/Function/ValueSources/ScaleFloatFunction.cs, src/Lucene.Net.Queries/Function/ValueSources/ShortFieldSource.cs
Converted types to use invariant culture when converting strings to numbers and numbers to strings.
After analysis, it looks like this is the right choice, as the places that utilize these queries are also using culture-insensitive conversions. If a user extends `FunctionValues`, they can build in their own culture sensitivity as needed per their requirements by adding overloads to these methods in a custom subclass.
=> Lucene.Net.Queries Culture Sensitivity (fixes #260)

build/Dependencies.props, src/Lucene.Net.Benchmark/Quality/Trec/TrecJudge.cs, src/Lucene.Net.Codecs/SimpleText/SimpleTextTermVectorsReader.cs, src/Lucene.Net.TestFramework.NUnit/Support/TestFramework/Assert.cs, src/Lucene.Net.TestFramework/Index/BaseTermVectorsFormatTestCase.cs, src/Lucene.Net.TestFramework/Support/Configuration/ConfigurationBuilderExtensions.cs, src/Lucene.Net.TestFramework/Support/Configuration/TestConfigurationFactory.cs, src/Lucene.Net.TestFramework/Support/Diagnostics/Debug.cs, src/Lucene.Net.TestFramework/Support/Util/LuceneTestFrameworkInitializer.cs, src/Lucene.Net.Tests.Benchmark/ByTask/Tasks/Alt/AltPackageTaskTest.cs, src/Lucene.Net.Tests.QueryParser/Classic/TestQueryParser.cs, src/Lucene.Net.Tests/Index/TestIndexWriterExceptions.cs, src/Lucene.Net/Analysis/Tokenizer.cs, src/Lucene.Net/Codecs/BlockTreeTermsWriter.cs, src/Lucene.Net/Codecs/Compressing/CompressingStoredFieldsIndexWriter.cs, src/Lucene.Net/Codecs/Compressing/CompressingTermVectorsReader.cs, src/Lucene.Net/Codecs/Lucene3x/Lucene3xTermVectorsReader.cs, src/Lucene.Net/Codecs/Lucene40/Lucene40TermVectorsReader.cs, src/Lucene.Net/Index/DocumentsWriterPerThread.cs, src/Lucene.Net/Index/FreqProxTermsWriterPerField.cs, src/Lucene.Net/Index/IndexWriter.cs, src/Lucene.Net/Index/StoredFieldsProcessor.cs, src/Lucene.Net/Index/TermVectorsConsumer.cs, src/Lucene.Net/Index/TermVectorsConsumerPerField.cs, src/Lucene.Net/Support/Diagnostics/Debugging.cs
This fixes #267 by converting these asserts that were intended for control flow during testing into `InvalidOperationException`s. In the test framework, we are still throwing `Lucene.Net.Diagnostics.AssertionException` in order to differentiate an "assert" from other cases that are throwing `InvalidOperationException`.
This is similar to how Lucene 8.x behaves, and only affects legacy codecs for `Lucene3x` and `Lucene40`.
As for `BlockTreeTermsWriter`, its assert was failing due to lack of validation on the `Prefix` to ensure it is valid UTF-8. Since the problem is only when building the string in the assert, a private method was added to generate the string by catching exceptions due to invalid UTF-8 and falling back to just writing out the display of bytes in `BytesRef`.
=> Failing Asserts on .NET Standard 2.x (fixes #267, fixes #301)

src/Lucene.Net.Tests.Analysis.Common/Analysis/NGram/NGramTokenizerTest.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestCharTokenizers.cs
See the known failing tests in #269.
The problem was that the code point was being cast to a `char` before calling the `IndexOf` method, which means that it didn't support surrogate pairs. In rare instances where the cast turned the code point into a valid token character the test failed.
.NET doesn't have a built-in overload of `String.IndexOf()` that accepts a code point, that is an extension method in J2N.
=> Fix for NGram TestUTF8FullRange() tests (See #269)

src/Lucene.Net.Analysis.Common/Analysis/Core/LetterTokenizer.cs, src/Lucene.Net.Analysis.Common/Analysis/Core/LowerCaseTokenizer.cs, src/Lucene.Net.Analysis.Common/Analysis/Core/WhitespaceTokenizer.cs, src/Lucene.Net.Analysis.Common/Analysis/El/GreekLowerCaseFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/En/PorterStemmer.cs, src/Lucene.Net.Analysis.Common/Analysis/Ga/IrishLowerCaseFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/StemmerOverrideFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/WordDelimiterIterator.cs, src/Lucene.Net.Analysis.Common/Analysis/Synonym/SynonymFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Th/ThaiTokenizer.cs, src/Lucene.Net.Analysis.Common/Analysis/Tr/TurkishLowerCaseFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/CharArrayMap.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/CharacterUtils.cs, src/Lucene.Net.Analysis.Morfologik/Morfologik/MorfologikFilter.cs, src/Lucene.Net.TestFramework/Analysis/MockTokenizer.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Miscellaneous/TestStemmerOverrideFilter.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Payloads/TypeAsPayloadTokenFilterTest.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestCharArraySet.cs, src/Lucene.Net.Tests.Highlighter/PostingsHighlight/TestPostingsHighlighterRanking.cs, src/Lucene.Net.Tests/Support/TestWeakDictionaryBehavior.cs, src/dotnet/Lucene.Net.Tests.ICU/Search/PostingsHighlight/TestICUPostingsHighlighterRanking.cs
This fixes several Analysis.Common classes that were broken since 4.8.0-beta00008 in commit https://github.com/apache/lucenenet/commit/b733c4d158e5e1de62c6b12797c589ac70b4c1c7 because the `Character` class was changed to J2N which uses the current culture by default instead of Java's default of invariant culture for uppercasing and lowercasing. As a result, these classes were unintentionally modified in behavior. This patch reverts them back to the invariant culture (or specific culture for the class, where applicable).
Also, a bug was discovered where a cast from `int` to `char` caused many analysis classes to incorrectly process surrogate pairs, which this addresses.
We were also able to revert the `TurkishLowercaseFilter` back to its original implementation by utilizing `J2N.Character` …
=> Fix for analysis culture sensitivity and surrogate pair support

src/Lucene.Net.Analysis.Common/Analysis/Th/ThaiTokenizer.cs, src/Lucene.Net.Analysis.Common/Analysis/Th/ThaiWordFilter.cs
The `ThaiWordBreaker` was created to cover the gap between ICU's `BreakIterator` class and the `BreakIterator` class from the JDK which this analyzer was originally based on. However, there was a bug that made it fail when there were surrogate pairs in the input which this patch addresses.
Also, this adds locking which helps (but does not completely fix) a thread safety issue with `ThaiTokenizer`. The prime suspect is the dictionary-based `BreakIterator` for Thai in ICU4N, but we need to investigate further.
=> Fixed ThaiWordBreaker to account for surrogate pairs

src/Lucene.Net.Analysis.Common/Analysis/Th/ThaiTokenizer.cs, src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/BreakIteratorWrapper.cs, src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/CharArrayIterator.cs, src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/CompositeBreakIterator.cs, src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/DefaultICUTokenizerConfig.cs, src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/ICUTokenizer.cs, src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/ICUTokenizerConfig.cs, src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/ICUTokenizerFactory.cs, src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/ScriptIterator.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Th/TestThaiAnalyzer.cs, src/Lucene.Net/Util/AttributeSource.cs
This patch fixes thread safety with `ICUTokenizer` and makes it pass the `TestRandomStrings` and `TestRandomHugeStrings` of both `TestICUTokenizer` and `TestICUTokenizerCJK` test classes (see #269). This serves as proof that thread safety is broken in ICU4N's BreakIterator and the patch can be reverted once the thread safety issues have been addressed in ICU4N.
The `ThaiTokenizer` is also patched slightly better here, but it still occasionally fails the `TestRandomStrings` and `TestRandomHugeStrings` tests (see #269).
This PR also contains some performance improvements for `AttributeSource` that make the tests less likely to run slow due to threading contention issues or unnecessary dictionary lookups.
=> Temporary thread safety fix for ICUTokenizer/Locking patches for AttributeSource

src/Lucene.Net.Replicator/IndexInputInputStream.cs, src/Lucene.Net.Tests.Replicator/IndexInputStreamTest.cs
Lucene.Net.Replicator: Fixed an issue in IndexInputStream.Read(...) that meant the method could return a number larger than what was passed in for read count or what the buffer could hold.
It should instead return the total number of bytes that was read into the buffer, which logically can't be bigger than the buffer it self.
This would make implementations like [Stream.CopyTo](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.copyto?view=netcore-3.1) fail as it relies on the returned number to tell how much to write into the target stream.
=> Lucene.Net.Replicator: Fixed an issue in IndexInputStream.Read(...)

src/Lucene.Net/Search/DocTermOrdsRangeFilter.cs, src/Lucene.Net/Search/DocTermOrdsRewriteMethod.cs, src/Lucene.Net/Search/FieldCacheDocIdSet.cs, src/Lucene.Net/Search/FieldCacheRangeFilter.cs, src/Lucene.Net/Search/FieldCacheRewriteMethod.cs, src/Lucene.Net/Search/FieldCacheTermsFilter.cs, src/Lucene.Net/Search/FieldValueFilter.cs
Added predicate parameter so users don't have to hand-code classes just to apply document filters.
=> Lucene.Net.Search.FieldCacheDocIdSet: Added constructor with predicate

src/Lucene.Net.Sandbox/Queries/FuzzyLikeThisQuery.cs, src/Lucene.Net.Sandbox/Queries/SlowFuzzyTermsEnum.cs, src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs, src/Lucene.Net/Search/FuzzyTermsEnum.cs, src/Lucene.Net/Search/TopScoreDocCollector.cs, src/Lucene.Net/Support/AssemblyUtils.cs, src/Lucene.Net/Util/SPIClassIterator.cs
This fixes tests that are failing due to floating point precision issues on x86 when optimized. Disabling optimizations on specific methods fixes the following tests:
- `Lucene.Net.Sandbox.TestSlowFuzzyQuery::TestTokenLengthOpt()`
- `Lucene.Net.Search.TestSearchAfter::TestQueries()`
- `Lucene.Net.Search.TestTopDocsMerge::TestSort_1()`
- `Lucene.Net.Search.TestTopDocsMerge::TestSort_2()`
as recorded in #269.
=> Fixes 4 failing tests in .NET Framework/x86

src/Lucene.Net.TestFramework/Index/BaseDocValuesFormatTestCase.cs, src/Lucene.Net/Codecs/Compressing/CompressingTermVectorsWriter.cs, src/Lucene.Net/Document/FloatDocValuesField.cs, src/Lucene.Net/Search/Spans/FieldMaskingSpanQuery.cs
Fixed several references to `J2N.BitConversion` that were calling the overload that normalizes NaN when they should have been calling the raw bit conversion instead. This is to match Lucene's behavior, but only affects those who are storing NaN in the index.
=> Fixed several references to J2N.BitConversion

src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/CapitalizationFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/CapitalizationFilterFactory.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Miscellaneous/TestCapitalizationFilter.cs
Changed default behavior to use invariant culture instead of the current thread's culture to match Lucene, which seems more natural when using filters inside of analyzers.
=> BREAKING: Changed CaptializationFilter default culture to invariant to match Lucene

Directory.Build.targets, src/Lucene.Net.Tests.TestFramework/Configuration/Custom/MockConfigurationFactory.cs, src/Lucene.Net/Support/Configuration/Base/ConfigurationRoot.cs
Since the `IConfigurationRoot` interface is different between `Microsoft.Extensions.Configuration.Extensions` 1.x and 2.x+, this patch removes the interface from .NET Framework targets and replaces it with `IConfiguration`.
=> Fixes #323 - Allow .NET Framework users to upgrade Microsoft.Extensions.Configuration without requiring an IConfigurationFactory

Lucene.Net.sln, src/Lucene.Net/Lucene.Net.csproj, src/dotnet/Lucene.Net.CodeAnalysis.CSharp/Lucene.Net.CodeAnalysis.CSharp.csproj, src/dotnet/Lucene.Net.CodeAnalysis.CSharp/Lucene1000_SealIncrementTokenMethodCSCodeFixProvider.cs, src/dotnet/Lucene.Net.CodeAnalysis.CSharp/Lucene1000_SealTokenStreamClassCSCodeFixProvider.cs, src/dotnet/Lucene.Net.CodeAnalysis.CSharp/Lucene1000_TokenStreamOrItsIncrementTokenMethodMustBeSealedCSAnalyzer.cs, src/dotnet/Lucene.Net.CodeAnalysis.VisualBasic/Lucene.Net.CodeAnalysis.VisualBasic.csproj, src/dotnet/Lucene.Net.CodeAnalysis.VisualBasic/Lucene1000_SealIncrementTokenMethodVBCodeFixProvider.cs, src/dotnet/Lucene.Net.CodeAnalysis.VisualBasic/Lucene1000_TokenStreamOrItsIncrementTokenMethodMustBeSealedVBAnalyzer.cs, src/dotnet/Lucene.Net.Tests.CodeAnalysis/TestLucene1000_SealIncrementTokenMethodCSCodeFixProvider.cs, src/dotnet/Lucene.Net.Tests.CodeAnalysis/TestLucene1000_SealIncrementTokenMethodVBCodeFixProvider.cs, src/dotnet/Lucene.Net.Tests.CodeAnalysis/TestLucene1000_SealTokenStreamClassCSCodeFixProvider.cs
This works around the problem by creating separate assemblies for CSharp and VisualBasic that only depend on dependencies for the specific language (fixes #286)
=> Lucene.Net.CodeAnalysis: Separated CSharp and VisualBasic providers (fixes #286)

src/Lucene.Net/Search/FieldCacheImpl.cs
Minor change, but noticed this was appearing on my benchmark when trying to enumerate all search hits - don't think the dictionary is actually needed here
=> remove unnecessary dictionary lookup in FieldCacheImpl

src/Lucene.Net/Search/FieldCache.cs, src/Lucene.Net/Search/FieldCacheImpl.cs, src/Lucene.Net/Util/FieldCacheSanityChecker.cs
This refactors `FieldCacheImpl` and `FieldCache` to take advantage of generics to reduce casting and also eliminates a particular boxing issue with the `acceptableOverheadRatio` value of `BinaryDocValuesImpl` and `SortedDocValuesImpl`.
The impact seems negligible on the simple case benchmarks we are using. However, we are now seeing the test times on Windows dip to lower levels than seen before.
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1016 (1909/November2018Update/19H2)
Intel Core i7-8850H CPU 2.60GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.1.301
[Host]                      : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
4.8.0-beta00005             : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), …
```
=> Reduced FieldCacheImpl casting/boxing

websites/site/contributing/community-links.md, websites/site/contributing/index.md, websites/site/contributing/toc.yml
Adding a "Community Links" page to the website which links from the Contribution page at the top. We could also link here from the home page too if we want. 
I've added a few posts I know about along with the relevant links from here https://cwiki.apache.org/confluence/display/LUCENENET/Guides+and+Tutorials+from+around+the+web which i think are just Simone's links.
I've also added a few of the projects I know. 
Just wondering if there's any other obvious projects/links to put up here before it goes live? 
Here's what the page looks like
=> Website community links update

src/Lucene.Net.Tests/Index/TestIntBlockPool.cs, src/Lucene.Net.Tests/Util/TestByteBlockPool.cs
=> Lucene.Net.Tests: Removed calls to obsolete Counter.Get() method

websites/apidocs/Templates/LuceneApiDocs/layout/_master.tmpl, websites/apidocs/Templates/LuceneTemplate/layout/_master.tmpl, websites/apidocs/Templates/LuceneTemplateAssets/styles/main.css
This PR addresses issue #365 which adds the 'Fork me on GitHub' ribbon to the API docs. I added the `_master.tmpl` files to both `/websites/apidocs/Templates/LuceneApiDocs/layout/_master.tmpl` and `/websites/apidocs/Templates/LuceneTemplate/layout/_master.tmpl`. However, I was not able to test. For some reason I could not run the `docs.ps1` file. I wanted to go ahead and get the PR in, in case this fix works. If not please let me know and I will try to figure out why I can't get the `docs.ps1` file to run.
=> Add fork me on GitHub to API docs

src/Lucene.Net/Util/Automaton/State.cs
It took awhile to track it down, but with a working failure project (thanks @wilson556) and confirmation that the problem started between 4.8.0-beta00007 and 4.8.0-beta00008 the problem was traced to https://github.com/apache/lucenenet/commit/e1ead061df6ab5371979040ae8071b1bf8b18070.
It turns out that this was being caused by a subtle change from using reference equality to implementing an `Equals()` method, which was comparing the `id` value. The presumption that the `id` would be unique. It turns out that the unique identifier is the object reference and `id` might have collisions.
Fixes #296.
=> Fixes #296 - Remove Equals() from Lucene.Net.Util.Automaton.State

src/Lucene.Net/Search/FieldCacheImpl.cs
As was discussed in #371, we are definitely seeing a negative impact with this change that was introduced in #348 with commit https://github.com/apache/lucenenet/commit/34758c1315391794825f33a3f48b5a3dd6083745. This PR reverts that commit and removes the unnecessary fields from the "anonymous" classes.
<details>
<summary>Click to expand</summary>
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.572 (2004/?/20H1)
Intel Core i7-8850H CPU 2.60GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.1.403
[Host]             : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX 4.700.20.47203), X64 RyuJIT
4.8.0-beta00005    : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX 4.700.20.47203), X64 RyuJIT
4.8.0-beta00006    : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX …
```
=> Revert FieldCacheImpl delegate capture (Fixes #370, Closes #371)

src/docs/JavaDocToMarkdownConverter/JavaDocToMarkdownConverter.csproj, src/docs/LuceneDocsPlugins/EnvironmentVariableInlineRule.cs, src/docs/LuceneDocsPlugins/LuceneDfmEngineCustomizer.cs, src/docs/LuceneDocsPlugins/LuceneDocsPlugins.csproj, websites/apidocs/docs.ps1, websites/apidocs/index.md, websites/site/contributing/documentation.md, websites/site/site.ps1
Streamlines some of the build operations:
* Uses powershell flags instead of 0/1
* Updates docs on how to run the scripts including their params
* re-enables our docfx plugins with custom MD parsers so the lucene version is automatically applied throughout the docs
* Ensures the correct base path is used when building the docs for release so that linking works correctly
I have run this locally and the docs build so perhaps it fixes this? https://github.com/apache/lucenenet/issues/380
=> Website updates (from oct 2020)

src/Lucene.Net.Tests.Facet/AssertingSubDocsAtOnceCollector.cs, src/Lucene.Net.Tests.Facet/FacetTestCase.cs, src/Lucene.Net.Tests.Facet/Range/TestRangeFacetCounts.cs, src/Lucene.Net.Tests.Facet/SlowRAMDirectory.cs, src/Lucene.Net.Tests.Facet/SortedSet/TestSortedSetDocValuesFacets.cs, src/Lucene.Net.Tests.Facet/Taxonomy/Directory/TestAddTaxonomy.cs, src/Lucene.Net.Tests.Facet/Taxonomy/Directory/TestConcurrentFacetedIndexing.cs, src/Lucene.Net.Tests.Facet/Taxonomy/Directory/TestDirectoryTaxonomyReader.cs, src/Lucene.Net.Tests.Facet/Taxonomy/Directory/TestDirectoryTaxonomyWriter.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestCachedOrdinalsReader.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestFacetLabel.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestLRUHashMap.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestSearcherTaxonomyManager.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyCombined.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyFacetAssociations.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyFacetCounts.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyFacetCounts2.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyFacetSumValueSource.cs, src/Lucene.Net.Tests.Facet/Taxonomy/WriterCache/TestCompactLabelToOrdinal.cs, src/Lucene.Net.Tests.Facet/TestDrillDownQuery.cs, src/Lucene.Net.Tests.Facet/TestDrillSideways.cs, src/Lucene.Net.Tests.Facet/TestFacetsConfig.cs, src/Lucene.Net.Tests.Facet/TestMultipleIndexFields.cs, src/Lucene.Net.Tests.Facet/TestRandomSamplingFacetsCollector.cs
Fixes some bugs and formatting issues with the tests in `Lucene.Net.Tests.Facet`.
=> Review of Lucene.Net.Tests.Facet (See #259)

src/Lucene.Net.Tests.Classification/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Classification/Utils/DataSplitterTest.cs
Reviewed classification tests. Made minor changes and uncommented 1 test and verified it passes.  See issue #259
=> Reviewed classification tests and made minor changes. Part of issue #259

.editorconfig, src/Lucene.Net.Tests.Expressions/JS/TestCustomFunctions.cs, src/Lucene.Net.Tests.Expressions/JS/TestJavascriptCompiler.cs, src/Lucene.Net.Tests.Expressions/JS/TestJavascriptOperations.cs, src/Lucene.Net.Tests.Expressions/TestDemoExpressions.cs, src/Lucene.Net.Tests.Expressions/TestExpressionRescorer.cs, src/Lucene.Net.Tests.Expressions/TestExpressionSortField.cs, src/Lucene.Net.Tests.Expressions/TestExpressionSorts.cs, src/Lucene.Net.Tests.Expressions/TestExpressionValueSource.cs
Mostly code formatting tweaks.  Did find one Test not ported at all and I added a comment as such but my hunch is the test does not apply to .Net.
=> Reviewed Expression Tests as part of [Issue #259](https://github.com/apache/lucenenet/issues/259)

src/Lucene.Net.Facet/RandomSamplingFacetsCollector.cs, src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyReader.cs, src/Lucene.Net.QueryParser/Analyzing/AnalyzingQueryParser.cs, src/Lucene.Net.QueryParser/Surround/Parser/QueryParser.cs, src/Lucene.Net.QueryParser/Xml/Builders/SpanOrTermsBuilder.cs, src/Lucene.Net.QueryParser/Xml/Builders/TermsFilterBuilder.cs, src/Lucene.Net.QueryParser/Xml/Builders/TermsQueryBuilder.cs, src/Lucene.Net.QueryParser/Xml/Builders/UserInputQueryBuilder.cs, src/Lucene.Net.Replicator/Http/HttpClientBase.cs, src/Lucene.Net.TestFramework/Analysis/BaseTokenStreamTestCase.cs, src/Lucene.Net.TestFramework/Analysis/CollationTestBase.cs, src/Lucene.Net.TestFramework/Store/BaseDirectoryTestCase.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Core/TestBugInSomething.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Miscellaneous/TestCodepointCountFilterFactory.cs, src/Lucene.Net.Tests.Expressions/JS/TestJavascriptCompiler.cs, src/Lucene.Net.Tests/Index/TestConcurrentMergeScheduler.cs, src/Lucene.Net.Tests/Index/TestFieldsReader.cs, src/Lucene.Net.Tests/Index/TestPersistentSnapshotDeletionPolicy.cs, src/Lucene.Net.Tests/Search/TestBoolean2.cs, src/Lucene.Net.Tests/Search/TestControlledRealTimeReopenThread.cs, src/Lucene.Net.Tests/Search/TestTimeLimitingCollector.cs, src/Lucene.Net/Store/ByteBufferIndexInput.cs, src/Lucene.Net/Store/LockStressTest.cs, src/Lucene.Net/Util/IOUtils.cs, src/Lucene.Net/Util/VirtualMethod.cs
This is a review to ensure that stack details are always preserved either by using `throw` without specifying the exception, or by using `innerException` of a new exception class instance.
It also fixes `DirectoryTaxonomyReader.ToString(int)` so it logs any exceptions instead of throwing them, as was the case in Lucene. For the time being, they are being written to `System.Diagnostics.Trace`.
=> Reviewed catch clauses and made improvements to preserve stack details

src/Lucene.Net.Facet/Taxonomy/CachedOrdinalsReader.cs, src/Lucene.Net.Spatial/Util/ShapeFieldCacheProvider.cs, src/Lucene.Net/Util/AttributeSource.cs, src/Lucene.Net/Util/VirtualMethod.cs
See #417.
This review includes all usage of `ConditionalWeakTable<TKey, TValue>` except for `FieldCacheImpl`, which is another branch that is being worked on. It does **not** include a review of `LurchTable<TKey, TValue>` or `ConcurrentDictionary<TKey, TValue>` usage.
The `ShapeFieldCacheProvider<T>` is almost certainly the fix for #319, but since we have no way to reproduce that exception we will have to get confirmation from the user.
=> Review of ConditionalWeakTable<TKey, TValue>.GetValue() usage (See #417)

Directory.Build.targets, src/Lucene.Net.Analysis.OpenNLP/Tools/OpenNLPOpsFactory.cs, src/Lucene.Net.Facet/Taxonomy/WriterCache/NameIntCacheLRU.cs, src/Lucene.Net.Join/ToParentBlockJoinCollector.cs, src/Lucene.Net.Spatial/Prefix/PrefixTreeStrategy.cs, src/Lucene.Net.TestFramework/Search/ShardSearchingTestBase.cs, src/Lucene.Net.TestFramework/Support/Configuration/TestConfigurationFactory.cs, src/Lucene.Net.TestFramework/Util/Fst/FSTTester.cs, src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs, src/Lucene.Net.TestFramework/Util/TestUtil.cs, src/Lucene.Net.Tests.Suggest/Spell/TestSpellChecker.cs, src/Lucene.Net/Search/SearcherLifetimeManager.cs, src/Lucene.Net/Support/Configuration/EnvironmentVariablesConfigurationProvider.cs, src/Lucene.Net/Support/IO/FileSupport.cs
Combined with #439, this closes #417.
This review included the following collections:
- `LurchTable<TKey, TValue>`
- `ConcurrentDictionary<TKey, TValue>`
- `ConcurrentQueue<T>`
- `ConcurrentStack<T>`
- `ConcurrentBag<T>`
- `BlockingCollection<T>`
With the exception of `FieldCacheImpl`, all access to these collections were checked to ensure proper use. Locks were added in cases where they were missing, and collections were swapped for non-synchronized versions in cases where there was no reason to use one. 
There are a few places we use `ConcurrentDictionary<TKey, TValue>` just to take advantage of the fact that its enumerator allows modification of the collection without throwing an exception. `FEATURE_DICTIONARY_REMOVE_CONTINUEENUMERATION` was added so we will be able to use …
=> Reviewed concurrent collections (Closes #417)

src/Lucene.Net.Suggest/Suggest/Fst/FSTCompletion.cs, src/Lucene.Net.Suggest/Suggest/SortedInputIterator.cs, src/Lucene.Net.Tests.Suggest/Suggest/DocumentValueSourceDictionaryTest.cs
Since `Reverse()` on collections is an expensive operation, this review is just to ensure we aren't using it unnecessarily.
There was one instance in `Lucene.Net.Suggest` where using `Stack<T>` could be used instead of reversing the output, and one instance where sorting the output was completely unnecessary. In the latter case, using `JCG.HashSet<T>` has already solved the test failures because its `Equals()` method respects set equality by default.
Also, an unnecessary lock was removed that had been added during the port.
=> Reviewed Reverse() calls

src/Lucene.Net.Benchmark/ByTask/Feeds/SpatialDocMaker.cs
Since Dictionary `this[key]` is not marked virtual in .NET, subclassing `Dictionary<string, string>` is not a valid approach. So we implement `IDictionary<string, string>` instead.
Also made note of other TODOs about missing parameters in Spatial4n: https://github.com/NightOwl888/Spatial4n/issues/1. Since we don't want to introduce breaking changes in Spatial4n, there is no need to do anything in Lucene.NET when it is fixed.
=> Fixes Lucene.Net.Benchmark.ByTask.Feeds.SpatialDocMaker.DictionaryAnonymousClass implementation

MIGRATE.md, src/Lucene.Net/migration-guide.md, websites/apidocs/docfx.core.json, websites/apidocs/docfx.json, websites/apidocs/index.md, websites/site/contributing/documentation.md
Fixes #399.
Added migration guide and updated content with .NET specifics. Note that due to limitations of DocFx, the file was added inside of the `Lucene.Net` project instead of placed at the root of the repo. A `MIGRATE.md` file at the root of the repo is also included to link to the new location.
This also adds a note in the out-of-date API docs build instructions that refer to the old `docfx.json` file rather than the new `docfx.<project>.json` files, which are the active ones.
=> Added migration guide (Fixes #399)

src/dotnet/tools/lucene-cli/docs/index.md, websites/apidocs/docs.ps1
Fixes #416.
This works around the problem that DocFx has updating tokens within fenced code blocks by doing the replacement before calling DocFx using Powershell.
I left the change to the version in the document, as the logical time to update it is when there is a release, so we just need to commit it back to the repo (we can automate this, but should start using a release branching scheme first so it doesn't happen live on `master`).
Also removed duplication of setting the environment variable and added regex validation to the version number.
=> Fixes CLI index page versioning issue (Fixes #416)

src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyReader.cs, src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyWriter.cs, src/Lucene.Net.Facet/Taxonomy/WriterCache/Cl2oTaxonomyWriterCache.cs
This reverts locking in `Lucene.Net.Facet` to the state it was in Lucene 4.8.1 and fixes some of the test slowness due to removing locks.
Also removes the timeout of 1 second that was placed in `Cl2oTaxonomyWriterCache`, which was causing intermittent test failures.
=> Reverts facet locking

MIGRATE.md, src/Lucene.Net.Analysis.Common/overview.md, src/Lucene.Net/Analysis/Analyzer.cs, src/Lucene.Net/Analysis/package.md, src/Lucene.Net/Document/package.md, src/Lucene.Net/overview.md, websites/apidocs/docfx.json, websites/apidocs/docs.ps1
This fixes code snippets, formatting, converts Java references to .NET (#284) in the following docs:
-  src\Lucene.Net\overview.md
-  src\Lucene.Net\Document\package.md
-  src\Lucene.Net\Analysis\package.md
-  src\Lucene.Net.Analysis.Common\overview.md
Also fixed the relative links in the MIGRATE.md file, updated the `docs.ps1` script to update the `toc.yml` with the latest `PackageVersion`, and fixed the copyright symbol on the API docs.
> NOTE: Since some `xref`s were not functioning under certain scenarios, relative links to the HTML documents were put in their place for the time being (see #300 about a fix for this). There were also a few direct links that were added to Microsoft's site for references to .NET types.
=> Fixes code snippets (#284) and cross-links (#300) in Lucene.Net and Lucene.Net.Analysis.Common (partial)

azure-pipelines.yml, build/azure-templates/run-tests-on-os.yml, src/Lucene.Net.Analysis.Stempel/Egothor.Stemmer/Compile.cs, src/Lucene.Net.Analysis.Stempel/Egothor.Stemmer/DiffIt.cs, src/dotnet/tools/Lucene.Net.Tests.Cli/Configuration/ConfigurationSettingsTest.cs, src/dotnet/tools/Lucene.Net.Tests.Cli/Configuration/TestConfigurationSettings.cs, src/dotnet/tools/Lucene.Net.Tests.Cli/EnvironmentTest.cs, src/dotnet/tools/Lucene.Net.Tests.Cli/InstallationTest.cs, src/dotnet/tools/lucene-cli/ConfigurationBase.cs, src/dotnet/tools/lucene-cli/Program.cs, src/dotnet/tools/lucene-cli/appsettings.json, src/dotnet/tools/lucene-cli/commands/ExitCode.cs, src/dotnet/tools/lucene-cli/commands/RootCommand.cs, src/dotnet/tools/lucene-cli/commands/analysis/AnalysisCommand.cs, src/dotnet/tools/lucene-cli/commands/benchmark/BenchmarkCommand.cs, src/dotnet/tools/lucene-cli/commands/demo/DemoCommand.cs, src/dotnet/tools/lucene-cli/commands/index/IndexCommand.cs, src/dotnet/tools/lucene-cli/commands/lock/LockCommand.cs, src/dotnet/tools/lucene-cli/lucene-cli.csproj
See #453.
This fixes the `appsettings.json` to make it optional and also adds a default `appsettings.json` to demonstrate the default settings that are available.
```json
{
"egothor": { "stemmer": { "encoding": "UTF-8" } },
"benchmark": { "work": { "dir": "work" } }
}
```
Note that `egothor:stemmer:encoding` can be set on the command line already, this is the default setting if no value is supplied. `benchmark:work:directory` can be supplied in a benchmark definition file and this is the default if it is not provided.
This serves as temporary documentation until #307 is completed.
Also, basic tests to install and run `lucene-cli` were added to ensure it can be installed and run without errors.
=> Fix for lucene-cli appsettings.json required error + installation/run tests (See #453)

build/Dependencies.props, src/Lucene.Net.Analysis.OpenNLP/Lucene.Net.Analysis.OpenNLP.csproj, src/Lucene.Net.Tests.Analysis.OpenNLP/Lucene.Net.Tests.Analysis.OpenNLP.csproj, src/Lucene.Net.Tests.Analysis.OpenNLP/TestOpenNLPSentenceBreakIterator.cs, src/Lucene.Net.Tests.Analysis.OpenNLP/TestOpenNLPTokenizerFactory.cs
See: https://github.com/apache/lucenenet/issues/460#issuecomment-813392889
The [OpenNLP.NET assembly is now strong named](https://github.com/sergey-tihon/OpenNLP.NET/issues/6), so this updates the Lucene.Net.Analysis.OpenNLP to also be strong named. This takes care of some of the friction we have had with lack of `InternalsVisibleTo` support.
=> Added Strong Name for Lucene.Net.Analysis.OpenNLP

src/Lucene.Net.Codecs/SimpleText/SimpleTextStoredFieldsWriter.cs, src/Lucene.Net.Codecs/SimpleText/SimpleTextTermVectorsWriter.cs
This is to sync with the correct Lucene 4.8.0 behavior.
=> Fix for SimpleTextStoredFieldsWriter.Abort() and SimpleTextTermVectorsWriter.Abort() to correctly swallow Dispose() exceptions

Lucene.Net.sln, build/Dependencies.props, src/Lucene.Net/Lucene.Net.csproj, src/dotnet/Lucene.Net.CodeAnalysis.CSharp/Lucene.Net.CodeAnalysis.CSharp.csproj, src/dotnet/Lucene.Net.CodeAnalysis.VisualBasic/Lucene.Net.CodeAnalysis.VisualBasic.csproj, src/dotnet/Lucene.Net.CodeAnalysis/Version.props, src/dotnet/Lucene.Net.Tests.CodeAnalysis/Lucene.Net.Tests.CodeAnalysis.csproj
Fixes #394.
This downgrades our code analyzers from .NET Standard 2.0 to .NET Standard 1.3 to fix analyzer loading issues in Visual Studio 2017 when referencing the `Lucene.Net` NuGet package.
It also downgrades `Microsoft.CodeAnalysis.CSharp.Workspaces` and `Microsoft.CodeAnalysis.VisualBasic.Workspaces` to 2.6.1 and adds direct dependencies on  `Microsoft.CodeAnalysis.CSharp` and `Microsoft.CodeAnalysis.VisualBasic`. There is an [unofficial guide that describes how this versioning works](https://roslyn-analyzers.readthedocs.io/en/latest/nuget-packages.html#nuget-packages), but this should add support for Visual Studio 15.6.1 and higher (previously it was 16.4.0 and higher).
The patch was confirmed to work on Visual Studio 15.9.29 as well as Visual Studio 16.8.2 in both C# and Visual …
=> Fix for code analyzer support on Visual Studio 2017 (fixes #394)

src/Lucene.Net.Analysis.ICU/Collation/ICUCollationDocValuesField.cs, src/Lucene.Net.Demo/Facet/AssociationsFacetsExample.cs, src/Lucene.Net.Facet/Support/Document/Extensions/DocumentExtensions.cs, src/Lucene.Net.Tests.Facet/Lucene.Net.Tests.Facet.csproj, src/Lucene.Net.Tests.Facet/Support/Document/Extensions/TestDocumentExtensions.cs, src/Lucene.Net.Tests/Support/Document/Extensions/TestDocumentExtensions.cs, src/Lucene.Net/Document/BinaryDocValuesField.cs, src/Lucene.Net/Document/Field.cs, src/Lucene.Net/Document/FloatField.cs, src/Lucene.Net/Document/IntField.cs, src/Lucene.Net/Document/LongField.cs, src/Lucene.Net/Support/Document/Extensions/DocumentExtensions.cs, src/dotnet/Lucene.Net.ICU/Support/Document/Extensions/DocumentExtensions.cs, src/dotnet/Lucene.Net.Tests.ICU/Lucene.Net.Tests.ICU.csproj, src/dotnet/Lucene.Net.Tests.ICU/Support/Document/Extensions/TestDocumentExtensions.cs
Closes #407
This moves all Document extensions to the `Lucene.Net.Documents.Extensions` namespace. This is a breaking change, but the extension methods for the `Document` class were in both the `Lucene.Net.Documents` and `Lucene.Net.Documents.Extensions` namespace and this unifies them all in a single import.
Added tests for `DocumentExtensions` in `Lucene.Net.Tests._J-S`, `Lucene.Net.Tests.ICU` and `Lucene.Net.Tests.Facet`. 
Added missing guard clauses and updated documentation of Document extension methods and some related fields.
=> Added tests for Document extension methods (Closes #407)

src/Lucene.Net/Document/FieldType.cs
The default value of `IsTokenized` changed to `false` in comments.  
The default value `NumericType.NONE` added in the comments.
=> `FieldType.cs` comments correction/improvement

src/Lucene.Net.Join/FakeScorer.cs, src/Lucene.Net.Join/Lucene.Net.Join.csproj, src/Lucene.Net.Join/Support/FixedBitSetCachingWrapperFilter.cs, src/Lucene.Net.Join/Support/JoinUtil.cs, src/Lucene.Net.Join/Support/ScoreMode.cs, src/Lucene.Net.Join/Support/ToChildBlockJoinQuery.cs, src/Lucene.Net.Join/Support/ToParentBlockJoinCollector.cs, src/Lucene.Net.Join/Support/ToParentBlockJoinFieldComparator.cs, src/Lucene.Net.Join/Support/ToParentBlockJoinQuery.cs, src/Lucene.Net.Join/Support/ToParentBlockJoinSortField.cs, src/Lucene.Net.Join/TermsCollector.cs, src/Lucene.Net.Join/TermsIncludingScoreQuery.cs, src/Lucene.Net.Join/TermsQuery.cs, src/Lucene.Net.Join/TermsWithScoreCollector.cs, src/Lucene.Net.Join/overview.md, src/Lucene.Net.Join/package.md, src/Lucene.Net.Tests.Join/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Join/Support/TestBlockJoin.cs, src/Lucene.Net.Tests.Join/Support/TestBlockJoinSorting.cs, src/Lucene.Net.Tests.Join/Support/TestBlockJoinValidation.cs, src/Lucene.Net.Tests.Join/Support/TestExceptionSerialization.cs, src/Lucene.Net.Tests.Join/Support/TestJoinUtil.cs, src/Lucene.Net.Tests/Support/ExceptionHandling/TestExceptionExtensions.cs, websites/apidocs/docfx.join.json
Moved entire `Lucene.Net.Join` namespace to `Lucene.Net.Search.Join` to match Lucene. Added duplicates of the public types in `Lucene.Net.Join` and marked them `Obsolete` and hidden from Intellisense so this is not a breaking change. Also added duplicate tests to ensure the "old" types in `Lucene.Net.Join` function until they are removed.
=> Moved Lucene.Net.Join types to Lucene.Net.Search.Join namespace

src/Lucene.Net.Facet/FacetField.cs, src/Lucene.Net.Facet/SortedSet/SortedSetDocValuesFacetField.cs, src/Lucene.Net.Facet/Taxonomy/AssociationFacetField.cs, src/Lucene.Net.Spatial/Prefix/PrefixTreeStrategy.cs, src/Lucene.Net.TestFramework/Index/BasePostingsFormatTestCase.cs, src/Lucene.Net.TestFramework/Index/BaseTermVectorsFormatTestCase.cs, src/Lucene.Net.Tests.Misc/Index/Sorter/SorterTestBase.cs, src/Lucene.Net.Tests/Support/Document/Extensions/TestDocumentExtensions.cs, src/Lucene.Net/Document/BinaryDocValuesField.cs, src/Lucene.Net/Document/DoubleField.cs, src/Lucene.Net/Document/FieldType.cs, src/Lucene.Net/Document/FloatField.cs, src/Lucene.Net/Document/IntField.cs, src/Lucene.Net/Document/LongField.cs, src/Lucene.Net/Document/NumericDocValuesField.cs, src/Lucene.Net/Document/SortedDocValuesField.cs, src/Lucene.Net/Document/SortedSetDocValuesField.cs, src/Lucene.Net/Document/StoredField.cs, src/Lucene.Net/Document/StringField.cs, src/Lucene.Net/Document/TextField.cs
Changed `Lucene.Net.Documents.FieldType::Freeze()` from void return to return this `FieldType`. This allows chaining the method at the end of a class initializer so the entire `FieldType` instance can be created on one line (which is important for static field initializers).
Chained the `Freeze()` method in all static field initializers of `Field` subclasses to eliminate extra helper load methods. 
Marked `BinaryDocValuesField.fType` static field obsolete and added `BinaryDocValuesField.TYPE` static field as it was in Lucene.
=> Changed Lucene.Net.Documents.FieldType::Freeze() to return a reference to this

src/Lucene.Net.Grouping/AbstractSecondPassGroupingCollector.cs, src/Lucene.Net.Grouping/BlockGroupingCollector.cs, src/Lucene.Net.Grouping/TopGroups.cs, src/Lucene.Net.Join/Support/ToParentBlockJoinCollector.cs, src/Lucene.Net.Join/ToParentBlockJoinCollector.cs, src/Lucene.Net.Tests.TestFramework/Codecs/Compressing/TestCompressingStoredFieldsFormat.cs, src/Lucene.Net/Search/TopDocs.cs
Changed all references that were `float.MinValue` and `double.MinValue` to `float.Epsilon` and `double.Epsilon` because those are the .NET equivalent constants to `Float.MIN_VALUE` and `Double.MIN_VALUE` in Java
- [Why is Double.MIN_VALUE in not negative](https://stackoverflow.com/a/3884879)
- [Why is Float.MIN_VALUE in Java a positive value?](https://stackoverflow.com/a/11420190)
- [Java: Float.MIN_VALUE vs Float.MIN_NORMAL](https://programming.guide/java/float-min-value-vs-float-min-normal.html)
- [Float Javadocs](https://docs.oracle.com/javase/7/docs/api/java/lang/Float.html#MIN_VALUE)
=> BUG: Changed usage of floating point MinValue constants to Epsilon to match Java

src/Lucene.Net/Util/BytesRef.cs
Improved debugger experience for BytesRef.  In addition to the decimal bytes values it now shows the BytesRef as a Utf8String.  If the BytesRef is not a Utf8 string that representation will just be gibberish.
=> Improved debugger experience for BytesRef

src/Lucene.Net.Grouping/AbstractSecondPassGroupingCollector.cs, src/Lucene.Net.Grouping/SearchGroup.cs, src/dotnet/tools/Lucene.Net.Tests.Cli/EnumerableExtensions.cs
Hello,
This pull request is _very simple_ and aims to reduce the technical debt. It specifically targets the "Any() should be used to test for emptiness" [rule](https://rules.sonarsource.com/csharp/RSPEC-1155) in SonarQube.
Let me know if you are interested in similar contributions.
Best,
Martin
=> Fix SonarQube's "Any() should be used to test for emptiness" / Code Smell

src/Lucene.Net.Analysis.Common/Analysis/CharFilter/HTMLStripCharFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/CharFilter/MappingCharFilterFactory.cs, src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs, src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/WordDelimiterFilterFactory.cs, src/Lucene.Net.Analysis.Stempel/Egothor.Stemmer/DiffIt.cs, src/Lucene.Net.Highlighter/Highlight/GradientFormatter.cs, src/Lucene.Net/Index/CheckIndex.cs, src/Lucene.Net/Index/PersistentSnapshotDeletionPolicy.cs, src/Lucene.Net/Util/Automaton/RegExp.cs
SWEEP: Replaced Substring method where appropriate with the overloads of number class Parse/TryParse that accept startIndex and length
=> PERFORMANCE: Use overloads of J2N Parse/TryParse that accept offsets rather than allocating substrings

src/Lucene.Net.QueryParser/Flexible/Core/Nodes/QueryNode.cs, src/Lucene.Net.QueryParser/Flexible/Core/Nodes/QueryNodeImpl.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Core/Nodes/TestQueryNode.cs
Patches [LUCENE-5805: QueryNodeImpl.removeFromParent does a lot of work without any effect](https://issues.apache.org/jira/browse/LUCENE-5805).
Also adds a .NETified `TryGetTag()` method to combine the `ContainsTag()` and `GetTag()` operations.
=> BREAKING: QueryParser.Flexible updates

README.md
When I was trying to generate nuget files from master for the first time I miss understood the instructions and thought I needed to run build from powershell.  But later realized that while powershell is required by the script, the execution of the script needs to be at a command prompt.  I was also unclear in what ways I might be able to modify the version number PackageVersion in order to distinguish the generated private build nuget files from a publicly released beta one.  After being successful I'm now updating the readme file to include my learnings to make it easier for the next person.  The existing docs were already great.  Hopefully this makes them a bit better.
=> Added additional "Building and Testing" info to the repo's readme file

src/Lucene.Net.Tests/Search/TestControlledRealTimeReopenThread.cs, src/Lucene.Net/Search/ControlledRealTimeReopenThread.cs
Added two additional demonstration tests for ControlledRealTimeReopenThread that make it easier to see how to use the class.  One of the tests, TestMultithreadedWaitForGeneration, demonstrates that the current implemention of the ControlledRealTimeReopenThread class is flawed when used in multi-thread situations. This test will fail currently but I will then add another commit that improves the ControlledRealTimeReopenThread class so that it's a more faithful port of the java version and then the test will pass.
=> Two additional ControlledRealTimeReopenThread tests

README.md
Fixed an example that perviously worked but no longer does.  The improved example works without error.
=> BUG: README.md - fixed broken example

src/Lucene.Net.Tests/Search/TestControlledRealTimeReopenThread.cs, src/Lucene.Net/Search/ControlledRealTimeReopenThread.cs
Reverts apache/lucenenet#513
This PR was causing frequent crashes on the `Lucene.Net.Tests._J-S` tests, so reverting to keep the build functional.
=> Revert "Bug Fix: Re-ported ControlledRealTimeReopenThread and added 2 new tests"

Directory.Build.targets, src/Lucene.Net.Benchmark/ByTask/Tasks/TaskSequence.cs, src/Lucene.Net.TestFramework/Index/RandomIndexWriter.cs, src/Lucene.Net.TestFramework/Store/BaseDirectoryTestCase.cs, src/Lucene.Net.TestFramework/Store/MockDirectoryWrapper.cs, src/Lucene.Net.TestFramework/Store/MockIndexOutputWrapper.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyCombined.cs, src/Lucene.Net.Tests.Suggest/Spell/TestSpellChecker.cs, src/Lucene.Net.Tests.Suggest/Suggest/Analyzing/AnalyzingInfixSuggesterTest.cs, src/Lucene.Net.Tests/Index/TestAddIndexes.cs, src/Lucene.Net.Tests/Index/TestDocumentsWriterStallControl.cs, src/Lucene.Net.Tests/Index/TestIndexWriter.cs, src/Lucene.Net.Tests/Index/TestIndexWriterMerging.cs, src/Lucene.Net.Tests/Index/TestIndexWriterWithThreads.cs, src/Lucene.Net.Tests/Index/TestStressIndexing2.cs, src/Lucene.Net.Tests/Search/TestControlledRealTimeReopenThread.cs, src/Lucene.Net.Tests/TestWorstCaseTestBehavior.cs, src/Lucene.Net/Support/Index/TaskMergeScheduler.cs
Removed FEATURE_THREAD_YIELD and FEATURE_THREAD_PRIORITY, both features that pertained only to .NET Standard 1.1.
- Reviewed and changed all instances of `Thread.Sleep(0)` back to `Thread.Yield()` (as was the case in Lucene). `Thread.Sleep(0)` was a workaround on .NET Standard 1.1.
This fixes some issues with deadlocks during test runs (noticed when #511 was submitted).
An unrelated bug in `TestIndexWriterWithThreads` (introduced in #476) was also found and fixed.
=> Removed FEATURE_THREAD_YIELD and FEATURE_THREAD_PRIORITY

Directory.Build.targets, build/Dependencies.props, src/Lucene.Net.Replicator/Http/HttpClientBase.cs, src/Lucene.Net.Replicator/Http/HttpReplicator.cs, src/Lucene.Net.Replicator/Http/ReplicationService.cs, src/Lucene.Net.Replicator/IndexAndTaxonomyReplicationHandler.cs, src/Lucene.Net.Replicator/IndexReplicationHandler.cs, src/Lucene.Net.Replicator/IndexRevision.cs, src/Lucene.Net.Replicator/LocalReplicator.cs, src/Lucene.Net.Replicator/PerSessionDirectoryFactory.cs, src/Lucene.Net.Replicator/ReplicationClient.cs, src/Lucene.Net.Tests.Replicator/Http/HttpReplicatorTest.cs, src/Lucene.Net.Tests.Replicator/Http/ReplicationServlet.cs, src/Lucene.Net.Tests.Replicator/IndexAndTaxonomyReplicationClientTest.cs, src/Lucene.Net.Tests.Replicator/IndexReplicationClientTest.cs, src/Lucene.Net.Tests.Replicator/Properties/AssemblyInfo.cs, src/Lucene.Net.Tests.Replicator/ReplicatorTestCase.cs, src/Lucene.Net/Support/ExceptionHandling/Exceptions/ServletException.cs
This fixes several issues with `Lucene.Net.Replicator`.
- `Lucene.Net.Replicator.Http.HttpReplicatorTest::TestBasic()`
This was failing due to the `Timeout` value being set to 1 second instead of the 60 second value that was used in Java. It has been increased to the .NET default of 100 seconds.
Fixes #363
- `Lucene.Net.Replicator.IndexAndTaxonomyReplicationClientTest::TestConsistencyOnExceptions()`
- `Lucene.Net.Replicator.IndexReplicationClientTest::TestConsistencyOnExceptions()`
These were failing due to the fact that they were throwing exceptions on the worker thread, which causes it to stop immediately when they are unhandled. The `Lucene.Net.Replicator.ReplicationClient.ReplicationThread` class was re-ported from Lucene 4.8.1 to subclass `ThreadJob` which handles re-throwing any …
=> Lucene.Net.Replicator Bug Fixes (Fixes #363)

src/Lucene.Net.Codecs/BlockTerms/BlockTermsReader.cs, src/Lucene.Net.Codecs/Bloom/BloomFilteringPostingsFormat.cs, src/Lucene.Net.Codecs/Memory/FSTOrdTermsReader.cs, src/Lucene.Net.Codecs/Memory/FSTTermsReader.cs, src/Lucene.Net.Codecs/Memory/MemoryDocValuesProducer.cs, src/Lucene.Net.Codecs/Memory/MemoryPostingsFormat.cs, src/Lucene.Net.Codecs/SimpleText/SimpleTextFieldsReader.cs, src/Lucene.Net.Codecs/SimpleText/SimpleTextTermVectorsReader.cs, src/Lucene.Net.Memory/MemoryIndex.MemoryIndexReader.cs, src/Lucene.Net.TestFramework/Codecs/RAMOnly/RAMOnlyPostingsFormat.cs, src/Lucene.Net.TestFramework/Index/AssertingAtomicReader.cs, src/Lucene.Net/Codecs/BlockTreeTermsReader.cs, src/Lucene.Net/Codecs/Compressing/CompressingTermVectorsReader.cs, src/Lucene.Net/Codecs/Lucene3x/Lucene3xFields.cs, src/Lucene.Net/Codecs/Lucene3x/Lucene3xTermVectorsReader.cs, src/Lucene.Net/Codecs/Lucene40/Lucene40TermVectorsReader.cs, src/Lucene.Net/Codecs/Lucene42/Lucene42DocValuesProducer.cs, src/Lucene.Net/Codecs/Lucene45/Lucene45DocValuesProducer.cs, src/Lucene.Net/Index/FilterAtomicReader.cs, src/Lucene.Net/Index/FilteredTermsEnum.cs, src/Lucene.Net/Index/SortedDocValuesTermsEnum.cs, src/Lucene.Net/Index/SortedSetDocValuesTermsEnum.cs, src/Lucene.Net/Search/FuzzyTermsEnum.cs
The original logic returned a `null` `BytesRef` instance to indicate that iteration is finished. We correctly got the `false` case when Lucene explicitly returned `null`, but in cases where it may have implicitly returned a `null` `BytesRef` we need to explicitly return `term != null` rather than `true` to ensure we correctly signal the end of iteration.
=> BUG: Modified all TermsEnum.MoveNext() methods to return a check for null rather than returning true

src/Lucene.Net.TestFramework/Index/BasePostingsFormatTestCase.cs
Removed `IndexOptions.NONE` from the list of available options, since this option is not valid for the tests. It was added as a placeholder for `null`, since in .NET `enum` is a value type.
=> BUG: Lucene.Net.TestFramework.Index.BasePostingsFormatTestCase: Removed IndexOptions.NONE from the list of available options

src/Lucene.Net.Grouping/Term/TermAllGroupHeadsCollector.cs, src/Lucene.Net.Tests.Grouping/AllGroupHeadsCollectorTest.cs
Fixes `AllGroupHeadCollectorTest.TestRandom()` on .NET Framework x86
=> BUG: Lucene.Net.Grouping.Term.TermAllGroupHeadsCollector: Use NumericUtils.SingleToSortableInt32() to compare floating point numbers

src/Lucene.Net.Codecs/SimpleText/SimpleTextFieldsReader.cs
Assert statement was using `BytesRef.Utf8ToString()`, which was causing exceptions when the `BytesRef` didn't contain valid UTF8. Changed to use [`BytesRefFormatter`](Lucene.Net.Codecs.SimpleText.SimpleTextFieldsReader::NextDoc()), which defers the call to convert the `BytesRef` until after the assert fails.
This was causing several tests to randomly fail that use `SimpleText` to compare other codecs with.
=> BUG: Lucene.Net.Codecs.SimpleText.SimpleTextFieldsReader::NextDoc(): Fixed assert that was throwing on BytesRef.Utf8ToString()

src/Lucene.Net/Util/Automaton/MinimizationOperations.cs, src/Lucene.Net/Util/FixedBitSet.cs, src/Lucene.Net/Util/OpenBitSet.cs
`OpenBitSet.Clear()` requires parameters, unlike `java.util.BitSet`. However, the second parameter of `OpenBitSet.Clear()` must be **one past** the end index per the docs. This was causing `Lucene.Net.Codecs.Lucene41.TestBlockPostingsFormat3.Test()` to fail randomly with an `IndexOutOfRangeException` and affects all components that depend on `Lucene.Net.Util.Automaton`.
=> BUG: Lucene.Net.Util.Automation.MinimizationOperations::MinimizeHopcroft(): Fixed range in OpenBitSet.Clear()

src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestQPHelper.cs
This was causing `Lucene.Net.Tests.QueryParser.Flexible.Standard.TestQPHelper::TestDateRange()` to fail when the random culture is Arabic.
Reference: https://github.com/dotnet/runtime/issues/61708#issuecomment-971116350
=> BUG: Lucene.Net.Tests.QueryParser.Flexible.Standard.TestQPHelper: Use ParseExact to specify the date format

src/Lucene.Net.Suggest/Suggest/Jaspell/JaspellTernarySearchTrie.cs, src/Lucene.Net.Tests.Analysis.Common/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Analysis.Kuromoji/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Analysis.Phonetic/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Analysis.SmartCn/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Analysis.Stempel/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Benchmark/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Classification/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Codecs/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Grouping/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Highlighter/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Join/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Memory/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Misc/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Queries/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Sandbox/Support/TestApiConsistency.cs, src/Lucene.Net.Tests.Suggest/Support/TestApiConsistency.cs, src/dotnet/Lucene.Net.Tests.ICU/Support/TestApiConsistency.cs
Lazy initialize a `J2N.Randomizer()` instance so we hit both paths approximately evenly instead of one path when deleting nodes recursively. The previous implementation used a `System.Random`, but always initialized it to the same seed, so we didn't actually generate random numbers.
=> BUG: Lucene.Net.Suggest.Jaspell.JaspellTernarySearchTree: Fixed random number generator so it produces random numbers

src/Lucene.Net.TestFramework/Util/TestUtil.cs
`J2N.Randomizer.Next(int)` throws `ArgumentOutOfRangeException` when the argument is 0 (confirmed this is how it works in Java). So, we need to skip the method in that case and pass 0 through.
This bug was carried over from Lucene and still exists in their codebase.
=> BUG: Lucene.Net.TestFramework.Util.TestUtil::RandomAnalysisString(): Fixed ArgumentOutOfRangeException

src/Lucene.Net.TestFramework/Util/TestUtil.cs, src/Lucene.Net.Tests/Index/TestIndexWriter.cs, src/Lucene.Net.Tests/Index/TestIndexWriterOnJRECrash.cs, src/Lucene.Net.Tests/Support/Threading/TestUninterruptableMonitor.cs, src/Lucene.Net/Index/IndexWriter.cs, src/Lucene.Net/Store/FSDirectory.cs, src/Lucene.Net/Store/NIOFSDirectory.cs
Closes #526  and closes #544.
This PR just adds the [Ignore] attribute to the following tests and updates the `IndexWriter` and directory documentation to indicate that `Thread.Interrupt()` is not supported in Lucene.NET due to the high possibility that it could break a `Commit()` or cause a deadlock.
- [Lucene.Net.TestIndexWriter.TestThreadInterruptDeadlock()](https://github.com/apache/lucenenet/blob/54c9a76ea22a1451e899577b296d4a58382d6a76/src/Lucene.Net.Tests/Index/TestIndexWriter.cs#L1480)
- [Lucene.Net.TestIndexWriter.TestTwoThreadsInterruptDeadlock()](https://github.com/apache/lucenenet/blob/54c9a76ea22a1451e899577b296d4a58382d6a76/src/Lucene.Net.Tests/Index/TestIndexWriter.cs#L1521)
- [Lucene.Net.Support.Threading.TestUninterruptableMonitor.TestThreadInterrupt()](https://github.com/ …
=> Deprecated support for Thread.Interrupt()

src/Lucene.Net.Tests/Search/TestSimpleExplanations.cs, src/Lucene.Net/Search/DisjunctionMaxScorer.cs
.NET Framework x86 requires an explicit cast to float to prevent it from losing precision. Fixes #546.
=> BUG: Lucene.Net.Search.DisjunctionMaxScorer: x86 floating point precision issue (fixes #546)

src/Lucene.Net.Expressions/ScoreFunctionValues.cs
Changed to explicit cast to (float) to prevent JIT from losing precision when assigning the value to double. Fixes `Lucene.Net.Expressions.TestExpressionSorts::TestQueries()`.
Reproducible in `net48`, x86, Release mode with the following attributes.
```c#
[assembly: Lucene.Net.Util.RandomSeed(0x23cc862e070f9ee8)]
[assembly: NUnit.Framework.SetCulture("lo")]
```
=> BUG: Lucene.Net.Expressions.ScoreFunctionValues: Fixed x86 floating point issue

build/Dependencies.props, src/Lucene.Net.QueryParser/Flexible/Standard/Config/NumberDateFormat.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestNumericQueryParser.cs, src/Lucene.Net.Tests.QueryParser/Lucene.Net.Tests.QueryParser.csproj, src/Lucene.Net.Tests.QueryParser/Support/Flexible/Standard/Config/TestNumberDateFormat.cs, src/Lucene.Net.Tests.QueryParser/Support/TestApiConsistency.cs, src/Lucene.Net/Support/Util/NumberFormat.cs
- Fixed calendar check so we don't produce random numbers that are out of bounds of the calendar of the random culture
- Added TimeZone support
- BREAKING: Changed constructors of `Lucene.Net.Util.NumberFormat` and `Lucene.Net.QueryParsers.Flexible.Standard.Config.NumberDateFormat` to accept `IFormatProvider` rather than `CultureInfo` and changed `NumberFormat.Culture` property to `NumberFormat.FormatProvider`.
=> BUG: Lucene.Net.QueryParser.Flexible.Standard: Fixed calendar handling on .NET Core

src/Lucene.Net.Tests.Spatial/Prefix/SpatialOpRecursivePrefixTreeTest.cs
Ported over patch from https://github.com/apache/lucene/commit/e9906a334b8e123e93b917c3feb6e55fed0a8c57 (from Lucene 4.9.0) (fixes #559).
Contains requires a non-geo instance of `SpatialContext` to compare corners, otherwise it may match in cases where it isn't supposed to. This is entirely a patch that fixes the test, it has no impact on the production code.
The test was made non-random and ported to Java to determine whether or not the same issue happens in Lucene (and it does). Here are the tests:
```c#
[Test]
[LuceneNetSpecific]
public virtual void TestContains_Fixed()
{
this.ctx = SpatialContext.GEO;
////A fairly shallow grid, and default 2.5% distErrPct
//if (maxLevels == -1)
//    maxLevels = randomIntBetween(1, 3);//max 16k cells (32^3)
this.grid = new GeohashPrefixTree(ctx, …
```
=> BUG: Lucene.Net.Spatial.Prefix.SpatialOpRecursivePrefixTreeTest::TestContains() (fixes #559)

src/Lucene.Net.Tests.Join/Support/TestJoinUtil.cs, src/Lucene.Net.Tests.Join/TestJoinUtil.cs, src/Lucene.Net/Search/TermScorer.cs
`Lucene.Net.Search.TermScorer`: Added cast to fix calculation in .NET Framework x86 with optimizations enabled (fixes #549 / `Lucene.Net.Search.TestJoinUtil::TestMultiValueRandomJoin()`).
=> BUG: Lucene.Net.Search.TestJoinUtil::TestMultiValueRandomJoin() (fixes #549)

src/Lucene.Net.Tests/Codecs/Lucene3x/TestTermInfosReaderIndex.cs, src/Lucene.Net.Tests/Index/TestCodecs.cs, src/Lucene.Net.Tests/Index/TestConsistentFieldNumbers.cs, src/Lucene.Net/Index/CheckIndex.cs, src/Lucene.Net/Index/IndexFileNames.cs, src/Lucene.Net/Index/IndexWriter.cs, src/Lucene.Net/Index/ReadersAndUpdates.cs, src/Lucene.Net/Index/SegmentDocValues.cs, src/Lucene.Net/Index/SegmentInfos.cs, src/Lucene.Net/Index/SegmentReader.cs
Fixes #573. This is a breaking change. The segment file names were being generated in base 10 rather than base 36 (Character.MaxRadix), which caused us to generate different segment file names than Lucene and Lucene.NET 3.x. This changes the base back to 36, but it means 4.8.0-beta00016 and beyond will not be able to read indexes produced by previous betas by default.
To fix this, we added a `SegmentInfos.UseLegacySegmentNames` setting to read 4.8.0-beta00001 thru 4.8.0-beta00015 indexes, which is `false` by default. Setting to `true` at application startup will enable reading indexes from prior beta versions (with broken segment names).
> NOTE: We recommend regenerating your indexes, if possible, rather than using this "feature". Enabling this makes the file names inconsistent. Some …
=> BUG: Fixes #573. Changed segment names to match Lucene 4.8.0 and Lucene.NET 3.x

src/Lucene.Net/Index/BinaryDocValuesFieldUpdates.cs, src/Lucene.Net/Index/BufferedUpdates.cs, src/Lucene.Net/Index/BufferedUpdatesStream.cs, src/Lucene.Net/Index/CoalescedUpdates.cs, src/Lucene.Net/Index/DocValuesFieldUpdates.cs, src/Lucene.Net/Index/DocValuesUpdate.cs, src/Lucene.Net/Index/DocumentsWriter.cs, src/Lucene.Net/Index/DocumentsWriterDeleteQueue.cs, src/Lucene.Net/Index/FrozenBufferedUpdates.cs, src/Lucene.Net/Index/IndexWriter.cs, src/Lucene.Net/Index/NumericDocValuesFieldUpdates.cs, src/Lucene.Net/Index/ReadersAndUpdates.cs
Refactored so the subclasses will handle getting the values from `DocValuesFieldUpdatesIterator` or `DocValuesUpdate` via a cast rather than boxing the value. Also marked internal (as well as all members of `BufferedUpdates`), since this was not supposed to be part of the public API.
=> BREAKING: Lucene.Net.Index.DocValuesFieldUpdates: Fixed boxing issue

src/Lucene.Net.Misc/Index/IndexSplitter.cs, src/Lucene.Net.Tests.Misc/Index/TestIndexSplitter.cs, src/Lucene.Net.Tests/Index/TestConsistentFieldNumbers.cs, src/Lucene.Net.Tests/Index/TestPerSegmentDeletes.cs, src/Lucene.Net.Tests/Index/TestSizeBoundedForceMerge.cs, src/Lucene.Net/Index/CheckIndex.cs, src/Lucene.Net/Index/IndexWriter.cs, src/Lucene.Net/Index/LogMergePolicy.cs, src/Lucene.Net/Index/SegmentInfos.cs, src/Lucene.Net/Index/StandardDirectoryReader.cs
Changed `Lucene.Net.Index.SegmentInfos.Info()` method into an indexer for the class to make it simpler to understand (we had `Infos.Info(x).Info.Name`, it is now `Infos[x].Info.Name`). Marked `Info()` obsolete.
=> BREAKING: Lucene.Net.Index.SegmentInfos: Changed Info() method to an indexer (.NET Convention)

src/Lucene.Net.Facet/FacetResult.cs, src/Lucene.Net.Facet/LabelAndValue.cs, src/Lucene.Net.Tests.Demo/Facet/TestAssociationsFacetsExample.cs, src/Lucene.Net.Tests.Demo/Facet/TestExpressionAggregationFacetsExample.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyFacetAssociations.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyFacetCounts.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyFacetSumValueSource.cs, src/Lucene.Net/Support/Arrays.cs
Added overload of `ToString()` that accepts `IFormatProvider` to `FacetResult` and `LabelAndValue` classes. Also implemented `IFormattable` on both classes.
The default format has changed from invariant culture to current culture to match .NET.
=> Lucene.Net.Facet: Added culture-sensitve ToString() overload on FacetResult and LabelAndValue

src/Lucene.Net.TestFramework/Index/ThreadedIndexingAndSearchingTestCase.cs, src/Lucene.Net.Tests/Search/TestControlledRealTimeReopenThread.cs, src/Lucene.Net/Index/IndexReader.cs, src/Lucene.Net/Search/ControlledRealTimeReopenThread.cs
See #513 and #519.
This re-applies the changes that were introduced in #513 and patches them so they don't deadlock on macOS.
- Lock was removed from `Dispose(bool)`
- `AtomicBoolean` added to ensure `Dispose(bool)` is only entered by a single thread.
- `AtomicInt64` added for `refreshStartGen`, which is updated and read outside of locks.
- Use constants for second/millisecond/nanosecond conversions.
- Ignored `TestStraightForwardDemonstration()` and `TestMultithreadedWaitForGeneration()`, since they often fail in CI because of timing check failures (tolerance is too low)
- Renamed `intrinsic` field to `m_signal` and marked it protected so subclasses can receive signaling events.
- Use `ConcurrentSet<T>` rather than `ConcurrentHashSet<T>` in `ThreadedIndexingAndSearchingTestCase`.
- Use …
=> Lucene.Net.Search.ControlledRealTimeReopenThread: Refactor to integrate changes from #513

src/Lucene.Net.Benchmark/ByTask/Feeds/DocData.cs, src/Lucene.Net.Benchmark/ByTask/Feeds/TrecContentSource.cs, src/Lucene.Net.QueryParser/Classic/QueryParser.cs, src/Lucene.Net.QueryParser/Classic/QueryParserBase.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Builders/NumericRangeQueryNodeBuilder.cs, src/Lucene.Net.QueryParser/Flexible/Standard/CommonQueryParserConfiguration.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Config/FieldDateResolutionFCListener.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Config/NumberDateFormat.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Config/StandardQueryConfigHandler.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Nodes/NumericQueryNode.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Nodes/NumericRangeQueryNode.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Processors/NumericQueryNodeProcessor.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Processors/NumericRangeQueryNodeProcessor.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Processors/TermRangeQueryNodeProcessor.cs, src/Lucene.Net.QueryParser/Flexible/Standard/StandardQueryParser.cs, src/Lucene.Net.Tests.QueryParser/Classic/TestQueryParser.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Precedence/TestPrecedenceQueryParser.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestNumericQueryParser.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestQPHelper.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestStandardQP.cs, src/Lucene.Net.Tests.QueryParser/Util/QueryParserTestBase.cs, src/Lucene.Net.Tests._A-D/Lucene.Net.Tests._A-D.csproj, src/Lucene.Net.Tests/Document/TestDateTools.cs, src/Lucene.Net.Tests/Search/TestCustomSearcherSort.cs, src/Lucene.Net.Tests/Search/TestDateFilter.cs, src/Lucene.Net.Tests/Search/TestDateSort.cs, src/Lucene.Net.Tests/Support/TestApiConsistency.cs, src/Lucene.Net/Document/DateTools.cs, src/Lucene.Net/Support/DateTimeOffsetUtil.cs, src/Lucene.Net/Support/Util/NumberFormat.cs
- Added support for `TimeZoneInfo` when converting to/from string
- BREAKING: Added `NumericRepresentation` enum to allow converting to/from long in the following formats:
- Unix Epoch (default): Milliseconds since Jan 1, 1970 12:00:00 AM UTC.
- Ticks: The raw ticks from `DateTime` or `DateTimeOffset`.
- Ticks as Milliseconds: This is for compatibility with prior versions of Lucene.NET (3.0.3 and 4.8.0-beta00001 - 4.8.0-beta00015). The conversion done on input values is `time * TimeSpan.TicksPerMillisecond` and the conversion to output values is `time / TimeSpan.TicksPerMillisecond`.
- BREAKING: De-nested `Resolution` enum and renamed `DateResolution`.
- `Lucene.Net.QueryParsers.Flexible.Standard.Config.NumberDateFormat`: Added constructor overload to format a date without a time.
- …
=> BREAKING: Lucene.Net.Documents.DateTools/Lucene.Net.QueryParser Updates

src/Lucene.Net/Search/FieldCacheRangeFilter.cs
Added protected Equals(x, y) method to allow subclasses to compare equality for value types without boxing
=> PERFORAMANCE: Lucene.Net.Search.FieldCacheRangeFilter: Eliminated boxing in Equals() check

src/Lucene.Net.TestFramework/Support/Util/LuceneRandomSeedInitializer.cs, src/Lucene.Net.TestFramework/Support/Util/RandomSeedAttribute.cs, src/Lucene.Net.TestFramework/Support/Util/RandomizedContext.cs, src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
Lucene uses a compound seed that contains multiple seeds delimited by a colon. It is unclear what the purpose of this is, but this patch changes the datatype of the `RandomSeedAttribute` from long/ulong to string and changes the parsing to ignore everything after a colon so we can expand later without a breaking change.
This also prefixes the `RandomizedContext` property with an underscore, which hides it from displaying in Visual Studio Test Explorer.
=> Lucene.Net.TestFramework: Changed RandomSeedAttribute parameter to string to allow for compound seeds

src/Lucene.Net.TestFramework/Analysis/BaseTokenStreamTestCase.cs, src/Lucene.Net.TestFramework/Index/BaseStoredFieldsFormatTestCase.cs, src/Lucene.Net.TestFramework/Store/MockDirectoryWrapper.cs, src/Lucene.Net.TestFramework/Store/MockIndexOutputWrapper.cs, src/Lucene.Net.TestFramework/Support/JavaCompatibility/LuceneTestCase.cs, src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs, src/Lucene.Net.Tests.Misc/Index/TestIndexSplitter.cs, src/Lucene.Net.Tests/Index/TestCrash.cs, src/Lucene.Net.Tests/Index/TestDoc.cs, src/Lucene.Net.Tests/Index/TestIndexWriterWithThreads.cs, src/Lucene.Net.Tests/Index/TestStressIndexing.cs, src/Lucene.Net.Tests/Index/TestTransactions.cs
- Fixed the documentation comments for `LuceneTestCase`
- Adds some documentation for random seed configuration
- Implements some missing console logging
- **BREAKING:** `Lucene.Net.TestFramework.Store.MockDirectoryWrapper:` Renamed `AssertNoUnreferencedFilesOnClose` to `AssertNoUnreferencedFilesOnDispose`
=> Test Framework Updates

build/NuGet.props, build/build.ps1, src/Lucene.Net.Analysis.Common/Lucene.Net.Analysis.Common.csproj, src/Lucene.Net.Analysis.Kuromoji/Lucene.Net.Analysis.Kuromoji.csproj, src/Lucene.Net.Analysis.Morfologik/Lucene.Net.Analysis.Morfologik.csproj, src/Lucene.Net.Analysis.OpenNLP/Lucene.Net.Analysis.OpenNLP.csproj, src/Lucene.Net.Analysis.Phonetic/Lucene.Net.Analysis.Phonetic.csproj, src/Lucene.Net.Analysis.SmartCn/Lucene.Net.Analysis.SmartCn.csproj, src/Lucene.Net.Analysis.Stempel/Lucene.Net.Analysis.Stempel.csproj, src/Lucene.Net.Benchmark/Lucene.Net.Benchmark.csproj, src/Lucene.Net.Classification/Lucene.Net.Classification.csproj, src/Lucene.Net.Codecs/Lucene.Net.Codecs.csproj, src/Lucene.Net.Expressions/Lucene.Net.Expressions.csproj, src/Lucene.Net.Facet/Lucene.Net.Facet.csproj, src/Lucene.Net.Grouping/Lucene.Net.Grouping.csproj, src/Lucene.Net.Highlighter/Lucene.Net.Highlighter.csproj, src/Lucene.Net.Join/Lucene.Net.Join.csproj, src/Lucene.Net.Memory/Lucene.Net.Memory.csproj, src/Lucene.Net.Misc/Lucene.Net.Misc.csproj, src/Lucene.Net.Queries/Lucene.Net.Queries.csproj, src/Lucene.Net.QueryParser/Lucene.Net.QueryParser.csproj, src/Lucene.Net.Replicator/Lucene.Net.Replicator.csproj, src/Lucene.Net.Sandbox/Lucene.Net.Sandbox.csproj, src/Lucene.Net.Spatial/Lucene.Net.Spatial.csproj, src/Lucene.Net.Suggest/Lucene.Net.Suggest.csproj, src/Lucene.Net.TestFramework/Lucene.Net.TestFramework.csproj, src/Lucene.Net/Lucene.Net.csproj, src/Lucene.Net/readme-nuget.md, src/dotnet/Lucene.Net.ICU/Lucene.Net.ICU.csproj
- Added a `readme.md` file for the Lucene.Net NuGet package.
- Added a link to the documentation mini-site below the description for each NuGet package (except Lucene.Net and lucene-cli, which each have a readme.md)
- Added a link to the release notes in the NuGet package (`<PackageReleaseNotes>`).
- Corrected the description of several of the packages, which had copy-paste errors.
=> NuGet Readme, documentation, and release notes links

websites/site/contributing/source.md
Update the page to show current information about the  Apache's two-master setup and provided additional information about contributing source code with many links to external references.  This is pretty much a rewrite of the page.
=> Improved content of /contributing/source web page

websites/site/lucenetemplate/index.html.tmpl
The prior link was broken and went to a 404 page at Amazon.com
=> Fixed broken book link for Instant Lucene.NET

src/Lucene.Net.TestFramework/Util/TestUtil.cs
Protect `Randomizer.Next(int)` overload from being called with `maxValue` of 0, since it requires at least 1
=> BUG: Lucene.Net.TestFramework.Util.TestUtil::RandomAnalysisString(): Fixed rare ArgumentOutOfRangeException

src/Lucene.Net/Search/FieldCacheImpl.cs
Logic was inverted on `innerCache` so the value was being updated if exists, when it should not be updated in this case
=> BUG: Lucene.Net.Search.FieldCacheImpl.Cache<TKey, TValue>::Put(): Inverted cache logic

src/Lucene.Net/Store/FSDirectory.cs, src/Lucene.Net/Store/MMapDirectory.cs, src/Lucene.Net/Store/NIOFSDirectory.cs, src/Lucene.Net/Store/SimpleFSDirectory.cs, src/Lucene.Net/Support/IO/StreamExtensions.cs
Each stream in `Lucene.Net.Support.IO.StreamExtensions` was sharing a common lock, which means that multiple NIOFSDirectory instances were all competing for the same lock. This fixes it so each `FileStream` instance gets its own lock when reading.
Also updated the `FSDirectory` documentation to remove irrelevant Java info and replace it with performance characteristics of the .NET implementation.
=> PERFORMANCE: Fixed NIOFSDirectory Bottleneck

.github/workflows/Lucene-Net-Documentation.yml, Directory.Build.targets, azure-pipelines.yml, src/Directory.Build.targets, src/docs/Directory.Build.props, src/docs/Directory.Build.targets, src/docs/DocumentationTools.sln, src/docs/LuceneDocsPlugins/LuceneDocsPlugins.csproj, src/docs/LuceneDocsPlugins/Properties/AssemblyInfo.cs, websites/apidocs/docs.ps1
Fixes #601.
- Upgraded `LuceneDocsPlugins.csproj` to use new .csproj format
- Upgraded `docs.ps1` to use `dotnet publish` rather than NuGet restore and MSBuild
- Upgraded Azure Pipelines to use `windows-latest` instead of `vs2017-win2016` for docs and website
=> Upgraded build tools for LuceneDocsPlugins and moved docs/website build to windows-latest (fixes #601)

websites/apidocs/apiSpec/core/Lucene_Net_Codecs.md
Updated `Lucene.Net.Codecs` namespace documentation to demonstrate the registration using the `Initialize()` method rather than `TestFrameworkSetUp()` method.
=> docs: Updated `Lucene.Net.Codecs` DI documentation

src/Lucene.Net/Index/BaseCompositeReader.cs
Removed allocation of new `List<T>` that was added during the port to handle generic casting. Lucene [didn't have this extra allocation](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/index/BaseCompositeReader.java#L69).
=> PERFORMANCE: Lucene.Net.Index.BaseCompositeReader: Removed unnecessary list allocation

src/Lucene.Net.Analysis.SmartCn/Hhmm/SegToken.cs
It is so hard to debug without a friendly display. I just add a `DebuggerDisplay` for `SegToken`, you can also add one for `SegTokenPair` and others.
In C# 10, the attribute should be 
```csharp
[System.Diagnostics.DebuggerDisplay($"\{new string({nameof(CharArray)})\}")]
```
You can also override the `ToString` method instead.
=> Add DebuggerDisplay for SegToken

.build/azure-templates/install-dotnet-sdk.yml, .build/azure-templates/run-tests-on-os.yml, azure-pipelines.yml
There were a couple of issues with the testing strategy for x86:
1. x86 is not supported on Linux or macOS on .NET Core.
2. The .NET Core x86 tests were failing to run.
The Azure DevOps agents [require a `performMultiLevelLookup` parameter set to `true` to run x86](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops), which we weren't providing.
This fixes the build to pass the parameter in case of x86 on Windows, and removes all of the test configs for x86 on macOS/Linux.
=> Build: Fix for x86 tests

.build/dependencies.props
fixes #640
https://github.com/advisories/GHSA-5crp-9r3c-p9vr
Updated Newtonsoft.Json to 13.0.1. I ran the unit tests locally and can't see that this change breaks anything.
=> chore(deps): Update Newtonsoft.Json to 13.0.1 to avoid vulnerability

src/Lucene.Net.Analysis.Kuromoji/Dict/BinaryDictionary.cs
The `string.Format` statement would result in the following exception:
```
Unhandled exception. System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.String.Format(String format, Object arg0, Object arg1, Object arg2)
```
=> fix: Fixed throw statement in BinaryDictionary

src/Lucene.Net.Analysis.Common/Analysis/Fr/FrenchStemmer.cs
[File: FrenchStemmer.cs]
Java reference: https://github.com/apache/lucene/blob/f01152a5909fa6059f4f1d4aeb4e14968ef1d8c2/lucene/analysis/common/src/java/org/apache/lucene/analysis/fr/FrenchStemmer.java#L450-L477
I'm unsure if this is covered by and unit tests.
Detected on 3 issues here: https://sonarcloud.io/project/issues?fileUuids=AYPAuMLmhbfJOGLOoZHT&resolved=false&severities=MAJOR&types=BUG&id=nikcio_lucenenet&open=AYPAuPYNhbfJOGLOobEI
=> fix: Aligned FrenchStemmer.cs with Java code

.editorconfig
As per https://github.com/apache/lucenenet/issues/648#issuecomment-1279823136
=> .editorconfig: Added suppression for CA2249: Consider using String.Contains instead of String.IndexOf

src/Lucene.Net.Tests.Analysis.SmartCn/TestHMMChineseTokenizerFactory.cs
Added LuceneNetSpecificAttribute to `TestHHMMSegmenter()` and renamed `TestHHMMSegmenterInitialization()`, since this is a smoke test that was added to test and debug initialization of `HHMMSegmenter`.
=> Lucene.Net.Tests.Analysis.SmartCn.TestHMMChineseTokenizerFactory::TestHHMMSegmenter() Added LuceneNetSpecificAttribute

src/Lucene.Net.Analysis.SmartCn/Utility.cs
=> Lucene.Net.Analysis.Cn.Smart.Utility: Changed SPACES to use an encoded character for '\u3000' so it is visible in the designer.

src/Lucene.Net.Analysis.Common/Analysis/Nl/DutchStemmer.cs
=> fix: Fixed '&' to '&&' in DutchStemmer

src/Lucene.Net.Analysis.Common/Analysis/Util/BufferedCharFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/CharacterUtils.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/OpenStringBuilder.cs, src/Lucene.Net.Analysis.Stempel/Egothor.Stemmer/MultiTrie2.cs, src/Lucene.Net.Benchmark/ByTask/Feeds/RandomFacetSource.cs, src/Lucene.Net.Facet/Taxonomy/LRUHashMap.cs, src/Lucene.Net.Grouping/AbstractFirstPassGroupingCollector.cs, src/Lucene.Net.Spatial/Prefix/Tree/Cell.cs, src/Lucene.Net.Suggest/Suggest/Analyzing/AnalyzingInfixSuggester.cs, src/Lucene.Net/Analysis/TokenAttributes/CharTermAttribute.cs, src/Lucene.Net/Index/ConcurrentMergeScheduler.cs, src/Lucene.Net/Search/BooleanClause.cs, src/Lucene.Net/Search/SearcherLifetimeManager.cs, src/Lucene.Net/Store/BufferedIndexInput.cs, src/Lucene.Net/Store/BufferedIndexOutput.cs, src/Lucene.Net/Store/ByteBufferIndexInput.cs, src/Lucene.Net/Store/DataInput.cs, src/Lucene.Net/Store/Lock.cs, src/Lucene.Net/Store/LockStressTest.cs, src/Lucene.Net/Util/CharsRef.cs
Fixes #665.
Also addressed potential int overflow issues when checking for "index + length must be <= array length".
=> SWEEP: Fixed ArgumentOutOfRange parameters so the message is passed into the 2nd parameter.

Directory.Build.targets, src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs, src/Lucene.Net.Analysis.Common/Analysis/Pattern/PatternReplaceCharFilter.cs, src/Lucene.Net.Analysis.Phonetic/Language/DoubleMetaphone.cs, src/Lucene.Net.Benchmark/ByTask/Feeds/EnwikiContentSource.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/SearchTravRetHighlightTask.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Parser/EscapeQuerySyntaxImpl.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Parser/StandardSyntaxParser.cs, src/Lucene.Net.Replicator/Http/HttpClientBase.cs, src/Lucene.Net.Suggest/Suggest/Analyzing/AnalyzingInfixSuggester.cs, src/Lucene.Net/Util/AttributeSource.cs
Fixes #675.
While the System.Memory package allows the use of `ReadOnlySpan<T>` in all target frameworks, the methods overloads that accept `ReadOnlySpan<T>` parameters are only available in `net6.0` and in most cases, `netstandard2.1`. Therefore, at least for this use case, it was impractical to use System.Memory and we have new conditional compilation features to enable the `AsSpan()` calls when the APIs exist to utilize them.
- FEATURE_STRING_CONCAT_READONLYSPAN (`net6.0` only)
- FEATURE_NUMBER_PARSE_READONLYSPAN (`net6.0` and `netstandard2.1` only)
- FEATURE_STREAM_READ_SPAN (`net6.0` and `netstandard2.1` only)
- FEATURE_STRINGBUILDER_APPEND_READONLYSPAN (`net6.0` and `netstandard2.1` only)
=> SWEEP: Prefer 'AsSpan' over 'Substring' when span-based overloads are available

src/Lucene.Net.Benchmark/ByTask/Tasks/ReadTokensTask.cs, src/Lucene.Net.Benchmark/Support/TagSoup/PYXScanner.cs, src/Lucene.Net.Benchmark/Support/TagSoup/PYXWriter.cs, src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyWriter.cs, src/Lucene.Net.Facet/Taxonomy/WriterCache/CollisionMap.cs, src/Lucene.Net.Queries/Function/FunctionQuery.cs, src/Lucene.Net.QueryParser/Classic/QueryParser.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Parser/StandardSyntaxParser.cs, src/Lucene.Net.QueryParser/Surround/Parser/QueryParser.cs, src/Lucene.Net.TestFramework/Index/RandomIndexWriter.cs, src/Lucene.Net/Analysis/Tokenizer.cs, src/Lucene.Net/Codecs/Lucene3x/Lucene3xTermVectorsReader.cs, src/Lucene.Net/Index/DocumentsWriterFlushControl.cs, src/Lucene.Net/Index/FrozenBufferedUpdates.cs, src/Lucene.Net/Index/NoMergePolicy.cs, src/Lucene.Net/Index/ParallelCompositeReader.cs, src/Lucene.Net/Search/IndexSearcher.cs, src/Lucene.Net/Search/MatchAllDocsQuery.cs, src/Lucene.Net/Support/Index/TaskMergeScheduler.cs, src/Lucene.Net/Util/AttributeSource.cs, src/Lucene.Net/Util/Automaton/State.cs, src/Lucene.Net/Util/InfoStream.cs, src/Lucene.Net/Util/MergedIterator.cs, src/Lucene.Net/Util/RamUsageEstimator.cs
=> SWEEP: Add a nested comment explaining why this method is empty.

.build/azure-templates/publish-test-results.yml, .build/azure-templates/run-tests-on-os.yml, .github/workflows/Lucene-Net-Dependency-Conflict-Warning.yml
See #699.
- Added a GitHub workflow that posts a message to a PR to run tests in Azure DevOps if they have dependency version changes ([example](https://github.com/NightOwl888/lucenenet/pull/12)).
- Added detection of assembly load failures to Azure DevOps to fail the build ([example](https://dev.azure.com/LuceneNET-Temp/Lucene.NET/_build/results?buildId=2009&view=results)).
=> Feature: build dependency conflict messaging

src/Lucene.Net/Util/MergedIterator.cs
Changed from using inline string conversions when the generic type is string to `J2N.Collections.Generic.Comparer<T>`, which is statically initialized with the optimal comparer that matches Java behaviors.
=> PERFORMANCE: Lucene.Net.Util.MergedEnumerator: Changed to use J2N.Collections.Generic.Comparer<T> to match Java behaviors and for better performance

src/Lucene.Net.Analysis.Common/Analysis/Cjk/CJKBigramFilter.cs
Fixes #657.
Changed the value of ALL to set all flags. The value was 0xff instead of 0xffff, which wasn't valid.
Reviewed all other `[Flags]` enums to ensure they are valid. Closes #658.
=> BREAKING: Lucene.Net.Analysis.Cjk.CJKBigramFilter: Changed the value of CJKScript.ALL

src/Lucene.Net.Analysis.Common/Analysis/Compound/Hyphenation/PatternParser.cs, src/Lucene.Net.Tests/Analysis/TestToken.cs, src/Lucene.Net.Tests/Analysis/TokenAttributes/TestCharTermAttributeImpl.cs, src/Lucene.Net.Tests/Search/TestCustomSearcherSort.cs
Removed call to `ToString()` for `StringBuilder.Append()` methods so strongly typed `StringBuilder` overloads can be used on target frameworks that support it. Fixes #668.
=> Fix: Remove the ToString call in order to use a strongly-typed StringBuilder overload

src/Lucene.Net.Analysis.Phonetic/Language/MatchRatingApproachEncoder.cs, src/Lucene.Net.TestFramework/Support/Util/LuceneTestFrameworkInitializer.cs, src/Lucene.Net/Search/FieldCacheImpl.cs, src/Lucene.Net/Search/Similarities/BasicModelBE.cs
Following #690 I've now added suppression attributes to the methods we decided not to make static.
Adds to #663 
I also had another look at [This issue](https://sonarcloud.io/project/issues?issues=AYPAuN5xhbfJOGLOoaDV&open=AYPAuN5xhbfJOGLOoaDV&id=nikcio_lucenenet) and found that the reason this caused problems is because I forgot to change the `this.` to `BasicModelBE.` in the `Score` method. But I don't know if this is moving too far away from the original code?
The change would be:
```csharp
public override sealed float Score(BasicStats stats, float tfn)
{
double F = stats.TotalTermFreq + 1 + tfn;
// approximation only holds true when F << N, so we use N += F
double N = F + stats.NumberOfDocuments;
return (float)(-SimilarityBase.Log2((N - 1) * Math.E) + BasicModelBE.F(N + F - 1, N + F - …
```
=> chore: Added suppression attributes to CA1822

src/Lucene.Net.Analysis.Common/Analysis/Fa/PersianAnalyzer.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Fa/TestPersianStemFilter.cs
Reverted changes from #571 as was done in apache/lucene#904. Changed `TestPersianStemFilter` to use mocks.
=> Lucene.Net.Analysis.Fa/PersianAnalyzer: Removed PersianStemmer as per apache/lucene#904

src/Lucene.Net/Search/Similarities/BasicModelBE.cs, src/Lucene.Net/Search/Similarities/BasicModelD.cs, src/Lucene.Net/Search/Similarities/BasicModelG.cs, src/Lucene.Net/Search/Similarities/BasicModelIF.cs, src/Lucene.Net/Search/Similarities/BasicModelIn.cs, src/Lucene.Net/Search/Similarities/BasicModelIne.cs, src/Lucene.Net/Search/Similarities/BasicModelP.cs, src/Lucene.Net/Search/Similarities/NormalizationH2.cs
Statically imported `SimilarityBase` where appropriate so the `Log2` method doesn't have to be qualified (like in Lucene). Fixes #694.
=> Lucene.Net.Search.Similarities: Statically imported SimilarityBase, where approrpriate

src/Lucene.Net.Analysis.Kuromoji/Util/CSVUtil.cs, src/Lucene.Net.Tests.Analysis.Kuromoji/Util/TestCSVUtil.cs
Applied [SOLR-9413](https://issues.apache.org/jira/browse/SOLR-9413) patch to fix the `QuoteEscape()` method and add tests. Fixes #660.
=> Lucene.Net.Analysis.Kuromoji.Util.CSVUtil: Fixed QuoteEscape method

src/Lucene.Net.Codecs/Memory/DirectDocValuesProducer.cs, src/Lucene.Net.Suggest/Suggest/Analyzing/FreeTextSuggester.cs, src/Lucene.Net/Support/Arrays.cs
Classes removed: DirectDocValuesProducer.FSTEntry,  FreeTextSuggester.AnalyzingComparer and Arrays.EmptyArrayHolder. Replaced code with appropriate LUCENENET comment.  Related to Issue #669
=> Removed 3 private nested classes that were not in use

Directory.Build.targets
Works around a recent VS2022 bug that causes a StackOverflowException when building the solution in VS2022.
=> Disabled Json Source Generator.

azure-pipelines.yml
The macOS-10.15 environment is deprecated and will be removed from Azure DevOps on December 1st, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5583 
So this PR updates our use of MacOS-10.15 to macOS-latest.
=> Updated Azure DevOps Mac OS used for Net3.1 Testing

.build/dependencies.props, src/Lucene.Net.Analysis.Common/Analysis/CharFilter/HTMLStripCharFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Ga/IrishLowerCaseFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/In/IndicNormalizer.cs, src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/StemmerOverrideFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Nl/DutchAnalyzer.cs, src/Lucene.Net.Analysis.Common/Analysis/Th/ThaiTokenizer.cs, src/Lucene.Net.Analysis.Common/Analysis/Th/ThaiWordFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/CharacterUtils.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/OpenStringBuilder.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/SegmentingTokenizerBase.cs, src/Lucene.Net.Analysis.Common/Lucene.Net.Analysis.Common.csproj, src/Lucene.Net.Analysis.Kuromoji/GraphvizFormatter.cs, src/Lucene.Net.Codecs/SimpleText/SimpleTextUtil.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/In/TestIndicNormalizer.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Miscellaneous/TestStemmerOverrideFilter.cs, src/Lucene.Net.Tests.TestFramework.DependencyInjection/Configuration/TestConfigurationService.cs, src/Lucene.Net.Tests.TestFramework.DependencyInjection/Startup.cs, src/Lucene.Net.Tests/Support/TestApiConsistency.cs, src/Lucene.Net.Tests/Util/TestUnicodeUtil.cs, src/Lucene.Net/Document/CompressionTools.cs, src/Lucene.Net/Lucene.Net.csproj, src/Lucene.Net/Support/Text/CharArrayFormatter.cs, src/Lucene.Net/Util/Constants.cs, src/Lucene.Net/Util/UnicodeUtil.cs
- **PERFORMANCE:** `Lucene.Net.Document.CompressionTools::CompressString()`: Eliminated unnecessary `ToCharArray()` allocation
- **PERFORMANCE:** `Lucene.Net.Codecs.SimpleText.SimpleTextUtil::Write()`: Removed unnecessary `ToCharArray()` allocation
- **PERFORMANCE:** `Lucene.Net.Analysis.CharFilters.HTMLStripCharFilter`: Removed allocation during parse of hexadecimal integers by using `J2N.Numerics.Int32.TryParse()` overloads to specify index, length and radix. Now, the reference to the underlying `char[]` is passed to `OpenStringBuilder.Append()` with index and length so it copies directly from array to array instead of allocating substrings.
- **PERFORMANCE:** Added a `CharArrayFormatter` struct to defer the allocation of constructing a string for `Debugging.Assert()` until after an …
=> PERFORMANCE: Reduced char[] and string allocations (mostly in analysis)

src/Lucene.Net.Suggest/Suggest/Fst/ExternalRefSorter.cs, src/Lucene.Net/Support/IO/FileSupport.cs
- `Lucene.Net.Support.IO.FileSupport::GetFileIOExceptionHResult()`: Avoid `Path.GetTempFileName()` because it is not secure. https://rules.sonarsource.com/csharp/RSPEC-5445
- `Lucene.Net.Search.Suggest.Fst.ExternalRefSorter`: Changed temp path generation to use `FileSupport.CreateTempFile()` with named prefix and extension because it more closely matches Lucene and makes the files more easily identifiable.
=> Path.GetFileName() Updates

src/Lucene.Net.TestFramework/Index/RandomIndexWriter.cs, src/Lucene.Net/Index/IndexWriter.cs
See #265.
Fixed `Dispose()` overloads so there is no method signature conflict between the public `Dispose(waitForMerges)` method and the protected `Dispose(disposing)` method which is meant for end users to override. This was done by adding a `protected virtual void Dispose(bool disposing, bool waitForMerges)` overload and removing `virtual` from the public `Dispose(bool waitForMerges)` overload.
This may break some existing code that either
1. Subclasses `IndexWriter` and overrides the `public virtual void Dispose(bool disposing)` method. Instead, the subclass should override `protected virtual void Dispose(bool disposing, bool waitForMerges)`.
2. Subclasses `IndexWriter` and implements a finalizer, in which case the call should now call `Dispose(disposing: false, waitForMerges: true)`. …
=> BREAKING: Lucene.Net.Index.IndexWriter: Fixed Dispose(waitForMerges) vs Dispose(disposing)

src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs, src/Lucene.Net.Tests/Index/TestDirectoryReader.cs, src/Lucene.Net.Tests/Index/TestIndexReaderClose.cs, src/Lucene.Net.Tests/Index/TestParallelCompositeReader.cs, src/Lucene.Net.Tests/Support/TestIDisposable.cs, src/Lucene.Net/Index/IndexReader.cs, src/Lucene.Net/Search/FieldCacheImpl.cs, src/Lucene.Net/Support/ObsoleteAPI/IndexReader.cs
- De-nested `IReaderClosedListener` from `IndexReader`.
- Renamed `IReaderClosedListener` > `IReaderDisposedListener`.
- Renamed `IReaderClosedListener.OnClose()` > `IReaderDisposedListener.OnDispose()`
- Renamed `AddReaderClosedListener()` > `AddReaderDisposedListener()`.
- Renamed `RemoveReaderClosedListener()` > `RemoveReaderDisposedListener()`.
=> BREAKING: Lucene.Net.Index.IndexReader: Refactored `IReaderClosedListener`

src/Lucene.Net/Analysis/TokenStreamToAutomaton.cs, src/Lucene.Net/Codecs/MappingMultiDocsAndPositionsEnum.cs, src/Lucene.Net/Codecs/MappingMultiDocsEnum.cs, src/Lucene.Net/Codecs/TermsConsumer.cs, src/Lucene.Net/Index/CheckIndex.cs, src/Lucene.Net/Store/BaseDirectory.cs, src/Lucene.Net/Store/BufferedChecksumIndexInput.cs, src/Lucene.Net/Store/ByteBufferIndexInput.cs, src/Lucene.Net/Store/RAMFile.cs, src/Lucene.Net/Util/CollectionUtil.cs, src/Lucene.Net/Util/IOUtils.cs
Closes #754.
Just removed the `LangVersion` update to 10 because VS 2019 doesn't support it.
=> Improve Code Quality (originally submitted by @iamcarbon in #754)

src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/PrefixAndSuffixAwareTokenFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/PrefixAwareTokenFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/BufferedCharFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/CharArrayMap.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/NearRealtimeReaderTask.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/TaskSequence.cs, src/Lucene.Net.Codecs/Memory/MemoryDocValuesConsumer.cs, src/Lucene.Net.Facet/Taxonomy/WriterCache/CollisionMap.cs, src/Lucene.Net.Spatial/Prefix/AbstractVisitingPrefixTreeFilter.cs, src/Lucene.Net/Analysis/TokenFilter.cs, src/Lucene.Net/Analysis/Tokenizer.cs, src/Lucene.Net/Codecs/PerField/PerFieldDocValuesFormat.cs, src/Lucene.Net/Codecs/PerField/PerFieldPostingsFormat.cs, src/Lucene.Net/Index/IndexWriter.cs, src/Lucene.Net/Index/PrefixCodedTerms.cs, src/Lucene.Net/Store/FSDirectory.cs, src/Lucene.Net/Support/IO/SafeTextWriterWrapper.cs, src/Lucene.Net/Support/Index/TaskMergeScheduler.cs, src/Lucene.Net/Util/PrintStreamInfoStream.cs, src/dotnet/tools/lucene-cli/CommandLine/CommandLineApplication.cs, src/dotnet/tools/lucene-cli/SourceCode/SourceCodeSectionReader.cs
Related to #265 
I've run through most of the issues reported in Sonarcloud related to the use of the IDisposable pattern (https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS3881&id=apache_lucenenet)
This PR is meant to further expose which implementations of the pattern require more investigation while also removing the easiest areas where the pattern just needs a simple alignment. This means that if any of the following changes exposes an issue requiring much more effort this is best to be moved to comment on the existing issue and have a solution opened in another PR. I realize that a correct implementation of this pattern can be advanced and is related to at least a handful of issues opened in this repository which is why I want to take the approach stated 😄 .
To …
=> fix: Aligned disposable patterns

Directory.Build.targets, src/Lucene.Net.Analysis.Common/Analysis/Util/BufferedCharFilter.cs, src/Lucene.Net/Support/IO/SafeTextWriterWrapper.cs
Well, sort of. An implementation of `Peek()` was added. Several of the method overloads were changed from throwing `NotImplementedException` to `NotSupportedException`.
Fixed locks in `Read()` and `Read(char[] buffer, int offset, int length)` to use `UninterruptableMonitor`.
=> Finished BufferedCharFilter implementation

TestTargetFramework.props
Disabled EoL warnings in test projects so we don't get false flags for testing with net5.0. We use net5.0 to test the netstandard2.1 target framework and will continue doing so for the foreseeable future.
=> TestTargetFramework.props: Disabled EoL warnings in Test Projects

src/Lucene.Net.Tests.Analysis.ICU/Analysis/Icu/Segmentation/TestICUTokenizerFactory.cs, src/Lucene.Net.Tests.Analysis.ICU/Collation/TestICUCollationKeyFilterFactory.cs, src/Lucene.Net.Tests.Analysis.Kuromoji/TestJapaneseIterationMarkCharFilterFactory.cs, src/Lucene.Net.Tests.Analysis.Kuromoji/TestJapanesePartOfSpeechStopFilterFactory.cs, src/Lucene.Net.Tests.Analysis.Kuromoji/TestJapaneseTokenizerFactory.cs, src/Lucene.Net.Tests.Analysis.Phonetic/Language/Bm/PhoneticEngineRegressionTest.cs, src/Lucene.Net.Tests.Analysis.Phonetic/TestBeiderMorseFilterFactory.cs, src/Lucene.Net.Tests.Analysis.Phonetic/TestPhoneticFilterFactory.cs, src/Lucene.Net.Tests.Grouping/TestGrouping.cs, src/Lucene.Net.Tests.Highlighter/Highlight/HighlighterTest.cs, src/Lucene.Net.Tests.Highlighter/VectorHighlight/FastVectorHighlighterTest.cs, src/Lucene.Net.Tests.Misc/Document/TestLazyDocument.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Precedence/TestPrecedenceQueryParser.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestMultiFieldQPHelper.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestNumericQueryParser.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestQPHelper.cs, src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestStandardQP.cs, src/Lucene.Net.Tests.Spatial/Prefix/SpatialOpRecursivePrefixTreeTest.cs, src/Lucene.Net.Tests.Suggest/Suggest/DocumentDictionaryTest.cs, src/Lucene.Net.Tests.Suggest/Suggest/DocumentValueSourceDictionaryTest.cs, src/Lucene.Net.Tests.Suggest/Suggest/Fst/WFSTCompletionTest.cs, src/Lucene.Net.Tests.Suggest/Suggest/TestInputIterator.cs, src/Lucene.Net/Support/DictionaryExtensions.cs
`Lucene.Net.Support.DictionaryExtensions`: Reduced dependency on the `Put()` method and added documentation to indicate that it doesn't work with non-nullable value types. Also documented the `PutAll()` method and added guard clause.
=> Lucene.Net.Support.DictionaryExtensions: Reduced dependency on the Put() method + added docs

src/Lucene.Net.Analysis.Common/Analysis/Core/StopAnalyzer.cs, src/Lucene.Net.Analysis.Common/Analysis/Fr/FrenchAnalyzer.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/BufferedCharFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/CharArrayMap.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/CharArraySet.cs, src/Lucene.Net.Expressions/JS/JavascriptCompiler.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestCharArrayMap.cs, src/Lucene.Net/Codecs/PostingsFormat.cs, src/Lucene.Net/Index/Fields.cs, src/Lucene.Net/Index/IndexWriter.cs, src/Lucene.Net/Index/MultiTermsEnum.cs, src/Lucene.Net/Index/ReaderSlice.cs, src/Lucene.Net/Index/Terms.cs, src/Lucene.Net/Support/Arrays.cs, src/Lucene.Net/Util/Bits.cs, src/Lucene.Net/Util/BytesRef.cs, src/Lucene.Net/Util/CharsRef.cs, src/Lucene.Net/Util/IntsRef.cs, src/Lucene.Net/Util/LongsRef.cs, src/dotnet/tools/lucene-cli/CommandLine/CommandLineApplication.cs
This contains breaking changes:
- `Lucene.Net.Analysis.Util.CharArrayDictionary<TValue>`: Removed the `CopyTo()` overloads from the public API. They are still accessible through `ICollection.CopyTo()`, but it is better to use the `Enumerator` to gain direct access to the `CurrentKey` and `CurrentValue` properties. `CopyTo()` was not something that existed in Lucene, but since `CharArrayMap` was created by subclassing `AbstractMap` (getting all of the "normal" functionality for free), we added it to make the collection "normal". However, `Dictionary<TKey, TValue>` doesn't expose its `CopyTo()` method publicly, so we are following suit.
=> SWEEP: Fixed SonarCloud issues that were found in "new code"

src/Lucene.Net/Store/InputStreamDataInput.cs, src/Lucene.Net/Store/OutputStreamDataOutput.cs
From talks in #763
Fixed InputStreamDataInput and OutputStreamDataOutput so that they don't wrap their input streams to BinaryReader/Writers to align the code closer to the Java source which just uses the input.
I also aligned the dispose method of the two so they behave the same.
This is a PR done a bit in blind as I can't build the full lucene source at the moment.
=> Align InputStreamDataInput and OutputStreamDataOutput closer to the Java Source

src/Lucene.Net.Analysis.Common/Analysis/Shingle/ShingleFilter.cs, src/Lucene.Net/Codecs/Lucene45/Lucene45DocValuesProducer.cs, src/Lucene.Net/Search/MinShouldMatchSumScorer.cs
This PR fixes some of the issues with virtual calls being made from constructors. The issues were reported by SonarCloud scans: https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS1699&id=apache_lucenenet and referenced in this issue: https://github.com/apache/lucenenet/issues/670
Particularly here we are addressing that have this issue and are either private or internal to Lucene and can be changed without impacting public API surface.
=> Remove virtual on a method that's being called from constructor

src/Lucene.Net.Analysis.Common/Analysis/Compound/Hyphenation/HyphenationTree.cs, src/Lucene.Net.Analysis.Common/Analysis/Compound/Hyphenation/TernaryTree.cs
I have changed my mind on TernaryTree and believe that making Init not virtual is a better fix than introducing locking/lazy initialization.
TernaryTree is an internal class that's being subclassed by public HyphenationTree class. HyphenationTree does not call Init anywhere. This:
```c#
internal class TernaryTree
{
public TernaryTree() { Init(); }
protected virtual void Init() { ... }
}
public class HyphenationTree
{
public HyphenationTree () 
}
```
Since HyphenationTree is public, by removing the …
=> BREAKING: Remove virtual on a method that's being called from constructor in TernaryTree

src/Lucene.Net.Analysis.Common/Analysis/Util/AbstractAnalysisFactory.cs
In this case, AbstractAnalysisFactory calls "Get" from the constructor. Get is virtual, but it does not feel like the intent here is to make that method extendable. It's a WIDELY extended class inside Lucene via TokenFilterFactory and all the classes that inherit from it, and none of them override Get implementations.
=> BREAKING: Make AbstractAnalysisFactory.Get non-virtual to avoid issues in constructors

src/Lucene.Net.Analysis.Common/Tartarus/Snowball/SnowballProgram.cs
This one focuses on SnowballProgram. The pattern here is to create a private method that the constructor can use and virtual methods can use as well.
=> BREAKING: remove virtual method call from constructor

src/Lucene.Net.Analysis.Common/Analysis/Util/OpenStringBuilder.cs
This one focuses on OpenStringBuilder. The pattern here is to create a private method that the constructor can use and virtual methods can use as well.
=> BREAKING: remove virtual method call from constructor in OpenStringBuilder

src/Lucene.Net.Suggest/Spell/SpellChecker.cs
This one focuses on SpellChecker. We are simply removing the virtual designation. It seems like Lucene team has been planning this as well based on TODO: comment above the method but has not pulled the trigger. We are going to go ahead and do that.
=> BREAKING: remove virtual designation as it's called from constructor

src/Lucene.Net/Util/SentinelIntSet.cs
This one focuses on SentinelInt32Set (aka SentinelIntSet) where we add a private method to call from the constructor and a virtual method that used to be called from the constructor.
=> BREAKING: remove virtual call from the constructor for SentinelInt32Set

src/Lucene.Net/Search/DisjunctionMaxQuery.cs
This one focuses on DisjunctionMaxQuery where we add a private method to call from the constructor and a virtual method that used to be called from the constructor.
=> BREAKING: remove virtual call from the constructor for DisjunctionMaxQuery

src/Lucene.Net.Spatial/Prefix/Tree/Cell.cs, src/Lucene.Net/Search/DisjunctionMaxQuery.cs
This one focuses on Cell where we add a private method to call from the constructor and a virtual method that used to be called from the constructor, as well as B_fixLeaf() method that another constructor calls.
=> BREAKING: Fix/virtual calls from constructors for cell

src/Lucene.Net.TestFramework/Analysis/LookaheadTokenFilter.cs, src/Lucene.Net.TestFramework/Analysis/MockGraphTokenFilter.cs, src/Lucene.Net.TestFramework/Analysis/MockRandomLookaheadTokenFilter.cs, src/Lucene.Net.Tests.TestFramework/Analysis/TestLookaheadTokenFilter.cs, src/Lucene.Net.Tests.TestFramework/Analysis/TrivialLookaheadFilter.cs, src/Lucene.Net.Tests/Analysis/TestLookaheadTokenFilter.cs, src/Lucene.Net.Tests/Analysis/TrivialLookaheadFilter.cs, src/Lucene.Net.Tests/Util/TestRollingBuffer.cs, src/Lucene.Net/Analysis/TokenStreamToAutomaton.cs, src/Lucene.Net/Util/RollingBuffer.cs
This one focuses on RollingBuffer and its subclasses. Instead of providing a virtual NewInstance to override, we accept a factory method in the constructor and use it whenever new instance is needed.
=> BREAKING: remove virtual call from the constructor for RollingBuffer and related classes

src/Lucene.Net/Search/Sort.cs
This one focuses on Sort. Creating a private method that constructor can call and calling the private method from the virtual method.
=> BREAKING: remove virtual call from the constructor for Sort

src/Lucene.Net.QueryParser/Flexible/Standard/Nodes/NumericRangeQueryNode.cs
This one focuses on NumericRangeQueryNode. Creating a private method that the constructor can call.
=> BREAKING: remove virtual call from the constructor for NumericRangeQueryNode

src/Lucene.Net.Highlighter/VectorHighlight/FieldPhraseList.cs
This one focuses on FieldPhraseList. Creating a private method that constructor can call, and calling the private method from the virtual method.
=> BREAKING: remove virtual call from the constructor for FieldPhraseList

src/Lucene.Net/Store/ByteArrayDataOutput.cs
This one focuses on ByteArrayDataOuput, creating a private method that constructor as well as public virtual methods can call.
=> BREAKING: remove virtual call from the constructor for ByteArrayDataOutput

src/Lucene.Net/Util/Packed/AbstractBlockPackedWriter.cs
This one focuses on AbstractBlockPackedWriter, creating a private method that the constructor and public virtual methods can call.
=> BREAKING: Fix/virtual calls from constructors for AbstractBlockPackedWriter

src/Lucene.Net/Search/IndexSearcher.cs
This one focuses on IndexSearcher. Creating a private method that constructor can call and calling the private method from the virtual method.
=> BREAKING: remove virtual call from the constructor for IndexSearcher

src/Lucene.Net.Join/TermsIncludingScoreQuery.cs
This one includes all the cases where we will ignore the warning and accept the code as is due to the fix being too invasive and not justifiable (e.g. classes are internal to Lucene.NET)
=> Supress sonar cloud warnings about constructor making virtual call

src/Lucene.Net/Index/DocTermOrds.cs
We are ignoring DocTermOrds errors as the Lucene team intended for the subclasses to use the protected constructor that does not call the virtual method, and they even specify that subclasses should call the virtual method themselves.
=> Ignore sonar cloud errors for DocTermOrds

src/Lucene.Net.Suggest/Suggest/Analyzing/AnalyzingInfixSuggester.cs
This one focuses on AnalyzingInfixSuggester. After going back to Lucene repository and looking at the history of the file, I found this:
https://issues.apache.org/jira/browse/LUCENE-7670
and https://github.com/apache/lucene/commit/c1fe88b7c6fa861d5101f9702a7832d29b8032ee
The opening of a writer appears to be a bug that was fixed, and the line was removed. Removing the line eliminates the sonar cloud issue as well.
=> Remove unnecessary index writer getting opened

src/Lucene.Net.Spatial/Prefix/WithinPrefixTreeFilter.cs
This one focuses on WithinPrefixTreeFilter. The fix was to add a protected constructor that does not call virtual methods, and the subclasses can use it to initialize and then call any methods they need inside their constructors.
=> Workaround for virtual call issue for WithinPrefixTreeFilter

src/Lucene.Net.QueryParser/Xml/QueryTemplateManager.cs
This one focuses on queryTemplateManager where we allow subclasses to use default constructor and expose m_defaultCompiledTemplates as protected for them to initialize it when needed.
=> Adjust QueryTemplateManager to allow subclasses avoid calling virtual methods from the constructors

src/Lucene.Net.Benchmark/ByTask/PerfRunData.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/ReadTask.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/WriteLineDocTask.cs
This one focuses on the findings in the Benchmark project. Adding attributes to ignore the warnings as opposed to introducing a workaround or a breaking change.
=> add ignore attributes

src/Lucene.Net.QueryParser/Surround/Query/SimpleTerm.cs, src/Lucene.Net.QueryParser/Surround/Query/SrndTruncQuery.cs
This one focuses on SrndTruncQuery. We are adding a protected constructor that subclasses can use.
=> BREAKING: SrndTruncQuery fix for virtual call being made from constructor

src/Lucene.Net.QueryParser/Classic/QueryParserTokenManager.cs
This one focuses on QueryParserTokenManager. We are suppressing the warnings and including docs with a note for subclasses to use a different constructor if needed.
=> Add suppress attributes and comment on using constructors for QueryParserTokenManager

src/Lucene.Net.Benchmark/Support/Sax/Helpers/AttributesImpl.cs
This one focuses on AttributesImpl. We are suppressing the warnings and including docs with a note for subclasses to use a different constructor if needed.
=> add suppress and comment on using constructors

src/Lucene.Net.Facet/Taxonomy/FloatTaxonomyFacets.cs, src/Lucene.Net.Facet/Taxonomy/IntTaxonomyFacets.cs, src/Lucene.Net.Facet/TopOrdAndFloatQueue.cs, src/Lucene.Net.Facet/TopOrdAndIntQueue.cs, src/Lucene.Net.Tests.Facet/Support/TestApiConsistency.cs, src/Lucene.Net.Tests/Support/TestApiConsistency.cs, src/Lucene.Net.Tests/Util/TestPriorityQueue.cs, src/Lucene.Net/Search/HitQueue.cs, src/Lucene.Net/Search/TopDocs.cs, src/Lucene.Net/Util/Fst/FST.cs, src/Lucene.Net/Util/PriorityQueue.cs
This adds a new ref struct to the project, `Lucene.Net.Util.ValuePriorityQueue<T>`. This struct contains the most of the same API and business logic as `PriorityQueue<T>`, but allows the memory used to be allocated elsewhere as `Span<T>` and passed in.
The amount to allocate can be calculated by calling `PriorityQueue.GetArrayHeapSize(maxSize)`, where `maxSize` is the external size of the `PriorityQueue` (representing the same value that is passed into the constructor of the current `PriorityQueue<T>`). The actual allocation amount is 1 greater than the priority queue size because it is 1-based rather than 0-based.
We get around the issue with structs not being inheritable by introducing a new `PriorityComparer<T>` abstract class with a single `bool LessThan(T a, T b)` method. This …
=> BREAKING: Introducing ValuePriorityQueue<T>

src/Lucene.Net/Search/IndexSearcher.cs
This one focuses on IndexSearcher. Since we discovered a separate constructor approach as an elegant way to address this issue, let's use it for IndexSearcher.
=> IndexSearcher fix for virtual calls from constructor

src/Lucene.Net.TestFramework/Index/RandomCodec.cs, src/Lucene.Net.Tests.Facet/SlowRAMDirectory.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyCombined.cs
This fixes an issue with a slow test in TestTaxonomyCombined. The original issue description is here:
The issue has been brought up in https://github.com/apache/lucenenet/issues/836, under `TestTaxonomyCombined.TestTaxonomyRefreshRaces()` section
After debugging the issue, I discovered that the cause of the slow down are System.Thread.Sleep(1) calls being made thousands of times with intent of sleep taking 1ms. On windows however, that could take much more than 1ms, 15ms normally, confirmed locally and found a discussion about it here:
https://stackoverflow.com/questions/19066900/thread-sleep1-takes-longer-than-1ms
I setup Java version locally to compare the running times and after the fix, Java version and .NET version is running in basically identical amount of time. Locally I get it to …
=> Fix slow test: use different sleep method if resolution is low

src/Lucene.Net.Suggest/Suggest/Analyzing/AnalyzingInfixSuggester.cs
Reverts apache/lucenenet#825
As explained in #839, this is causing a `AnalyzingInfixSuggesterTest.TestRandomNRT()` test failure because we apparently don't have all of the patches required to make it pass.
=> Revert "Remove unnecessary index writer getting opened"

src/Lucene.Net.Tests/Index/TestIndexWriterOnJRECrash.cs
Removed using block to ensure that our original CheckIndex error bubbles up instead of any issue disposing (or double-disposing) the directory.
This test occasionally failed because of #841 also, and this will fix that issue.
=> BUG: TestIndexWriterOnJRECrash: Removed using block

.gitignore, src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyIndexReaderFactory.cs, src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyIndexWriterFactory.cs, src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyReader.cs, src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyWriter.cs, src/Lucene.Net.Replicator/IndexAndTaxonomyRevision.cs, src/Lucene.Net.Replicator/Support/SnapshotDirectoryTaxonomyIndexWriterFactory.cs, src/Lucene.Net.Tests.Facet/Taxonomy/Directory/TestDirectoryTaxonomyReader.cs, src/Lucene.Net.Tests.Replicator/IndexAndTaxonomyReplicationClientTest.cs, src/Lucene.Net.Tests.Replicator/IndexAndTaxonomyRevisionTest.cs
Here we are changing DirectoryTaxonomyWriter to use DirectoryTaxonomyIndexWriterFactory class that will create config and writer. The factor class can be subclassed and a different implementation provided and used by either DirectoryTaxonomyWriter subclasses or just passed to the class itself.
We are also adjusting DirectoryTaxonomyReader to use DirectoryTaxonomyIndexReaderFactory class that will open index reader while also providing a way for users to customize the reader that's opened in any …
=> BREAKING: Use factory classes for DirectoryTaxonomyWriter and DirectoryTaxonomyReader

src/Lucene.Net.Suggest/Suggest/Analyzing/AnalyzingInfixSuggester.cs, src/Lucene.Net.Suggest/Suggest/Analyzing/AnalyzingInfixSuggesterIndexWriterConfigFactory.cs
Continuation of fixes with virtual calls being made from constructors. The issue originally reported by SonarCloud scans: https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS1699&id=apache_lucenenet and referenced in this issue: #670 
This PR takes care of AnalyzingInfixSuggester and replaces the creation of index writer config in a virtual method with a factory class.
=> BREAKING: Analyzing infix suggester virtual method fix

src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyWriter.cs
This takes care of what should be the last issue in this area. We already modified DirectoryTaxonomyWriter to accept a factory for index writer and now the last remaining virtual call it makes is to AddCategory in case an empty/new taxonomy directory is being created.
There does not appear to be an easy way to translate this into a factory that makes a logical sense.
I considered adding a private AddCategory method that constructor and AddCategory could call, but it seemed like it would prevent …
=> Suppress virtual method call from the constructor warning for AddCategory call

src/Lucene.Net.Tests/Document/TestDateTools.cs, src/Lucene.Net/Document/DateTools.cs
=> BUG: Lucene.Net.Documents.DateTools: Convert DateTimeKind.Unspecified dates to UTC, otherwise they can produce ArgumentOutOfRangeException

src/Lucene.Net.TestFramework/Store/BaseDirectoryTestCase.cs, src/Lucene.Net.TestFramework/Store/BaseDirectoryWrapper.cs, src/Lucene.Net.TestFramework/Store/MockDirectoryWrapper.cs, src/Lucene.Net.Tests.TestFramework/Support/TestApiConsistency.cs, src/Lucene.Net.Tests/Store/TestDirectory.cs, src/Lucene.Net.Tests/Store/TestNRTCachingDirectory.cs, src/Lucene.Net.Tests/Support/TestApiConsistency.cs, src/Lucene.Net/Codecs/MultiLevelSkipListReader.cs, src/Lucene.Net/Store/BaseDirectory.cs, src/Lucene.Net/Store/BufferedIndexOutput.cs, src/Lucene.Net/Store/CompoundFileDirectory.cs, src/Lucene.Net/Store/Directory.cs, src/Lucene.Net/Store/FSDirectory.cs, src/Lucene.Net/Store/InputStreamDataInput.cs, src/Lucene.Net/Store/MMapDirectory.cs, src/Lucene.Net/Store/NIOFSDirectory.cs, src/Lucene.Net/Store/NRTCachingDirectory.cs, src/Lucene.Net/Store/OutputStreamDataOutput.cs, src/Lucene.Net/Store/RAMDirectory.cs, src/Lucene.Net/Store/RateLimitedIndexOutput.cs, src/Lucene.Net/Store/SimpleFSDirectory.cs
Fixes #841. Part of #265.
This adds an atomic `CompareAndSetIsOpen(bool expect, bool update)` method to `BaseDirectory` and `BaseDirectoryWrapper` that can be used to ensure only a single call to `Dispose(bool)` will succeed. This is the same method signature as `J2N.Threading.Atomic.AtomicBoolean` and can be used the same way (without the extra heap allocation).
```c#
protected override void Dispose(bool disposing)
{
if (!CompareAndSetIsOpen(expect: true, update: false)) return;
// Dispose unmanaged resources
if (disposing)
{
// Dispose managed resources
}
}
```
This fixes `NRTCachingDirectory` (as well as all other directories) so they don't throw exceptions when `Dispose()` is called multiple times.
This of course means that `EnsureOpen()` will be active immediately when `Dispose()` is …
=> SWEEP: Lucene.Net.Store: Fixed several Dispose() methods so they are safe to be called multiple times

websites/site/quick-start/index.md
Remove the repetition of `to be able` from the quick-start page
=> Remove a repetion from the quick-start index.md page

.build/dependencies.props, .rat-excludes, src/Lucene.Net.Facet/Taxonomy/CachedOrdinalsReader.cs, src/Lucene.Net.Tests/Support/Util/Events/MockDelegateReference.cs, src/Lucene.Net.Tests/Support/Util/Events/TestBackgroundEventSubscription.cs, src/Lucene.Net.Tests/Support/Util/Events/TestDelegateReference.cs, src/Lucene.Net.Tests/Support/Util/Events/TestDispatcherEventSubscription.cs, src/Lucene.Net.Tests/Support/Util/Events/TestEventAggregator.cs, src/Lucene.Net.Tests/Support/Util/Events/TestEventBase.cs, src/Lucene.Net.Tests/Support/Util/Events/TestEventSubscription.cs, src/Lucene.Net.Tests/Support/Util/Events/TestPubSubEvent.cs, src/Lucene.Net/Index/IndexReader.cs, src/Lucene.Net/Lucene.Net.csproj, src/Lucene.Net/Search/CachingWrapperFilter.cs, src/Lucene.Net/Search/FieldCacheImpl.cs, src/Lucene.Net/Support/Util/Events/BackgroundEventSubscription.cs, src/Lucene.Net/Support/Util/Events/DelegateReference.cs, src/Lucene.Net/Support/Util/Events/DispatcherEventSubscription.cs, src/Lucene.Net/Support/Util/Events/EventAggregator.cs, src/Lucene.Net/Support/Util/Events/EventBase.cs, src/Lucene.Net/Support/Util/Events/EventSubscription.cs, src/Lucene.Net/Support/Util/Events/IDelegateReference.cs, src/Lucene.Net/Support/Util/Events/IEventAggregator.cs, src/Lucene.Net/Support/Util/Events/IEventSubscription.cs, src/Lucene.Net/Support/Util/Events/PubSubEvent.cs, src/Lucene.Net/Support/Util/Events/Resources.cs, src/Lucene.Net/Support/Util/Events/SubscriptionToken.cs, src/Lucene.Net/Support/Util/Events/ThreadOption.cs, src/Lucene.Net/Support/Util/Events/WeakDelegatesManager.cs, src/Lucene.Net/Support/Util/WeakEvents.cs
Fixes #872.
Imported `Prism.Events` namespace as `Lucene.Net.Util.Events` and dropped dependency on Prism.Core, which is now a commercial product. This uses the commit at https://github.com/PrismLibrary/Prism/releases/tag/DNF, since it is the last version released under the MIT license.
=> Removed dependency on Prism.Core (Fixes #872)

src/Lucene.Net.Tests/Util/TestPriorityQueue.cs, src/Lucene.Net/Util/PriorityQueue.cs
Binary serialization is obsolete in .NET 6+, and serialization didn't technically support extension because it was missing the virtual GetObjectData and OnDeserialization methods and deserialization constructor.
This fixes the SonarCloud security hotspot [Deserializing objects without performing data validation is security-sensitive](https://sonarcloud.io/organizations/apache/rules?open=csharpsquid%3AS5766&rule_key=csharpsquid%3AS5766).
=> Lucene.Net.Util.PriorityQueue: Removed [Serializable] attribute. 

src/Lucene.Net/Util/OfflineSorter.cs
Suppressed SonarCloud security hotspot S5443 [Using publicly writable directories is security-sensitive](https://sonarcloud.io/organizations/apache/rules?open=csharpsquid%3AS5443&rule_key=csharpsquid%3AS5443) because we are not writing predictable temp file names and allow using a different directory.
=> Lucene.Net.Util.OfflineSorter::DEFAULT_TEMP_DIR: Added suppression for SonarCloud S5443

.github/workflows/sonar.yml
Reverted to using dotnet-sonarscanner 5.8.0 to see whether we still get a non zero exit code.
5.8.0 is the version that was active when #709 was first submitted and was most likely the version in the cache until #867 was merged (working theory).
=> .github/workflows/sonar.yml: Attempting to fix exit code

src/Lucene.Net.Tests/Support/Util/Events/TestPubSubEvent.cs
This test has failed since #875 was submitted. Unfortunately, we had no way of knowing that this test was flakey until we inherited it from Prism.
Since we have had no complaints about the weak events in Prism, this is probably an edge case that may or may not need addressing later.
=> Lucene.Net.Util.Events.TestPubSubEvent::CanAddSubscriptionWhileEventIsFiring(): Added Ignore attribute

src/Lucene.Net/Store/LockStressTest.cs
Suppressed SonarCloud S2245 because the `Random` class is only used to generate a timeout
=> Lucene.Net.Store.LockStessTest: Suppressed SonarCloud S2245

.build/dependencies.props
This is only used in tests. We were getting some test failures (most likely because of incompatibilities with newer operating systems) that this upgrade resolves.
=> .build/dependencies.props: Upgraded TimeZoneConverter to 6.1.0. 

src/Lucene.Net.Tests/Index/TestIndexWriterOnJRECrash.cs
`Lucene.Net.Index.TestIndexWriterOnJRECrash::TestNRTThreads_Mem()`: Added [AwaitsFix] attribute because this test fails intermittently (see #894).
=> Lucene.Net.Index.TestIndexWriterOnJRECrash::TestNRTThreads_Mem(): Added [AwaitsFix] attribute because this test fails intermittently

src/Lucene.Net/Analysis/TokenAttributes/CharTermAttributeImpl.cs
PERFORMANCE: Lucene.Net.Analysis.TokenAttributes.CharTermAttribute: Optimized char copying on Append() and Subsequence()
This removes some allocations from the `StringBuilder` overloads of `Append()` and switches from using a for loop to `Arrays.Copy()` for `Subsequence()`.
=> PERFORMANCE: Lucene.Net.Analysis.TokenAttributes.CharTermAttribute: Optimized char copying on Append() and Subsequence()

src/Lucene.Net.Facet/Taxonomy/WriterCache/CategoryPathUtils.cs, src/Lucene.Net.Facet/Taxonomy/WriterCache/CharBlockArray.cs, src/Lucene.Net.Facet/Taxonomy/WriterCache/CompactLabelToOrdinal.cs
PERFORMANCE: Lucene.Net.Facet.Taxonomy.WriterCache.CharBlockArray: Compare equality and calculate hash code without allocating
The equality and hash code generation in Lucene relied on `Subsequence()` to generate the hash code and check for equality. Subsequence always allocates. The prior implementation of equality was actually copying the characters to a `StringBuilder` (which allocates), then calling `StringBuilder.ToString()` (which allocates), then comparing using `String.Equals()`, which only accepts a string.
This has been modified to pass `startIndex` and `length` to the `CharBlockArray` when calculating hash code and comparing for binary string equality. These checks are done in `CharBlockArray` itself on the original data structure …
=> PERFORMANCE: Lucene.Net.Facet.Taxonomy.WriterCache.CharBlockArray: Compare equality and calculate hash code without allocating

src/Lucene.Net.Facet/Taxonomy/WriterCache/CharBlockArray.cs, src/Lucene.Net.Tests.Facet/Taxonomy/WriterCache/TestCharBlockArray.cs
Lucene.Net.Facet.Taxonomy.WriterCache.CharBlockArray: Implemented `IAppendable` to align with Lucene.
`Lucene.Net.Facet.Taxonomy.WriterCache.CharBlockArray`: Implemented `IAppendable` to align with Lucene. Added tests to check the implementations, since we have many additional overloads in .NET. Added guard clauses for `Append()` overloads using the same semantics as the .NET StringBuilder class.
=> Lucene.Net.Facet.Taxonomy.WriterCache.CharBlockArray: Implemented IAppendable to align with Lucene.

TestTargetFramework.props
`TestTargetFramework.props`: Added documentation about how the TargetFramework specified in tests maps to a TargetFramework that is under test.
`TestTargetFramework.props`: Added documentation about how the TargetFramework specified in tests maps to a TargetFramework that is under test. 
We have had many suggestions to remove `net5.0` from our test targets because it is no longer supported. We keep `net5.0` around because everything higher will load the `net6.0` target by default, leaving a gap in our testing - `netstandard2.1`. We already force `net461` to load `netstandard2.0` in order to test it, but that seems like less of a valid test than using an obsolete framework.
=> TestTargetFramework.props: Added documentation about how the TargetFramework specified in tests maps to a TargetFramework that is under test

.github/workflows/sonar.yml
.github/workflows/sonar.yml: Upgraded JDK to 21 (latest LTS) because SonarCloud no longer supports JDK 11.
Fixes #883
.github/workflows/sonar.yml: Upgraded JDK to 21 (latest LTS) because SonarCloud no longer supports JDK 11.
Attempting JDK 21, although only JDK 17 is required for now, hopefully so we can future-proof a bit.
=> CI: .github/workflows/sonar.yml: Upgraded JDK to 21 (latest LTS) because SonarCloud no longer supports JDK 11. Fixes #883.

.build/dependencies.props
SECURITY: Bumped System.Security.Cryptography to 6.0.1 and SharpZipLib to 1.4.2
https://github.com/advisories/GHSA-2m65-m22p-9wjw
https://github.com/advisories/GHSA-m22m-h4rf-pwq3
https://github.com/advisories/GHSA-mm6g-mmq6-53ff
This has been tested in Azure DevOps to ensure .NET Framework can resolve dependency version conflicts with these changes.
I didn't see these in the [SonarCloud control panel](https://sonarcloud.io/project/overview?id=apache_lucenenet), but they were appearing in the logs.
=> Updated vulnerable dependencies System.Security.Cryptography and SharpZipLib

.build/TestReferences.Common.targets, .build/azure-templates/publish-nuget-packages.yml, .build/azure-templates/publish-test-results-for-test-projects.yml, .build/dependencies.props, .github/workflows/Lucene-Net-Tests-Analysis-OpenNLP.yml, Directory.Build.targets, src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/TypeAsSynonymFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/TypeAsSynonymFilterFactory.cs, src/Lucene.Net.Analysis.OpenNLP/Lucene.Net.Analysis.OpenNLP.csproj, src/Lucene.Net.Analysis.OpenNLP/overview.md, src/Lucene.Net.Facet/Lucene.Net.Facet.csproj, src/Lucene.Net.TestFramework/Analysis/CannedTokenStream.cs, src/Lucene.Net.TestFramework/Lucene.Net.TestFramework.csproj, src/Lucene.Net.Tests.AllProjects/Lucene.Net.Tests.AllProjects.csproj, src/Lucene.Net.Tests.Analysis.Common/Analysis/Miscellaneous/TestTypeAsSynonymFilterFactory.cs, src/Lucene.Net.Tests.Analysis.OpenNLP/Lucene.Net.Tests.Analysis.OpenNLP.csproj, src/Lucene.Net/Lucene.Net.csproj, src/dotnet/tools/Lucene.Net.Tests.Cli/Lucene.Net.Tests.Cli.csproj
Added net6.0 target to Lucene.Net.Analysis.OpenNLP and changed to using MavenReference
Closes #852, closes #460, related: #890
This supersedes and closes #852. It drops the package dependency on [OpenNLP.NET](https://www.nuget.org/packages/OpenNLP.NET), and instead uses `<MavenReference>` to add a dependency on [opennlp-tools](https://central.sonatype.com/artifact/org.apache.opennlp/opennlp-tools/1.9.4).
`<MavenReference>` does not add a binary to our distribution (except for IKVM and its dependencies). Instead, it transitively gets added to any SDK-style project that depends on Lucene.Net.Analysis.OpenNLP. Each dependency from Maven is downloaded and converted from bytecode into IL on the user's build machine.
This allows the user to add …
=> Added net6.0 target to Lucene.Net.Analysis.OpenNLP and changed to using MavenReference

src/Lucene.Net.Tests/Search/TestSort.cs, src/Lucene.Net/Search/FieldComparator.cs
`Lucene.Net.Search.FieldComparer.TermValComparer`: Fixed sorting ambiguity between empty fields and missing fields
When using `Arrays.Empty<T>()` we get a singleton instance. However, this comparer uses reference equality to compare the static fields `MISSING_BYTES` and `NON_MISSING_BYTES`. This reverts back to `new byte[0]` to ensure the reference equality checks pass.
This PR also adds an internal constructor to `FieldComparer`, since this is a class that we added to make Lucene.NET compile. It is confusing for users who are upgrading because in older versions `FieldComparer` was not a generic class. Users who are upgrading should use `FieldComparer<T>`, which reduces or eliminates the need for casting of the underlying type.
=> BUG: Lucene.Net.Search.FieldComparer.TermValComparer: Fixed sorting ambiguity between empty fields and missing fields

.github/workflows/sonar.yml
Only trigger SonarCloud on solution updates (not docs, website, or other files)
Fixes #873
Only trigger SonarCloud on solution updates (not docs, website, or CI files).
This PR also updates the SonarCloud workflow to use .NET 8 SDK, which we will need soon when we add .NET 8 tests.
=> ci: Only trigger SonarCloud on solution updates (not docs, website, or CI files). Fixes #873.

src/Lucene.Net.Replicator/LocalReplicator.cs, src/Lucene.Net.TestFramework/Codecs/RAMOnly/RAMOnlyPostingsFormat.cs, src/Lucene.Net.TestFramework/Store/MockDirectoryWrapper.cs, src/Lucene.Net.Tests/Search/TestBooleanOr.cs, src/Lucene.Net/Store/RAMFile.cs
SWEEP: Reviewed usage of atomic numeric type methods
Fixes #917
This aligns usages of `GetAndAdd()`, `AddAndGet()`, `IncrementAndGet()`, `GetAndIncrement()`, `DecrementAndGet()`, and `GetAndDecrement()` match Lucene (for both `AtomicInt32` and `AtomicInt64`). There were no significant issues found, but some of the adjacent code was corrected to use the correct types, casts, and formatting in the invariant culture.
=> SWEEP: Reviewed usage of atomic numeric type methods

src/Lucene.Net.Tests/Index/TestIndexWriterOnJRECrash.cs, src/Lucene.Net.Tests/Support/TestConcurrentHashSet.cs, src/Lucene.Net/Store/FSDirectory.cs, src/Lucene.Net/Support/ConcurrentHashSet.cs, src/Lucene.Net/Support/IO/PosixFsyncSupport.cs, src/Lucene.Net/Support/IO/WindowsFsyncSupport.cs, src/Lucene.Net/Support/Native/Interop.MacOS.Constants.cs, src/Lucene.Net/Support/Native/Interop.Posix.Close.cs, src/Lucene.Net/Support/Native/Interop.Posix.Constants.cs, src/Lucene.Net/Support/Native/Interop.Posix.Fcntl.cs, src/Lucene.Net/Support/Native/Interop.Posix.Fsync.cs, src/Lucene.Net/Support/Native/Interop.Posix.Open.cs, src/Lucene.Net/Support/Native/Interop.Win32.CloseHandle.cs, src/Lucene.Net/Support/Native/Interop.Win32.Constants.cs, src/Lucene.Net/Support/Native/Interop.Win32.CreateFileW.cs, src/Lucene.Net/Support/Native/Interop.Win32.FlushFileBuffers.cs, src/Lucene.Net/Util/IOUtils.cs
This restores the commented-out fsync behavior in FSDirectory to help mitigate a performance regression in .NET 8.
Fixes #933
See 933 for more details. Perf benchmark before:
```
| Method                  | Job      | Runtime  | IterationCount | LaunchCount | WarmupCount | N  | Mean      | Error      | StdDev   | Median    | Ratio | RatioSD |
|------------------------ |--------- |--------- |--------------- |------------ |------------ |--- |----------:|-----------:|---------:|----------:|------:|--------:|
| IndexDocumentsBenchmark | .NET 7.0 | .NET 7.0 | Default        | Default     | Default     | 10 |  44.11 ms |   3.756 ms | 11.02 ms |  40.34 ms |  1.00 |    0.00 |
| IndexDocumentsBenchmark | .NET 8.0 | .NET 8.0 | Default        | Default     | Default     | 10 | 843.36 ms |  16.485 ms …
```
=> Restore fsync behavior in FSDirectory via P/Invoke, #933

src/Lucene.Net/Search/ReferenceManager.cs
When it is a concrete type, this is avoided. Since this is an internal field there's no reason to use the abstracted type. 
See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1859
=> Use concrete ConcurrentHashSet instead of abstraction for performance

websites/site/.htaccess, websites/site/site.ps1
Website /latest/ using .htaccess rewrite rules
I don't think there is an issue for this one but it's a feature we have been wanting for a while.
This pull request introduces a new URL redirection feature for the Lucene.NET website. It sets up two redirects into the API documentation using .htaccess rewrite rules. The implementation adds two useful URL paths:
•	/doc/latest/: Redirects users to the API documentation for the most recent officially released version of Lucene.NET.
•	/doc/absolute-latest/: Directs users to the absolute latest version of the API documentation, which may include pre-release versions.
These redirects allow the main website to link to the API documentation dynamically, without hardcoding the version number in the URLs, …
=> feature/website support for /latest/ and /absolute-latest/ redirection

src/Lucene.Net.Replicator/Http/HttpClientBase.cs, src/Lucene.Net.Replicator/Http/ReplicationService.cs
Backport of a serialization fix from Lucene.
This backports a serialization fix in the upstream Lucene project to avoid arbitrary type instantiation when errors occur.
Upstream commit: https://github.com/apache/lucene/commit/b4b153f64fb0420c6e28ddea4c442e119458756c
=> BREAKING: Backport serialization fix for replicator

.build/dependencies.props
Upgrades System.Text.Json to 6.0.10 for net462 due to 6.0.6 advisory: https://github.com/advisories/GHSA-8g4q-xg66-9fp4
=> Upgrade TestFramework System.Text.Json reference to 6.0.10 for net462 target

src/Lucene.Net.QueryParser/Classic/QueryParserTokenManager.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Parser/StandardSyntaxParserTokenManager.cs
Leave debugStream as null on construction of parser token managers.
Fixes #{bug number} (in this specific format)
Fixes #936
{Detail}
* When `debugStream` is set to `Console.Out` by default, `StandardSyntaxParserTokenManager` throws an exception when constructing a `StandardQueryParser` on OSes that do not support System.Console, such as iOS and Android.
* `debugStream` can be set later using the setter, if needed.
* The above is the same for `QueryParserTokenManager` when constructing a `QueryParser`.
* See issue https://github.com/apache/lucenenet/issues/936 for details.
=> Leave debugStream as null on construction of parser token managers

Directory.Build.targets, src/Lucene.Net.Facet/Taxonomy/WriterCache/NameIntCacheLRU.cs, src/Lucene.Net.TestFramework/Util/Fst/FSTTester.cs, src/Lucene.Net/Index/IndexWriter.cs
Summary of the changes
Removed FEATURE_DICTIONARY_REMOVE_CONTINUEENUMERATION from the codebase
Fixes #978
Removed FEATURE_DICTIONARY_REMOVE_CONTINUEENUMERATION from the codebase.
Also, updated private fields to use `J2N.Collections.Generic.Dictionary<TKey,TValue>` for a performance boost when we upgrade to J2N 3.x `GetEnumerator()` currently boxes from struct to interface, but the breaking API change will return the struct instead, avoiding the boxing.
=> Removed FEATURE_DICTIONARY_REMOVE_CONTINUEENUMERATION from the codebase

.build/azure-templates/publish-test-results-for-test-projects.yml, src/dotnet/tools/Lucene.Net.Tests.Cli/Lucene.Net.Tests.Cli.csproj, src/dotnet/tools/lucene-cli/lucene-cli.csproj
lucene-cli: Removed target and tests for `net6.0`
Fixes #979
This removes the `net6.0` target from lucene-cli. The runtime to use it will be out of support in a few days, so we don't need it for the next release. This reduces the total distribution size of .nupkg and .snupkg files from 127MB to 108MB, and will save us some disk space during publish, as well.
=> lucene-cli: Removed target and tests for net6.0 (fixes #979)

Lucene.Net.sln, global.json, websites/websites.msbuildproj
The old docs project in the sln was based on the old .net framework 'websites' since msbuild/.net didn't have a nice way to have a project that just contains files.
Now, with the no-targets SDK project type, this is possible.
This just replaces the old docs project with a new one that uses the no-targets SDK project type
=> Replaces old docs project with modern 'no-targets' msbuild project

.build/runbuild.ps1
.build/runbuild.ps1: Changed to edit the global.json file instead of overwriting it to account for any future changes to it.
This fixes the Azure DevOps and command line build, which was inadvertently broken by #987.
=> .build/runbuild.ps1: Changed to edit the global.json file instead of overwriting it to account for any future changes to it.

src/Lucene.Net.TestFramework/Index/BaseMergePolicyTestCase.cs, src/Lucene.Net.Tests/Index/TestIndexWriterMerging.cs, src/Lucene.Net.Tests/TestMergeSchedulerExternal.cs, src/Lucene.Net/Index/ConcurrentMergeScheduler.cs, src/Lucene.Net/Index/IndexWriter.cs, src/Lucene.Net/Index/MergeScheduler.cs, src/Lucene.Net/Index/SerialMergeScheduler.cs, src/Lucene.Net/Support/Index/TaskMergeScheduler.cs
Reverts rename of `IndexWriter.NextMerge()` back to `GetNextMerge()` to match Java.
Fixes #986 
Simple refactor rename for all usages of `IndexWriter.NextMerge()` to `GetNextMerge()`.
=> Rename IndexWriter.NextMerge() to GetNextMerge(), #986

websites/apidocs/docfx.analysis-common.json, websites/apidocs/docfx.analysis-kuromoji.json, websites/apidocs/docfx.analysis-morfologik.json, websites/apidocs/docfx.analysis-opennlp.json, websites/apidocs/docfx.analysis-phonetic.json, websites/apidocs/docfx.analysis-smartcn.json, websites/apidocs/docfx.analysis-stempel.json, websites/apidocs/docfx.benchmark.json, websites/apidocs/docfx.classification.json, websites/apidocs/docfx.codecs.json, websites/apidocs/docfx.core.json, websites/apidocs/docfx.demo.json, websites/apidocs/docfx.expressions.json, websites/apidocs/docfx.facet.json, websites/apidocs/docfx.grouping.json, websites/apidocs/docfx.highlighter.json, websites/apidocs/docfx.icu.json, websites/apidocs/docfx.join.json, websites/apidocs/docfx.json, websites/apidocs/docfx.memory.json, websites/apidocs/docfx.misc.json, websites/apidocs/docfx.queries.json, websites/apidocs/docfx.queryparser.json, websites/apidocs/docfx.replicator.json, websites/apidocs/docfx.sandbox.json, websites/apidocs/docfx.spatial.json, websites/apidocs/docfx.suggest.json, websites/apidocs/docfx.test-framework.json
Uses the .NET 8 target for docs generation.
Related: #928
The docs generation was using the net6.0 target as the latest available; as of #982 we now have the net8.0 target, so this updates the docfx json files to use that target instead.
=> Use .NET 8 target for docs generation, #928

src/Lucene.Net.Analysis.OpenNLP/overview.md
… 
Fixed some errors in the OpenNLP docs that stated "transient" instead of "transitive" dependencies.
=> docs: OpenNLP: Corrected errors (transitive instead of transient) in the docs

README.md
Updates the .NET support information in the README.
Related to #928 
Updates the README to add the .NET 8 target, specify that the CLI requires the .NET 8 runtime, and removes references to older unsupported frameworks.
=> Update README.md for .NET support

websites/site/.gitattributes, websites/site/.htaccess
Fixes a website/site/.htaccess BOM bug, also updates to beta00017 redirects
Apache web server requires that the .htaccess file not be saved with a BOM.  The one previously committed accidentally contained a BOM, causing issues when deployed to the asf-site branch of the lucent-site repo.  This PR fixes that and also updates the related /docs/absolute-latest/ redirection to be to /docs/4.8.0-beta00017/
=> website/site/.htaccess - bug fix by removing BOM and update to beta0017 redirection

src/Lucene.Net.Tests/Search/TestFuzzyQuery.cs, src/Lucene.Net/Search/FuzzyQuery.cs
FuzzyQuery produces a wrong result when prefix is equal to the term length
Fixes #941 
See #941
(NOTE: This PR was originally opened as #945 but included an unexpected commit. This PR cherry-picks that commit.)
=> FuzzyQuery produces a wrong result when prefix is equal to the term length

.github/pull_request_template.md, .github/release.yml, websites/site/contributing/make-release.md
Summary of the changes
Added Automation for Release Notes
Added a `.github/release.yml` template to automatically generate and categorize the release notes using PR titles and labels.
Also updated the release procedure because generating the release notes requires the tag to exist.
> NOTE: To those merging PRs, it will make releases easier if we address the following before merging PRs:
> 
> 1. Change the title to concisely describe the change in the PR (keep in mind it will be a line item in the release notes)
> 2. Add a label to categorize (or ignore) the PR using the following table:
| GitHub Label                   | Action                                                   |
|--------------------------------|----------------------------------------------------------|
| notes:ignore …
=> Added GitHub Automation for Release Notes

.github/release.yml, websites/site/contributing/make-release.md
Summary of the changes 
Added "Improvements" Category for Release Notes, as we had that category in prior releases and some PRs are hard to categorize without it.
=> Added "Improvements" Category for Release Notes

src/Lucene.Net.Analysis.Common/Analysis/CommonGrams/CommonGramsFilterFactory.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Commongrams/TestCommonGramsFilterFactory.cs
=> Respect ignoreCase flag in CommonGramsFilterFactory

.build/dependencies.props
Upgrade NUnit to 3.14.0, as well as the test adapter and VS test SDK packages.
Related #259 
This fixes an issue in Rider with test discovery, impacting the ability to see and individually run child tests of test classes.
=> Upgrade NUnit to 3.14 and update test adapter and VS test SDK packages

src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
Improves the failed unit test message to provide an example lucene.testsettings.json.
Fixes #999
The lucene.testsettings.json seems to work more reliably and is a little more user-friendly than the runsettings file, so this improves the failed unit test message to provide a generated lucene.testsettings.json file. This also uses C# 11 multi-line strings instead of manual string concatenation.
=> Improve message for unit test failures for lucene.testsettings.json, #999

src/Lucene.Net/Analysis/ReusableStringReader.cs
Make ReusableStringReader internal
Fixes #1029
This was incorrectly ported as public; this now matches Lucene. This is a breaking change.
=> BREAKING: Make ReusableStringReader internal

src/Lucene.Net.Analysis.Common/Analysis/Shingle/ShingleFilterFactory.cs, src/Lucene.Net.Analysis.Common/Analysis/Synonym/SynonymFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Synonym/SynonymMap.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/CharacterUtils.cs, src/Lucene.Net.Analysis.Kuromoji/JapaneseKatakanaStemFilterFactory.cs, src/Lucene.Net.Analysis.Phonetic/Language/Bm/PhoneticEngine.cs, src/Lucene.Net.Benchmark/ByTask/Benchmark.cs, src/Lucene.Net.Benchmark/Quality/Trec/QueryDriver.cs, src/Lucene.Net.Benchmark/Quality/Utils/QualityQueriesFinder.cs, src/Lucene.Net.Benchmark/Utils/ExtractWikipedia.cs, src/Lucene.Net.Facet/Taxonomy/PrintTaxonomyStats.cs, src/Lucene.Net.Highlighter/VectorHighlight/BaseFragListBuilder.cs, src/Lucene.Net.Misc/Index/IndexSplitter.cs, src/Lucene.Net.Misc/Index/MultiPassIndexSplitter.cs, src/Lucene.Net.Misc/Misc/GetTermInfo.cs, src/Lucene.Net.Misc/Misc/HighFreqTerms.cs, src/Lucene.Net.Misc/Misc/IndexMergeTool.cs, src/Lucene.Net.Queries/TermFilter.cs, src/Lucene.Net.Suggest/Suggest/Fst/FSTCompletionBuilder.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Synonym/TestSynonymMapFilter.cs, src/Lucene.Net.Tests.Queries/TermFilterTest.cs, src/Lucene.Net/Index/IndexUpgrader.cs, src/Lucene.Net/Index/IndexWriterConfig.cs, src/Lucene.Net/Search/MinShouldMatchSumScorer.cs, src/Lucene.Net/Store/CompoundFileWriter.cs, src/Lucene.Net/Store/LockStressTest.cs, src/Lucene.Net/Store/LockVerifyServer.cs, src/Lucene.Net/Util/Automaton/BasicAutomata.cs, src/Lucene.Net/Util/UnicodeUtil.cs
Fix incorrect usage of argument exceptions for Sonar csharpsquid:S3928
Fixes #682
This addresses a few incorrect usages of various argument exceptions, such as missing/incorrect parameter names, using ArgumentOutOfRangeException with a parameter name that doesn't exist, missing messages for ArgumentException, and so on.
For the analysis factories, these were reverted to be ArgumentException because various analysis tools (including Sonar and ReSharper/Rider) complain about using a key name for the dictionary when it doesn't exist as a parameter.
=> Fix incorrect usage of argument exceptions for Sonar csharpsquid:S3928, #682

Lucene.Net.sln.DotSettings, src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs, src/Lucene.Net.Tests/Index/TestIndexWriterOnJRECrash.cs
Replace lucene.testSettings.config references with lucene.testsettings.json
Fixes #997
There were still some places in comments where we were referencing `lucene.testSettings.config` as the file name for setting your seed/culture, when it should be `lucene.testsettings.json`. This does a solution-wide find and replace for those occurrences in comments.
=> Replace lucene.testSettings.config references with lucene.testsettings.json

src/Lucene.Net.Analysis.Kuromoji/JapaneseTokenizerFactory.cs, src/Lucene.Net.Analysis.Kuromoji/Support/Util/EncodingProviderInitializer.cs, src/Lucene.Net.Analysis.Kuromoji/Tools/ConnectionCostsWriter.cs, src/Lucene.Net.Analysis.Kuromoji/Tools/DictionaryBuilder.cs, src/Lucene.Net.Analysis.SmartCn/AnalyzerProfile.cs, src/Lucene.Net.Analysis.SmartCn/Support/Util/EncodingProviderInitializer.cs, src/Lucene.Net.Tests.Analysis.Common/Startup.cs
Fixed encoding provider loading on .NET Framework (for .NET Standard 2.0 target)
Fixes #1025
Added `EncodingProviderInitializer` class to `Lucene.Net.Analysis.Kuromoji` and `Lucene.Net.Analysis.SmartCn` to prevent loading problems on the `netstandard2.0` target when the runtime is .NET Framework.
=> Fixed encoding provider loading on .NET Framework (for .NET Standard 2.0 target)

src/Lucene.Net.Facet/Taxonomy/WriterCache/CharBlockArray.cs, src/Lucene.Net.Tests.Facet/Taxonomy/WriterCache/TestCharBlockArray.cs, src/Lucene.Net.Tests/Analysis/TokenAttributes/TestCharTermAttributeImpl.cs, src/Lucene.Net/Analysis/TokenAttributes/CharTermAttribute.cs, src/Lucene.Net/Analysis/TokenAttributes/CharTermAttributeImpl.cs
Implement `ISpanAppendable` in `CharBlockArray` and `CharTermAttributeImpl`
Fixes #1026
This adds `ISpanAppendable` to the `CharBlockArray` and `CharTermAttributeImpl` classes. The classes implement the interface explicitly so that we can provide a default implementation that returns itself rather than `ISpanAppendable`, to match the existing Append overloads.
Note that while `IAppendable` is now redundant in the interface list for these types, I left it there for Lucene source compatibility and reference, since `ISpanAppendable` does not exist in Lucene.
=> Implement ISpanAppendable in CharBlockArray and CharTermAttributeImpl

src/Lucene.Net.Analysis.Common/Analysis/CharFilter/HTMLStripCharFilter.cs, src/Lucene.Net.Analysis.Common/Analysis/Nl/DutchAnalyzer.cs, src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/ScriptIterator.cs, src/Lucene.Net.Analysis.Kuromoji/JapaneseAnalyzer.cs, src/Lucene.Net.Analysis.Phonetic/Language/Bm/Lang.cs, src/Lucene.Net.Analysis.Phonetic/Language/Bm/Languages.cs, src/Lucene.Net.Benchmark/ByTask/Feeds/TrecDocParser.cs, src/Lucene.Net.Benchmark/Support/TagSoup/ElementType.cs, src/Lucene.Net.Misc/Document/LazyDocument.cs, src/Lucene.Net.QueryParser/ComplexPhrase/ComplexPhraseQueryParser.cs, src/Lucene.Net/Codecs/Lucene45/Lucene45DocValuesConsumer.cs, src/Lucene.Net/Index/FieldInfos.cs, src/Lucene.Net/Index/SortedSetDocValuesWriter.cs, src/Lucene.Net/Support/CRC32.cs, src/Lucene.Net/Util/SPIClassIterator.cs
Fix csharpsquid:S1117 SonarCloud warnings about shadowing fields with variable names
Fixes #678
This renames variables that shadowed fields of the same name, causing the SonarCloud S1117 warning. In the case of methods that replace static constructor initialization, this was named `result` instead of the field name. In other cases where there was no Lucene equivalent, the variable was renamed.
This also fixes a bug in FieldInfos where there was the possibility of a KeyNotFoundException due to a coding oversight.
This investigation discovered a potential maintainability bug in `SortedSetDocValuesWriter.Flush`. Due to GetOrdCountEnumerable and GetOrdsEnumerable (previously named with a typo) having the same return type, their names were accidentally swapped. I fixed the typo in the names …
=> Fix csharpsquid:S1117 SonarCloud warnings about shadowing fields with variable names

src/Lucene.Net.Tests.Analysis.ICU/Analysis/Icu/TestICUFoldingFilterFactory.cs
Removes `[AwaitsFix]` from TestICUFoldingFilterFactory.Test
Related #269
This test passes on Ubuntu 24.04 in my local testing. It was noted that it failed on Ubuntu 18.04 on GitHub Actions, but that is no longer a supported distribution for any of our current targets. This removes the `[AwaitsFix]` from this test to see if it passes in GitHub Actions on Ubuntu today, and if so, we can merge this to re-enable the test.
=> Enable TestICUFoldingFilterFactory.Test

src/Lucene.Net.Expressions/JS/JavascriptCompiler.cs
Mask off 63 from shift operand to prevent overflow on x86, and cast to 32-bit operand.
Fixes #1034
On x86 .NET Framework, the ANTLR/IL changes in #996 behave differently than other platforms. This seems to be due to x86 .NET Framework not masking off the operand correctly. Other platforms mask this off by 0x3f (63) since shifting by 64 or more would overflow, so this basically wraps the shift instead of overflowing. x86 netfx for some reason does not do this correctly. This adds a mask that does no harm on other platforms, but ensures that all are operating the same way.
Additionally, to fix an issue on .NET 5/6 (still usable with our netstandard2.1 target), the right operand must be an Int32 in case it overflows. If the operand is an Int64 and it is out of range, it can crash the process …
=> Expressions.JS: Bitwise left shift bugfixes, #1034

src/Lucene.Net.Tests/Util/TestByteBlockPool.cs, src/Lucene.Net/Util/ByteBlockPool.cs
Fix overflow (resulting in ArrayIndexOutOfBoundsException) in ByteBlockPool
Fixes #1003
Thanks to @hidingmyname for the provided test. This fixes an arithmetic overflow that results in an ArrayIndexOutOfBoundsException in ByteBlockPool for fields with a large number of small tokens. In .NET, the `checked` block causes the overflow to throw an OverflowException, just like how the upstream Java change to use `Math.addExact(x, y)` throws an ArithmeticException in that case.
=> Fix overflow in ByteBlockPool, #1003

Lucene.Net.sln.DotSettings, src/Lucene.Net.Benchmark/Quality/QualityQuery.cs, src/Lucene.Net.Highlighter/VectorHighlight/FieldPhraseList.cs, src/Lucene.Net.Highlighter/VectorHighlight/FieldTermStack.cs, src/Lucene.Net.QueryParser/Surround/Query/SimpleTerm.cs, src/Lucene.Net.Spatial/Prefix/Tree/Cell.cs, src/Lucene.Net.Suggest/Suggest/Fst/FSTCompletion.cs, src/Lucene.Net.Suggest/Suggest/Lookup.cs, src/Lucene.Net/Index/IndexCommit.cs, src/Lucene.Net/Index/Term.cs, src/Lucene.Net/Util/Automaton/State.cs, src/Lucene.Net/Util/BytesRef.cs, src/Lucene.Net/Util/CharsRef.cs, src/Lucene.Net/Util/IntsRef.cs, src/Lucene.Net/Util/LongsRef.cs, src/Lucene.Net/Util/Mutable/MutableValue.cs
Add operator overrides for public IComparable types
Fixes #683
This is to resolve the Sonar warning about needing to override the comparison operators for any types that implement IComparable. We are only doing this here for the public types.
QualityQuery was missing Equals and GetHashCode, as well as had some possible NullReferenceExceptions, so those have been fixed as well.
=> Add operator overrides for public IComparable types, #683

src/Lucene.Net.Replicator/LocalReplicator.cs, src/Lucene.Net.Tests._J-S/Lucene.Net.Tests._J-S.csproj, src/Lucene.Net.Tests/Support/Threading/AtomicDoubleTest.cs, src/Lucene.Net/Index/IndexWriter.cs, src/Lucene.Net/Index/IndexWriterConfig.cs, src/Lucene.Net/Index/LiveIndexWriterConfig.cs, src/Lucene.Net/Index/MergePolicy.cs, src/Lucene.Net/Index/SegmentCommitInfo.cs, src/Lucene.Net/Search/ControlledRealTimeReopenThread.cs, src/Lucene.Net/Search/TimeLimitingCollector.cs, src/Lucene.Net/Store/RateLimiter.cs, src/Lucene.Net/Support/Threading/AtomicDouble.cs
Convert long/double values that are volatile in Lucene (but can't be in .NET) to AtomicInt64 or (new) AtomicDouble.
Fixes #1063
Since we can't use `volatile` on 64-bit values in .NET, this doesn't work for `long` or `double`. This PR changes `volatile long` fields to be `AtomicInt64` from J2N, as well as introduces a new internal `AtomicDouble` type in Support for those values, using bit conversion to/from long internally so that we can use Interlocked on it.
=> Convert Lucene volatile long/double values to Atomic counterparts, #1063

src/Lucene.Net.TestFramework/Index/MockRandomMergePolicy.cs, src/Lucene.Net.Tests/Index/TestIndexWriter.cs, src/Lucene.Net.Tests/Util/TestSetOnce.cs, src/Lucene.Net/Index/IndexWriterConfig.cs, src/Lucene.Net/Index/LogMergePolicy.cs, src/Lucene.Net/Index/MergePolicy.cs, src/Lucene.Net/Index/TieredMergePolicy.cs, src/Lucene.Net/Index/UpgradeIndexMergePolicy.cs, src/Lucene.Net/Support/ObsoleteAPI/SetOnce.cs, src/Lucene.Net/Util/SetOnce.cs
Replaces Get and Set on the `SetOnce<T>` type with a new `Value` property, marks old methods as deprecated for removal.
Fixes #1069
In addition to the above, this also enables nullable in the file, and adds more meaningful exceptions in cases where otherwise it could possibly throw a NRE.
=> BREAKING: Replace SetOnce Get/Set with Value, #1069

src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs, src/Lucene.Net.Analysis.Common/Analysis/Synonym/SynonymMap.cs, src/Lucene.Net.Analysis.Kuromoji/Dict/BinaryDictionary.cs, src/Lucene.Net.Analysis.Kuromoji/Dict/CharacterDefinition.cs, src/Lucene.Net.Analysis.Kuromoji/Dict/ConnectionCosts.cs, src/Lucene.Net.Analysis.Kuromoji/Tools/BinaryDictionaryWriter.cs, src/Lucene.Net.Analysis.Kuromoji/Tools/CharacterDefinitionWriter.cs, src/Lucene.Net.Analysis.Kuromoji/Tools/ConnectionCostsBuilder.cs, src/Lucene.Net.Analysis.Kuromoji/Tools/ConnectionCostsWriter.cs, src/Lucene.Net.Analysis.Kuromoji/Tools/TokenInfoDictionaryBuilder.cs, src/Lucene.Net.Codecs/Memory/DirectPostingsFormat.cs, src/Lucene.Net.Demo/SearchFiles.cs, src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyWriter.cs, src/Lucene.Net.Misc/Index/IndexSplitter.cs, src/Lucene.Net.Misc/Index/MultiPassIndexSplitter.cs, src/Lucene.Net.Misc/Misc/GetTermInfo.cs, src/Lucene.Net.Misc/Misc/HighFreqTerms.cs, src/Lucene.Net.Spatial/Query/SpatialArgsParser.cs, src/Lucene.Net.Suggest/Suggest/Lookup.cs, src/Lucene.Net.TestFramework/Search/ShardSearchingTestBase.cs, src/Lucene.Net.TestFramework/Util/TestUtil.cs, src/Lucene.Net.Tests.Suggest/Suggest/Fst/LargeInputFST.cs, src/Lucene.Net/Codecs/Lucene45/Lucene45DocValuesConsumer.cs, src/Lucene.Net/Index/FlushPolicy.cs, src/Lucene.Net/Store/InputStreamDataInput.cs, src/Lucene.Net/Store/LockStressTest.cs, src/Lucene.Net/Store/LockVerifyServer.cs, src/Lucene.Net/Store/OutputStreamDataOutput.cs, src/Lucene.Net/Util/Constants.cs, src/Lucene.Net/Util/Fst/FST.cs
Disposes of some IDisposable objects that are not properly cleaned up.
Fixes #615
Partial #265
This adds `using` statements to clean up some disposable objects where it's possible to do so, after a review of our codebase with CA2000 code analysis warnings on, where the objects were determined to not "leak" via fields, return values, or the like. This also fixes two FileStream leaks in demo code, #615.
Note that CA2000 is _way_ too noisy to leave on, as there are literally hundreds of "violations" that would make our code a mess with `#pragma` suppressions. The Java upstream code is perhaps a little loose with keeping track of ICloseable lifetimes, but we have to match that in most cases. The cases fixed here were just ones where the object lifetime did not escape the method and it was …
=> Dispose of some disposables, #265, #615

src/Lucene.Net/Index/IndexReader.cs
Simplify IndexReader constructor.
Fixes #919
This removes the type check in the IndexReader constructor that ensures that only CompositeReader and AtomicReader are allowed subtypes. This is not needed since in C# we can use the `private protected` modifier to ensure that no outside classes can subtype this. This removes the need for the runtime check in the constructor, which will mildly improve performance. A comment was left explaining the divergence with the original commented-out code.
=> Simplify IndexReader constructor, #919

src/Lucene.Net.Benchmark/Support/Sax/Ext/Attributes2.cs, src/Lucene.Net.Benchmark/Support/Sax/Ext/Attributes2Impl.cs, src/Lucene.Net.Benchmark/Support/Sax/Helpers/AttributesImpl.cs, src/Lucene.Net.Codecs/SimpleText/SimpleTextDocValuesReader.cs, src/Lucene.Net.Memory/MemoryIndexNormDocValues.cs, src/Lucene.Net/Codecs/Lucene40/BitVector.cs, src/Lucene.Net/Index/DocValues.cs, src/Lucene.Net/Index/SegmentReader.cs, src/Lucene.Net/Support/ExceptionHandling/ExceptionExtensions.cs, src/Lucene.Net/Util/BytesRefArray.cs, src/Lucene.Net/Util/UnicodeUtil.cs
Replaces IndexOutOfRangeException use with ArgumentOutOfRangeException when thrown from a method rather than an indexer.
Fixes #1023 
It is not correct in .NET to use IndexOutOfRangeException to throw exceptions from a non-indexer method when an argument is out of range, even if that argument is named `index`; that is what ArgumentOutOfRangeException is for. Additionally, this has the added benefit of having the `paramName` set to know which argument is out of range.
=> SWEEP: Replace IndexOutOfRangeException with ArgumentOutOfRangeException except for indexer use, #1023

src/Lucene.Net.Benchmark/ByTask/Tasks/WriteEnwikiLineDocTask.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/WriteLineDocTask.cs, src/Lucene.Net.Benchmark/Quality/Trec/QueryDriver.cs, src/Lucene.Net.Benchmark/Utils/ExtractReuters.cs, src/Lucene.Net.Benchmark/Utils/ExtractWikipedia.cs, src/Lucene.Net.TestFramework/Util/Fst/FSTTester.cs, src/Lucene.Net.TestFramework/Util/TestUtil.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Hunspell/Test64kAffixes.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestFilesystemResourceLoader.cs, src/Lucene.Net.Tests.Benchmark/ByTask/Feeds/DocMakerTest.cs, src/Lucene.Net.Tests.Benchmark/ByTask/Feeds/LineDocSourceTest.cs, src/Lucene.Net.Tests.Benchmark/ByTask/Utils/StreamUtilsTest.cs, src/Lucene.Net.Tests.Demo/TestDemo.cs, src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyFacetCounts.cs, src/Lucene.Net.Tests/Index/TestCheckIndex.cs, src/Lucene.Net.Tests/Index/TestDocInverterPerFieldErrorInfo.cs, src/Lucene.Net.Tests/Index/TestIndexWriterDelete.cs, src/Lucene.Net.Tests/Index/TestPayloads.cs, src/Lucene.Net.Tests/Search/Spans/TestBasics.cs, src/Lucene.Net.Tests/Util/Fst/TestFSTs.cs, src/Lucene.Net.Tests/Util/TestOfflineSorter.cs, src/Lucene.Net/Codecs/Compressing/CompressingStoredFieldsReader.cs, src/Lucene.Net/Codecs/Lucene3x/Lucene3xStoredFieldsReader.cs, src/Lucene.Net/Codecs/Lucene40/Lucene40StoredFieldsReader.cs, src/Lucene.Net/Index/Term.cs, src/Lucene.Net/Support/StandardCharsets.cs, src/Lucene.Net/Util/IOUtils.cs, src/Lucene.Net/Util/OfflineSorter.cs
Use BOM-less UTF-8 encoding for writes
Fixes #1027
See #1027 for details.
=> BREAKING: Use BOM-less UTF-8 encoding for writes, #1027

src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestNumericQueryParser.cs
Fixes tests that fail randomly when the randomly selected culture is zh-Hant-TW and the time zone offset is negative.
Partial #846
See this comment for full details explaining the problem: https://github.com/apache/lucenenet/issues/846#issuecomment-2566110261
The solution was to ensure that the zh-Hant-TW culture (on .NET 6-8 when it is missing the `tt` in the LongTimePattern) does not pass the "sanity" check when there is a time zone with a negative offset due to this round-trip formatting/parsing bug. There already was a sanity check for the unix epoch (long value 0) which ensured the round-trip to/from string was parsed _successfully_, but it was not checking that it was parsed _correctly_. This code had been modified heavily from the original Lucene and was missing this equality …
=> Fix failing QueryParser Flexible tests due to zh-Hant-TW culture bug, #846

.build/azure-templates/publish-test-results.yml, .build/azure-templates/run-tests-on-os.yml, azure-pipelines.yml, src/Lucene.Net.TestFramework/Search/RandomSimilarityProvider.cs, src/Lucene.Net.TestFramework/Support/Util/LuceneTestCase.SetUpFixture.cs, src/Lucene.Net.TestFramework/Support/Util/TestExtensions.cs, src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs, src/Lucene.Net.Tests.AllProjects/Support/ExceptionHandling/TestExceptionExtensions.cs
Improved error handling and test reporting
This fixes several concerns regarding output during testing:
1. The details of the random test configuration are now output only if the test fails and will appear in the test message directly. This used to be where they appeared in older versions of NUnit and this restores that functionality.
2. Exceptions that were being called in `LuceneTestCase.OneTimeStartUp()` and `LuceneTestCase.OneTimeTearDown()` were not very visible because NUnit doesn't fail the test when they occur there. This changes it from re-throwing exceptions with an additional message to logging to the output. It goes to stderr in all cases except in `OneTimeTearDown()` where something is redirecting it to stdout. Either way, this changes the ADO pipeline to fail the build so we …
=> Lucene.Net.TestFramework: Improved error handling and test reporting

src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
Finishes implementation of the `[SuppressTempFileChecks]` attribute functionality.
Fixes #898
This attribute will cause the tear down logic to swallow any exceptions when cleaning up temporary files after the tests run. No tests actually need this attribute, but theoretically it is possible that a TestFramework user might want this. 
This also fixes an issue where the previous code was treating _all_ tests as if it had this attribute, and was not throwing if removing the temporary files failed. This change will make our tests more reliable by ensuring they fail if temp file handles are held during cleanup.
I'm also open to removing this attribute, since none of our tests need it and latest Lucene doesn't use it internally either. It could be viewed as a bad practice to just ignore these …
=> Finish [SuppressTempFileChecks] attribute functionality, #898

src/Lucene.Net.Tests/Support/Document/Extensions/TestIndexableFieldExtensions.cs, src/Lucene.Net.Tests/Support/IO/TestByteArrayOutputStream.cs, src/Lucene.Net.Tests/Support/TestAssemblyUtils.cs, src/Lucene.Net.Tests/Support/TestDictionaryExtensions.cs, src/Lucene.Net.Tests/Support/Util/TestCastTo.cs, src/Lucene.Net.Tests/Support/Util/TestListExtensions.cs
Adds some Support unit tests.
Partial #920
This adds unit tests for the Support namespace types listed in #920 that don't need Apache Harmony or other test considerations, including:
- IndexableFieldExtensions
- ByteArrayOutputStream
- CastTo
- ListExtensions
- AssemblyUtils
- DictionaryExtensions
=> Add some Support unit tests, #920

src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs, src/Lucene.Net.TestFramework/Codecs/Lucene42/Lucene42DocValuesConsumer.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Hunspell/TestDictionary.cs
Some minor cleanup of IDisposable pattern implementations, and a bug fix.
Fixes #265
I did a review of all implementations of `IDisposable.Dispose()` to ensure they follow the [Dispose Pattern](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern) correctly, and someone had clearly already done all of the hard work here: it was nearly all done right. There were a couple cases that I fixed in this PR:
- Lucene42DocValuesConsumer.SortedSetEnumerator did not implement the pattern correctly, but it also is an internal type with no subclasses, so this was made `sealed`.
- Hunspell's TestDictionary.CloseCheckInputStream had a curious shadowing of Dispose that was causing it to not work correctly, and this exposed a bug: the stream wrapper was getting disposed of …
=> IDisposable Pattern Cleanup and fix TestDictionary.TestResourceCleanup, #265

src/Lucene.Net.TestFramework/Support/Util/DisposableResourceInfo.cs, src/Lucene.Net.TestFramework/Support/Util/LifecycleScope.cs, src/Lucene.Net.TestFramework/Support/Util/RandomizedContext.cs, src/Lucene.Net.TestFramework/Support/Util/TestExtensions.cs, src/Lucene.Net.TestFramework/Util/CloseableDirectory.cs, src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs, src/Lucene.Net.TestFramework/Util/TestRuleMarkFailure.cs, src/Lucene.Net.Tests.Grouping/TestGroupingExtra.cs, src/Lucene.Net.Tests.TestFramework/Support/TestApiConsistency.cs, src/Lucene.Net.Tests/Util/Fst/TestFSTs.cs
Added DisposeAfterSuite/DisposeAfterTest feature to test framework
Fixes #1094
This adds the `LuceneTestCase.DisposeAfterTest()` and `LuceneTestCase.DisposeAfterSuite()` methods to the test framework that exist in Lucene 4.8.0.
It also removes the `LuceneTestCase.SuiteFailureMarker` property that wasn't implemented. NUnit already tracks the result state of the tests in `NUnit.Framework.Internal.TestExectionContext.CurrentContext.TestResult.ResultState` and `NUnit.Framework.TestContext.CurrentContext.Result.Outcome` in a context-sensitive and thread safe manner, so there is no need to reinvent the wheel with this. For the same reason, we don't need the `TestFailureMarker` property or `TestRuleMarkFailure` class, which are all part of this feature.
The new feature also revealed that there …
=> Added DisposeAfterSuite/DisposeAfterTest feature to test framework

src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestBufferedCharFilter.cs
Fixes the `TestBufferedCharFilter.Test_Ready` failing test.
Fixes #1102
Background: CharFilter.IsReady returns true if any calls to Read are guaranteed not to block. Otherwise, it means that a call may or may not block.
This test was failing because StringReader is not a CharFilter and thus it did not have an IsReady property. BufferedCharFilter only is ready if the underlying TextReader is a CharFilter and it returns true for IsReady. So given that BufferedCharFilter already properly cascaded the property, this fixes the failing test by adding a new adapter class to adapt the StringReader to a CharFilter so that it is IsReady-aware. Since StringReaders do not block on calls to Read, this always returns true.
This is perhaps a little bit of a leaky abstraction by having to know these …
=> Fix TestBufferedCharFilter.Test_Ready failing test, #1102

src/Lucene.Net.Replicator/LocalReplicator.cs
Lucene.Net.Replicator.LocalReplicator.ReplicationSession: Removed unnecessary array allocation
Fixes #1070
This changes `ReplicationSession.sessions` to use `J2N.Collections.Dictionary<TKey, TValue>` which allows deleting while iterating forward prior to .NET Core. This removes a `.ToArray()` allocation just for the sake of using an enumerator to clean up replication sessions.
=> Lucene.Net.Replicator.LocalReplicator.ReplicationSession: Removed unnecessary array allocation

src/Lucene.Net.Tests/Support/Util/Events/TestPubSubEvent.cs
Lucene.Net.Util.Events.TestPubSubEvent::CanAddSubscriptionWhileEventIsFiringNonGeneric(): Added [Ignore] attribute.
See #998
`Lucene.Net.Util.Events.TestPubSubEvent::CanAddSubscriptionWhileEventIsFiringNonGeneric()`: Added `[Ignore]` attribute, as this only applies prior to .NET Standard 2.1 and was an inherited problem from Prism.Core. This problem will eventually go away when every target below `netstandard2.1` is dropped and it doesn't seem like a priority to fix it unless a user reports a problem related to using weak events as a workaround to the fact that `ConditionalWeakTable<TKey, TValue>` didn't have an enumerator in older target frameworks.
=> Lucene.Net.Util.Events.TestPubSubEvent::CanAddSubscriptionWhileEventIsFiringNonGeneric(): Added [Ignore] attribute

src/Lucene.Net.Facet/Taxonomy/WriterCache/CharBlockArray.cs, src/Lucene.Net.Tests/Support/IO/TestStreamExtensions.cs
Add unit tests for StreamExtensions
Fixes #1105
Adds some tests adapted from Apache Harmony for the StreamExtensions extension methods.
=> Add unit tests for StreamExtensions, #1105

src/Lucene.Net.Tests/Util/TestExceptionExtensions.cs
Add unit tests for ExceptionExtensions.
Fixes #1112 
Adds unit tests for Lucene.Net.Util.ExceptionExtensions around handling suppressed extensions.
=> Add unit tests for ExceptionExtensions, #1112

Directory.Build.targets, src/Lucene.Net.Tests/Support/Threading/JSR166TestCase.cs, src/Lucene.Net.Tests/Support/Threading/TestLimitedConcurrencyLevelTaskScheduler.cs, src/Lucene.Net/Support/Threading/LimitedConcurrencyLevelTaskScheduler.cs
Adds unit tests for LimitedConcurrencyLevelTaskScheduler.
Fixes #1110
This adds some Apache Harmony tests for ThreadPoolExecutor and adapts them for testing LimitedConcurrencyLevelTaskScheduler (used in Lucene.NET in place of ThreadPoolExecutor).
This class, being a TaskScheduler, is only useful when used with i.e. a TaskFactory, so it does not have a very testable public API surface. So to exercise this class, some extension methods were added in the JSR166TestCase file to emulate a ThreadPoolExecutor's API surface. This keeps track of task state using a ConditionalWeakTable keyed on TaskScheduler, so that when the TaskScheduler is garbage collected, its state is cleaned up. The state is needed to track completed tasks, since LimitedConcurrencyLevelTaskScheduler removes/dequeues tasks …
=> Add unit tests for LimitedConcurrencyLevelTaskScheduler, #1110

src/Lucene.Net.Tests/Support/Support_CollectionTest.cs, src/Lucene.Net.Tests/Support/Support_SetTest.cs, src/Lucene.Net.Tests/Support/Support_UnmodifiableCollectionTest.cs, src/Lucene.Net.Tests/Support/TestConcurrentHashSet.cs, src/Lucene.Net.Tests/Support/Threading/JSR166TestCase.cs, src/Lucene.Net/Support/ConcurrentHashSet.cs
Add support unit tests for ConcurrentHashSet
Fixes #1117
This ports tests from Harmony for `Collections.synchronizedSet` and `ConcurrentHashMap` and adapts them to our `ConcurrentHashSet`.
This also adds nullable reference type checking to ConcurrentHashSet, which exposed some nullability issues. Given that our current use of this type is for values that should never be null (or would otherwise throw an NRE upon use as null is not checked-for), this adds a generic type constraint of `notnull` to ensure that it cannot be used with nullable reference types. Work would need to be done (under proper unit test coverage) to make this null-friendly if that is needed in the future.
=> Add support unit tests for ConcurrentHashSet, #1117

Lucene.Net.sln.DotSettings, src/Lucene.Net.Tests/Support/BaseConcurrentSetTestCase.cs, src/Lucene.Net.Tests/Support/TestConcurrentHashSet.cs, src/Lucene.Net.Tests/Support/TestConcurrentSet.cs, src/Lucene.Net.Tests/Support/TestConcurrentSetBase.cs, src/Lucene.Net/Support/ConcurrentSet.cs
Adds support unit tests for ConcurrentSet
Fixes #1118
As noted in #1118, this type should pass the same tests as ConcurrentSet (apart from the constructor differences). So this PR takes the tests created in #1117 and refactors them out into a base class that can be used for both ConcurrentHashSet and ConcurrentSet test fixtures. The two `protected abstract` methods are factory methods to create the specific implementation being tested. The two constructor tests that are specific to ConcurrentHashSet only exist on TestConcurrentHashSet.
Additionally, this PR removes a few more usages of SystemTypesHelpers in those shared tests.
=> Add Support unit tests for ConcurrentSet

src/Lucene.Net.Tests/Support/Threading/TestLimitedConcurrencyLevelTaskScheduler.cs
Fixes the LimitedConcurrencyLevelTaskScheduler timing-dependent tests.
Fixes #1123
This PR should fix the two tests in TestLimitedConcurrencyLevelTaskScheduler that are timing-dependent and fail regularly in the constrained environment of Azure DevOps pipelines. This is likely because of thread contention, as these tests pass regularly locally and on GitHub actions. The two failing tests are the only tests in the class that depend on timing between the test thread and a parallel task, and an occasional failure should not generally be considered a full-suite failure as the test is nondeterministic in nature. So this changes the assertion to mark the test as Inconclusive if the values don't match at the time of evaluation.
=> Fix LimitedConcurrencyLevelTaskScheduler timing-dependent tests, #1123

.build/azure-templates/run-tests-on-os.yml, .build/runbuild.ps1
Reduce Powershell build output noise
The Start-Job (and to a lesser degree, New-Item for new directories) cmdlets produce a lot of useless noise to the logs when running tests, when we're already logging the test command being executed.
Example (before, paths anonymized):
```
Frameworks To Test for /.../lucene.net/src/dotnet/Lucene.Net.Tests.ICU/Lucene.Net.Tests.ICU.csproj: net9.0;net8.0;net6.0
Next Project in Queue: Lucene.Net.Tests.ICU, Framework: net9.0
d----          3/7/2025  10:06 AM                  Lucene.Net.Tests.ICU
dotnet test /.../lucene.net/src/dotnet/Lucene.Net.Tests.ICU/Lucene.Net.Tests.ICU.csproj --configuration Release --framework net9.0 --no-build --no-restore --blame  --blame-hang --blame-hang-dump-type mini --blame-hang-timeout 15minutes --results-directory …
```
=> Reduce Powershell build output noise

src/Lucene.Net.TestFramework/Index/AlcoholicMergePolicy.cs
Fixes random failing tests when local time zone participates in Daylight Saving Time
Fixes #1133
The random seed in #1133 results in many failing tests due to the lucenenet-specific code in AlcoholicMergePolicy converting between the local time zone and the random time zone in a way that could result in an invalid date/time being created when near a DST boundary. This fixes this particular issue by always converting from UTC (which does not have DST) to the random time zone. I believe this should be reliable even if the destination/random time zone participates in DST.
=> Fix random failing tests when near a DST boundary, #1133

src/Lucene.Net.TestFramework/Analysis/CrankyTokenFilter.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Core/TestAllAnalyzersHaveFactories.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Core/TestRandomChains.cs
---
Moved `CrankyTokenFilter` to the correct namespace `Lucene.Net.Analysis`.
---
Fixes [#1127](https://github.com/apache/lucenenet/issues/1127)
---
This pull request addresses issue [#1127](https://github.com/apache/lucenenet/issues/1127) by moving `CrankyTokenFilter` from the incorrect namespace:
- **Old Namespace:** `Lucene.Net.TestFramework.Analysis.CrankyTokenFilter`  
- **New Namespace:** `Lucene.Net.Analysis`
✅ **Details:**
- Updated the `CrankyTokenFilter` class to reside in the `Lucene.Net.Analysis` namespace, aligning it with the correct package as in the original Lucene project (`org.apache.lucene.analysis`).
- Ensured that the class remains in the **TestFramework project** and was not moved to `Lucene.Net.Analysis.Common`.
- Adjusted any necessary using statements and …
=> BREAKING: Move CrankyTokenFilter to Lucene.Net.Analysis namespace (#1127)

.asf.yaml
This is a chore PR to fix an error that Apache Infra is reporting:
```
An error occurred while processing the github feature in .asf.yaml:
when expecting a mapping
found arbitrary text
in "lucenenet.git/.asf.yaml::github", line 24, column 1:
^ (line: 24)
```
My (and Claude Code's) theory is that the comment is not indented properly, which is causing the error.
Upon reviewing the docs, it appears like our syntax for [branch protection](https://github.com/apache/infrastructure-asfyaml/blob/main/README.md#branch-protection) was missing the "minimal dictionary" so I added that as well.
=> Fix .asf.yaml syntax error for Apache Infrastructure

src/Lucene.Net.Codecs/SimpleText/SimpleTextDocValuesReader.cs, src/Lucene.Net.Codecs/SimpleText/SimpleTextUtil.cs, src/Lucene.Net.Facet/SortedSet/DefaultSortedSetDocValuesReaderState.cs, src/Lucene.Net.Grouping/AbstractGroupFacetCollector.cs, src/Lucene.Net.Join/TermsIncludingScoreQuery.cs, src/Lucene.Net.Misc/Misc/TermStats.cs, src/Lucene.Net.Queries/TermsFilter.cs, src/Lucene.Net.Suggest/Suggest/Fst/FSTCompletion.cs, src/Lucene.Net.Tests/Util/TestUnicodeUtil.cs, src/Lucene.Net/Codecs/BlockTreeTermsWriter.cs, src/Lucene.Net/Codecs/Lucene3x/Lucene3xFields.cs, src/Lucene.Net/Support/ObsoleteAPI/UnicodeUtil.cs, src/Lucene.Net/Util/BytesRef.cs, src/Lucene.Net/Util/UnicodeUtil.cs
Various improvements to the UnicodeUtil APIs
Fixes #1024
This PR includes several changes to the UnicodeUtil APIs:
- New TryUTF8toUTF16 method added that uses the Try-method pattern common in .NET, so that it will return false if there is an incomplete UTF-8 byte sequence at the end
- UTF8toUTF16 has been updated to throw a ParseException instead of IndexOutOfRangeException if there is an incomplete UTF-8 byte sequence at the end
- New UTF8toUTF16WithFallback method that is like UTF8toUTF16 but adds the U+FFFD character to the output if there is an incomplete UTF-8 byte sequence at the end, instead of throwing
- Moved ToCharArray to the ObsoleteAPI folder as a partial class, and marked for removal in the 4.8.0 RC
- Add ReadOnlySpan overloads where applicable
- Add TryUtf8ToString and …
=> UnicodeUtil updates: TryUTF8toUTF16, ReadOnlySpan methods, #1024

src/Lucene.Net.QueryParser/Classic/MultiFieldQueryParser.cs, src/Lucene.Net.Tests.QueryParser/Classic/TestMultiFieldQueryParser.cs
Fixes a dictionary access bug in MultiFieldQueryParser found during investigating #1157
Related #1157
In the Java code, it calls `.get` on the map and checks for null. We were implicitly throwing a KeyNotFoundException instead. This changes the code to do a safe check with `TryGetValue` which more closely matches the upstream behavior.
Additionally, this adds a test case to confirm boosts are working as expected as reported in #1157.
=> Fix dictionary access in MultiFieldQueryParser, #1157

.build/dependencies.props, Directory.Build.targets, src/Lucene.Net.Benchmark/ByTask/Tasks/AnalyzerFactoryTask.cs, src/Lucene.Net.Benchmark/ByTask/Utils/Algorithm.cs, src/Lucene.Net.Benchmark/ByTask/Utils/Config.cs, src/Lucene.Net.QueryParser/Flexible/Core/Nodes/BoostQueryNode.cs, src/Lucene.Net/Index/CheckIndex.cs, src/Lucene.Net/Index/DocumentsWriterPerThread.cs, src/Lucene.Net/Index/LogMergePolicy.cs, src/Lucene.Net/Index/TieredMergePolicy.cs, src/Lucene.Net/Search/ControlledRealTimeReopenThread.cs, src/Lucene.Net/Search/FieldCache.cs
This adds a reference to the new [Lucene.Net.CodeAnalysis.Dev](https://github.com/apache/lucenenet-codeanalysis-dev) package, where we can build code analysis rules that are specific to this project to do advanced code cleanup and validation tasks.
These warnings were disabled because they are too noisy for general use:
```xml
<PropertyGroup Label="Warnings to be Disabled in Solution">
<NoWarn Label="Floating point types should not be compared for exact equality">$(NoWarn);LuceneDev1000</NoWarn>
<NoWarn Label="Floating point type arithmetic needs to be checked on x86 in .NET Framework and may require extra casting">$(NoWarn);LuceneDev1002</NoWarn>
<NoWarn Label="Java array parameters can sometimes be replaced with .NET out or ref parameters">$(NoWarn);LuceneDev1003</NoWarn>
<NoWarn …
```
=> Added Lucene.Net.CodeAnalysis.Dev package reference

src/Lucene.Net.Analysis.Common/Analysis/Util/StemmerUtil.cs, src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestStemmerUtil.cs
Optimize StemmerUtil for `ReadOnlySpan<char>`/`Span<char>`
Fixes #1140
This PR optimizes StemmerUtil's EndsWith and StartsWith for `ReadOnlySpan<char>`, and Delete and DeleteN for `Span<char>`. Additionally, this type was missing unit tests (including in latest Lucene AFAICT), so this adds some lucenenet-specific unit tests for this type.
Note that the `len` parameters are not quite what you might expect on a naïve reading of the XML doc comments. It is not always equal to the input buffer length (otherwise we could just use `s.Length` and drop the parameter). Instead, it's Lucene's equivalent of what we would call a Slice in .NET. Any characters after `len` chars in the input buffer are treated as if they aren't there. While we could update every callsite of these methods to pass in a …
=> Optimize StemmerUtil for `ReadOnlySpan<char>`/`Span<char>`, #1140

src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs, src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/PerFieldAnalyzerWrapper.cs, src/Lucene.Net.Analysis.Common/Analysis/Util/AnalysisSPILoader.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/RepSumByNameRoundTask.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/RepSumByNameTask.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/RepSumByPrefRoundTask.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/RepSumByPrefTask.cs, src/Lucene.Net.Benchmark/ByTask/Tasks/ReportTask.cs, src/Lucene.Net.Expressions/JS/JavascriptCompiler.cs, src/Lucene.Net.Facet/DrillDownQuery.cs, src/Lucene.Net.Grouping/Function/FunctionDistinctValuesCollector.cs, src/Lucene.Net.QueryParser/Flexible/Standard/Config/StandardQueryConfigHandler.cs, src/Lucene.Net.Tests.Grouping/DistinctValuesCollectorTest.cs, src/Lucene.Net.Tests.QueryParser/Simple/TestSimpleQueryParser.cs, src/Lucene.Net.Tests.Spatial/Prefix/SpatialOpRecursivePrefixTreeTest.cs, src/Lucene.Net/Index/BufferedUpdates.cs, src/Lucene.Net/Search/SloppyPhraseScorer.cs, src/Lucene.Net/Util/AttributeSource.cs
Fixes [#1199](https://github.com/apache/lucenenet/issues/1199)
Replaced all usages of JCG.LinkedDictionary with JCG.OrderedDictionary across the codebase for consistency and to better match the semantics of LinkedHashMap in the JDK. Updated comments to clarify the change as Lucene.NET specific.
=> Replace LinkedDictionary with OrderedDictionary

.build/dependencies.props, Directory.Build.targets, TestTargetFramework.props, src/Lucene.Net/Support/IO/WindowsFsyncSupport.cs
Fixes #1100
Upgrades dev analyzers which adds the LuceneDev1005 analyzer for public types in the Lucene.Net.Support namespace. Fixes the only violation: WindowsFsyncSupport.
Note that upgrading this analyzer reference adds a lot of build warnings due to the new LuceneDev1006 analyzer.
=> Upgrade dev analyzers to 1.0.0-alpha.18; make WindowsFsyncSupport internal, #1100
