src/Lucene.Net.TestFramework/Codecs/lucene42/Lucene42DocValuesConsumer.cs

Lucene42DocValuesConsumer's AddSortedSetField was using values enumerator to return values for "AddBinaryField" downstream code when it should only be used for WriteFST. This resulted in incorrect doc values being recorded in the index. The Lucene code can be seen here:
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/test-framework/src/java/org/apache/lucene/codecs/lucene42/Lucene42DocValuesConsumer.java#L308
Note how it never uses values iterator when adding binary field portion.
This fixes failures in TestLucene42DocValuesFormat tests, example:
http://teamcity.codebetter.com/viewLog.html?buildId=179703&tab=buildResultsDiv&buildTypeId=LuceneNet_Core#testNameId5215188354472572854

Values iterator should not be used in binary field portion

---

src/Lucene.Net.TestFramework/Attributes/LongRunningTestAttribute.cs
src/Lucene.Net.TestFramework/Lucene.Net.TestFramework.csproj
src/Lucene.Net.TestFramework/Util/BaseDocIdSetTestCase.cs
src/Lucene.Net.Tests/core/Util/TestPagedBytes.cs

here is the long running test attribute and also the attribute applied to one of the longer-running tests.
[4f28661] adding LongRunningTest attribute.

Marking a few things long running. (+1 squashed commits)

---

src/Lucene.Net.TestFramework/Store/MockDirectoryWrapper.cs

Fix port implementation of "FillOpenTrace" to preserve the exception type that was intended to be thrown. In addition, rename the method to reflect better what it does in .NET as in Java version it would modify the stack trace of the exception but .NET version is instead passing the original exception as inner exception.
This fixes tests that depend on IOException being thrown and not Exception, such as Lucene.Net.Index.TestCodecHoldsOpenFiles.TestExposeUnclosedFiles

preserve exception type

---

src/Lucene.Net.TestFramework/Index/BaseTermVectorsFormatTestCase.cs
src/Lucene.Net.Tests/core/Index/TestMultiLevelSkipList.cs
src/Lucene.Net.Tests/core/Index/TestPayloads.cs
src/Lucene.Net.Tests/core/Index/TestTermVectorsReader.cs

More methods marked as sealed to pass Lucene.Net.Index tests

more marked as sealed

---

src/Lucene.Net.Codecs/BlockTerms/BlockTermsReader.cs
src/Lucene.Net.Codecs/BlockTerms/FixedGapTermsIndexReader.cs
src/Lucene.Net.Codecs/BlockTerms/TermsIndexReaderBase.cs
src/Lucene.Net.Codecs/BlockTerms/VariableGapTermsIndexReader.cs
src/Lucene.Net.Codecs/BlockTerms/VariableGapTermsIndexWriter.cs
src/Lucene.Net.Codecs/Memory/DirectPostingsFormat.cs
src/Lucene.Net.Codecs/Memory/FSTOrdTermsReader.cs
src/Lucene.Net.Codecs/Memory/FSTOrdTermsWriter.cs
src/Lucene.Net.Codecs/Memory/FSTTermOutputs.cs
src/Lucene.Net.Codecs/Memory/FSTTermsReader.cs
src/Lucene.Net.Codecs/Memory/FSTTermsWriter.cs
src/Lucene.Net.Codecs/Memory/MemoryPostingsFormat.cs
src/Lucene.Net.Codecs/SimpleText/SimpleTextDocValuesReader.cs
src/Lucene.Net.Codecs/SimpleText/SimpleTextFieldsReader.cs
src/Lucene.Net.Codecs/SimpleText/SimpleTextStoredFieldsReader.cs
src/Lucene.Net.Codecs/SimpleText/SimpleTextTermVectorsReader.cs
src/Lucene.Net.Codecs/SimpleText/SimpleTextUtil.cs

Finalizing conversion of the Lucene.Net.Codecs (Memory), as well as refactoring to account for change from long to long?

Lucene.net.codecs.memory

---

src/Lucene.Net.Core/Index/IndexReader.cs

Make sure we do not forget about tracking the dropped exceptions.

Add LUCENENET TODO

---

src/Lucene.Net.Tests/core/Index/TestTermsEnum.cs

Several tests in the fixture were using instance variables for directory and reader references and that was breaking the tests as they were not initialized to clean state. Refactored to get rid of instance variables and any shared state issues.

don't use instance variables, clean up test

---

src/Lucene.Net.Tests/core/Util/TestQueryBuilder.cs

another unsealed increment token

seal IncrementToken

---

src/Lucene.Net.Queries/CustomScoreQuery.cs
src/Lucene.Net.Queries/TermsFilter.cs
src/Lucene.Net.Tests.Queries/BoostingQueryTest.cs
src/Lucene.Net.Tests.Queries/ChainedFilterTest.cs
src/Lucene.Net.Tests.Queries/Function/FunctionTestSetup.cs
src/Lucene.Net.Tests.Queries/Function/TestBoostedQuery.cs
src/Lucene.Net.Tests.Queries/Function/TestDocValuesFieldSources.cs
src/Lucene.Net.Tests.Queries/Function/TestFieldScoreQuery.cs
src/Lucene.Net.Tests.Queries/Function/TestFunctionQuerySort.cs
src/Lucene.Net.Tests.Queries/Function/TestLongNormValueSource.cs
src/Lucene.Net.Tests.Queries/Function/TestOrdValues.cs
src/Lucene.Net.Tests.Queries/Function/TestValueSources.cs
src/Lucene.Net.Tests.Queries/Lucene.Net.Tests.Queries.csproj
src/Lucene.Net.Tests.Queries/Mlt/TestMoreLikeThis.cs
src/Lucene.Net.Tests.Queries/TermsFilterTest.cs
src/Lucene.Net.Tests.Queries/TestCustomScoreQuery.cs

This PR wraps up the port of tests for the Lucene.Net.Queries project.

Add tests to Lucene.Net.Queries

---

src/Lucene.Net.Core/Codecs/Compressing/CompressionMode.cs

Remove use of C# 6 string interpolation in CompressionMode.cs

Remove use of C# 6 features

---

src/Lucene.Net.Core/Util/OfflineSorter.cs
src/Lucene.Net.Tests/core/Util/TestOfflineSorter.cs

This resolves the following failing tests:
Core.Util.TestOfflineSorter.TestEmpty
Core.Util.TestOfflineSorter.TestIntermediateMerges
Core.Util.TestOfflineSorter.TestSmallRandom

Fixed OfflineSorter Test Failures

---

src/Lucene.Net.Analysis.Common/Analysis/Compound/hyphenation/PatternParser.cs
src/Lucene.Net.Analysis.Common/Analysis/Compound/hyphenation/TernaryTree.cs
src/Lucene.Net.Analysis.Common/Analysis/Core/StopFilter.cs
src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/CapitalizationFilterFactory.cs
src/Lucene.Net.Analysis.Common/Analysis/Nl/DutchAnalyzer.cs
src/Lucene.Net.Analysis.Common/Analysis/Nl/DutchStemFilter.cs
src/Lucene.Net.Analysis.Common/Analysis/Nl/DutchStemmer.cs
src/Lucene.Net.Analysis.Common/Analysis/Synonym/SlowSynonymFilter.cs
src/Lucene.Net.Analysis.Common/Analysis/Util/AbstractAnalysisFactory.cs
src/Lucene.Net.Analysis.Common/Analysis/Util/CharArrayMap.cs
src/Lucene.Net.Analysis.Common/Analysis/Util/CharArraySet.cs
src/Lucene.Net.Tests.Analysis.Common/Analysis/Core/TestBugInSomething.cs
src/Lucene.Net.Tests.Analysis.Common/Analysis/Synonym/TestSynonymMapFilter.cs
src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestCharArrayMap.cs
src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestCharArraySet.cs
src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestCharTokenizers.cs

This fixes the 23 Analysis tests that were failing all of the time, and 1 test that was failing about 10% of the time.
> NOTE: This includes the commits from #185.
Also, the CharArraySet and CharArrayMap classes were refactored:
1. An `ICharArrayMap` interface was introduced to allow CharArraySet to hold a reference to CharArrayMap without knowing its generic type.
2. A `MapValue` class was introduced to emulate Java's ability to put an `object()` instance into a generic type, whose only purpose is to make the value non-null (since null has a special meaning and default(TValue) would break the null check anyway if we were dealing with value types).
3. A `ValueCollection` class and `ValueEnumerator` class were introduced to house the logic that converts the `MapValue` to a real value, and …

Fixed 24 Failing Analaysis Tests + Completed CharArraySet/CharArrayMap Implementation

---

README.md

Its impossible to find the nuget package for the user contributed code. I have therefore added the nuget link into the readme.

Add Lucene.Net.Contrib

---

src/Lucene.Net.Analysis.Common/Analysis/Ar/ArabicStemmer.cs

modified to be a generic IList<char[]>. Created methods for readability.

https://issues.apache.org/jira/browse/LUCENENET-607

---

README.md
src/Lucene.Net/overview.md
websites/apidocs/docfx.global.json
websites/site/contributing/documentation.md
websites/site/contributing/make-release.md
websites/site/docs.md
websites/site/download/download.md
websites/site/download/toc.yml
websites/site/download/version-4.8.0-beta00012.md
websites/site/lucenetemplate/partials/home-quick-start.tmpl.partial

Updates for API documentation, release procedure, and download pages for 4.8.0-beta00010, 4.8.0-beta00011, and 4.8.0-beta00012

4.8.0-beta00012 release updates

---

azure-pipelines.yml
build/azure-templates/publish-test-results-for-test-projects.yml
build/azure-templates/publish-test-results.yml
build/azure-templates/run-tests-on-os.yml

Added Azure DevOps tests for .NET Framework x86 (see #258)

---

src/Lucene.Net/Store/NativeFSLockFactory.cs

Fixes Failing Tests: TestTermVectorsWriter::TestTermVectorCorruption() and TestIndexWriterReader::TestDuringAddIndexes()

---

.editorconfig
CHANGES.txt
src/Lucene.Net.Suggest/Suggest/Analyzing/AnalyzingInfixSuggester.cs
src/Lucene.Net.Suggest/Suggest/Analyzing/BlendedInfixSuggester.cs
src/Lucene.Net.Tests.Suggest/Suggest/Analyzing/AnalyzingInfixSuggesterTest.cs
src/Lucene.Net.Tests.Suggest/Suggest/Analyzing/BlendedInfixSuggesterTest.cs

Implements [LUCENE-5889](https://github.com/apache/lucene-solr/commit/4a485d68771e5e123139cc12e9ea2733a922baea#diff-96baf6cc4649d2c8d0aa5423587cf3aa3bf82adca5c953d1c9fbbba2575aca6f) 
A version 5.0 feature later backported to 4.11.0

Implements [LUCENE-5889]

---

build/Dependencies.props

Upgrading the two as a pair seemed to make things happy.

Upgrade NUnit to ver 3.13.1 and NUnit3TestAdapter to ver 3.17.0 [#406](https://github.com/apache/lucenenet/issues/406)

---

src/Lucene.Net.Join/FakeScorer.cs
src/Lucene.Net.Join/FixedBitSetCachingWrapperFilter.cs
src/Lucene.Net.Join/JoinUtil.cs
src/Lucene.Net.Join/ScoreMode.cs
src/Lucene.Net.Join/TermsCollector.cs
src/Lucene.Net.Join/TermsIncludingScoreQuery.cs
src/Lucene.Net.Join/TermsQuery.cs
src/Lucene.Net.Join/TermsWithScoreCollector.cs
src/Lucene.Net.Join/ToChildBlockJoinQuery.cs
src/Lucene.Net.Join/ToParentBlockJoinCollector.cs
src/Lucene.Net.Join/ToParentBlockJoinFieldComparator.cs
src/Lucene.Net.Join/ToParentBlockJoinQuery.cs
src/Lucene.Net.Join/ToParentBlockJoinSortField.cs
src/Lucene.Net.Tests.Join/TestBlockJoin.cs
src/Lucene.Net.Tests.Join/TestBlockJoinSorting.cs
src/Lucene.Net.Tests.Join/TestBlockJoinValidation.cs
src/Lucene.Net.Tests.Join/TestJoinUtil.cs

Fixes some minor bugs and formatting issues with the tests in `Lucene.Net.Tests.Join`. See #259.

Review of Lucene.Net.Tests.Join (See #259)

---

src/Lucene.Net/Search/Similarities/TFIDFSimilarity.cs

Ref: https://github.com/apache/lucene-solr/commit/f0bfcbc7d8fbc5bb2791da60af559e8b0ad6eed6

Don't insert extra newline in TFIDFSim's score explanation

---

src/Lucene.Net/Search/FieldCacheImpl.cs

This reverts the changes to locking in `FieldCacheImpl` that were introduced to attempt to reduce locking. It is clear that we need to rule out concurrency differences from Lucene such as this in order to get to the bottom of our locking contention issues during testing.
The 2 main things that were changed were:
1. Restore locks back to the Lucene 4.8.0 state, including replacing some missing locks.
2. Changed from using `ConcurrentDictionary<TKey, TValue>` back to `Dictionary<TKey, TValue>` because it adds unnecessary overhead.
As for #272, much of the locking contention has been reduced by using `ConditionalWeakTable<TKey, TValue>` rather than `WeakDictionary<TKey, TValue>` in .NET Standard 2.1+. In addition, we have made several other performance improvements since the report, which …

Reverted FieldCacheImpl Locking (Closes #272)

---

src/Lucene.Net/Index/IndexWriter.cs

Swapped in `ConcurrentDictionary<TKey, TValue>` instead of `Dictionary<TKey, TValue>` to take advantage of the fact [`ConcurrentDictionary<TKey, TValue>` supports deleting while iterating](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getenumerator?redirectedfrom=MSDN&view=net-5.0#remarks). Also added conditional support to use a non-concurrent `Dictionary<TKey, TValue>` if/when we add a target for .NET Core/.NET 5/.NET 6.
This puts us more in line with Lucene 4.8.0.

PERFORMANCE: Lucene.Net.IndexWriter.ReaderPool: Fixed deleting while iterating to reduce allocations

---

src/Lucene.Net.Queries/Mlt/MoreLikeThis.cs

`Lucene.Net.Queries.Mlt.MoreLikeThis`: Fixed boxing issues with `RetrieveTerms(`) and `RetrieveInterestingTerms()` methods by changing `object[]` to a class named `ScoreTerm` (same refactoring as Lucene 8.2.0).

Fixes boxing on MoreLikeThis

---

src/Lucene.Net.Analysis.Phonetic/Language/Bm/PhoneticEngine.cs
src/Lucene.Net.Benchmark/ByTask/Tasks/SearchTravRetHighlightTask.cs
src/Lucene.Net.Benchmark/ByTask/Tasks/SearchTravRetVectorHighlightTask.cs
src/Lucene.Net.TestFramework/Store/MockDirectoryWrapper.cs
src/Lucene.Net/Support/CollectionExtensions.cs

- Use `ExceptWith()` where appropriate
- Optimized `ICollection<T>.RemoveAll()` and created extension method for `ICollection<T>.RetainAll()` and updated method signatures to match the JDK

PERFORMANCE: Updated collections to use optimized removal methods

---

src/Lucene.Net.Tests/Util/TestPriorityQueue.cs

These are required to make the tests pass after fixing randomization issues in the test framework.

BUG: Lucene.Net.Tests.Util.TestPriorityQueue: Fixed issues with comparers

---

src/Lucene.Net.Suggest/Suggest/Analyzing/BlendedInfixSuggester.cs
src/Lucene.Net.Tests.Suggest/Suggest/Analyzing/BlendedInfixSuggesterTest.cs

Fix #527 
Apply patch from https://issues.apache.org/jira/browse/LUCENE-6093

Patch for BlendedInfixSuggester to solve ArgumentNullException

---

src/Lucene.Net.Facet/DrillDownQuery.cs

Added collection initializer so query can be populated in one statement and enumerated to get both its query clauses and dimensions

Lucene.Net.Facet.DrillDownQuery: Added collection initializer

---

src/Lucene.Net.Demo/Facet/DistanceFacetsExample.cs
src/Lucene.Net.Demo/Facet/ExpressionAggregationFacetsExample.cs
src/Lucene.Net.Expressions/SimpleBindings.cs
src/Lucene.Net.Tests.Expressions/TestDemoExpressions.cs

Added collection initializer and updated `DistanceFacetsExample` and `ExpressionAggregationFacetsExample` to demonstrate usage.

Lucene.Net.Expressions.SimpleBindings: Added collection initializer

---

websites/site/contributing/how-to-setup-java-lucene-debugging.md
websites/site/contributing/toc.yml
websites/site/lucenetemplate/styles/main.css

This adds a new "How to Setup Java Lucene 4.8 Debugging" page to the "Contributing" section of the website.

Add "How to Setup Java Debugging page"

---

.github/workflows/Lucene-Net-Documentation.yml
.github/workflows/Lucene-Net-Website.yml

See https://github.com/apache/lucenenet/pull/533#discussion_r780633564

.github/workflows: Updated website/documentation configs to use subdirectory glob patterns for paths.

---

README.md
websites/site/contributing/how-to-setup-java-lucene-debugging.md
websites/site/contributing/source.md
websites/site/lucenetemplate/styles/main.css

Added gray boxes around images on Contributor "Setup Java Debugging" web page.
Fixed "lines of code" indicated on Contributor Source Code web page and linked to related image.
Added welcome and more overview content, plus minor edits to repo README page

docs: Repo README page edits, and two minor web page content edits.

---

websites/site/contributing/how-to-setup-java-lucene-debugging.md
websites/site/contributing/make-release.md
websites/site/docfx.json
websites/site/docs.md
websites/site/index.md
websites/site/lucenetemplate/index.html.tmpl
websites/site/lucenetemplate/styles/main.css
websites/site/lucenetemplate/styles/site.css
websites/site/quick-start/index.md
websites/site/quick-start/introduction.md
websites/site/quick-start/learning-resources.md
websites/site/quick-start/toc.yml
websites/site/quick-start/tutorial.md
websites/site/toc.yml

Improved visual communication of home page. Made hero text much larger and made better use of negative space.  Made the books smaller on home page. Added new "Getting Started" section comprised of 4 pages: index, Introduction, Tutorial and Learning Resources.  
Increased body font size. Improved UI of hyperlinks both with brighter color and better hover feedback.  Fixed bug so that "Improve this Doc" is always clickable. Fixed responsive bug,  Updated website footer copyright date.

Website: Improved home page messaging, added New Getting Started Section and more.

---

websites/site/quick-start/learning-resources.md

website: fixed horizontal rule

---

src/Lucene.Net.Replicator/Http/HttpClientBase.cs

fix: Fixed Infinite loop in HttpClientBase

---

src/Lucene.Net.Benchmark/Support/TagSoup/Guard.cs
src/Lucene.Net.Benchmark/Support/TagSoup/HTMLScanner.cs
src/Lucene.Net.Benchmark/Support/TagSoup/PYXScanner.cs
src/Lucene.Net.Benchmark/Support/TagSoup/PYXWriter.cs
src/Lucene.Net.Benchmark/Support/TagSoup/Parser.cs
src/Lucene.Net.Benchmark/Support/TagSoup/ScanHandler.cs
src/Lucene.Net.Benchmark/Support/TagSoup/Scanner.cs
src/Lucene.Net.Benchmark/Support/TagSoup/Schema.cs
src/Lucene.Net.Benchmark/Support/TagSoup/XMLWriter.cs

See #681.
- Reviewed API for accessibility issues.
- Fixed error handling and guard clauses.
- Changed to generic collections.
- **BREAKING**: Renamed method arguments.

SWEEP: Lucene.Net.Benchmark.Support.TagSoup: Review

---

src/Lucene.Net.Codecs/Memory/MemoryDocValuesConsumer.cs
src/Lucene.Net.Highlighter/VectorHighlight/BaseFragListBuilder.cs
src/Lucene.Net.TestFramework/Codecs/Lucene42/Lucene42DocValuesConsumer.cs
src/Lucene.Net.TestFramework/Codecs/MissingOrdRemapper.cs
src/Lucene.Net.TestFramework/Index/RandomIndexWriter.cs
src/Lucene.Net.Tests/Index/TestIndexWriter.cs
src/Lucene.Net.Tests/Index/TestIndexableField.cs
src/Lucene.Net/Codecs/Lucene3x/Lucene3xTermVectorsReader.cs
src/Lucene.Net/Index/BufferedUpdatesStream.cs
src/Lucene.Net/Index/CoalescedUpdates.cs
src/Lucene.Net/Index/FrozenBufferedUpdates.cs
src/Lucene.Net/Util/AttributeSource.cs
src/Lucene.Net/Util/RamUsageEstimator.cs
src/Lucene.Net/Util/WeakIdentityMap.cs

SWEEP: Renamed classes from using Iterable and Iterator to Enumerable and Enumerator, where appropropriate

---

src/Lucene.Net.Benchmark/Support/TagSoup/HTMLScanner.cs
src/Lucene.Net.Benchmark/Support/TagSoup/Parser.cs

See https://github.com/apache/lucenenet/pull/692#issuecomment-1282267048

Fixed TagSoup Parser/HTMLScanner

---

src/Lucene.Net.Tests/Index/TestIndexWriter.cs

BUG: Lucene.Net.Tests.Index.TestIndexWriter: Finished port of RandomFailingFieldEnumerable.

---

.build/TestReferences.Common.targets
.build/dependencies.props
src/Lucene.Net.TestFramework/Lucene.Net.TestFramework.csproj
src/Lucene.Net.Tests.Analysis.SmartCn/Lucene.Net.Tests.Analysis.SmartCn.csproj
src/Lucene.Net.Tests.Benchmark/Lucene.Net.Tests.Benchmark.csproj

Fix for net461 dependency conflict after upgrading Newtonsoft.Json.

---

src/Lucene.Net.Analysis.Common/Analysis/Br/BrazilianStemmer.cs
src/Lucene.Net.Analysis.Common/Analysis/De/GermanLightStemmer.cs
src/Lucene.Net.Analysis.Common/Analysis/Fi/FinnishLightStemmer.cs
src/Lucene.Net.Analysis.Common/Analysis/Hu/HungarianLightStemmer.cs
src/Lucene.Net.Analysis.Common/Analysis/In/IndicNormalizer.cs
src/Lucene.Net.Analysis.Common/Analysis/Util/AbstractAnalysisFactory.cs
src/Lucene.Net.Analysis.Common/Analysis/Util/CharacterUtils.cs
src/Lucene.Net.Misc/Index/Sorter/BlockJoinComparatorSource.cs
src/Lucene.Net.TestFramework/Support/JavaCompatibility/LuceneTestCase.cs
src/Lucene.Net.TestFramework/Support/Util/LuceneRandomSeedInitializer.cs
src/Lucene.Net.TestFramework/Support/Util/LuceneSetUpFixtureBuilder.cs
src/Lucene.Net/Index/DocumentsWriterFlushQueue.cs

Adds to #663
- Added static to more methods
- Added suppression for warnings on methods not marked in #693 but found to be unwanted in #690

Review for CA1822: Mark members as static (2)

---

src/Lucene.Net.Analysis.Common/Analysis/Br/BrazilianStemmer.cs

Adds to #663
- Added static to more methods
Hopefully one of the last sweeps needed 😄

Review for CA1822: Mark members as static (3)

---

src/Lucene.Net.Analysis.Common/Analysis/Synonym/SlowSynonymFilter.cs

Added nameof for the sonar suggestions.

---

.editorconfig
TestTargetFramework.props

This is just to reduce some of the noise, but we have some way to go to filter these warnings down to the important stuff.

Suppressed some SonarCloud Warnings

---

src/Lucene.Net.Queries/Function/ValueSourceScorer.cs

This one focuses on ValueSourceScorer where we add a private method to call from the constructor and a virtual method that used to be called from the constructor before.

BREAKING: create private method for calling from construtor for ValueSourceScorer

---

src/Lucene.Net.Spatial/Prefix/Tree/Cell.cs
src/Lucene.Net/Search/DisjunctionMaxQuery.cs
src/Lucene.Net/Util/SentinelIntSet.cs

This PR augments the documentation based on the feedback in https://github.com/apache/lucenenet/pull/801

Add documentation explaining the behavior change for certain virtual methods

---

src/Lucene.Net.TestFramework/Support/Util/RandomizedContext.cs

BUG: Lucene.Net.Util.RandomizedContext: Create a separate instance of Randomizer() for each thread

---

.github/workflows/sonar.yml

Disable caching (for now) and only create directory if it doesn't already exist

.github/workflows/sonar.yml: Attempting to fix exit code

---

.github/ISSUE_TEMPLATE/10_bug_report.yml
.github/ISSUE_TEMPLATE/20_feature_request.yml
.github/ISSUE_TEMPLATE/30_task.yml
.github/ISSUE_TEMPLATE/40_documentation_improvement.yml
.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md

This is being discussed on the dev mailing list: https://lists.apache.org/thread/q1qdmb72bw8f76gm7gpnktlb6ytk7t04

Added GitHub Issue and PR templates to improve usability and automatically tag issues appropriately

---

src/Lucene.Net.Tests.Analysis.Common/Analysis/Miscellaneous/TestStemmerOverrideFilter.cs

**BUG:** `Lucene.Net.Analysis.Miscellaneous.TestStemmerOverrideFilter::TestRandomRealisticWhiteSpace()`: Fixed rare random test failure
Fixes #896
Ported patch from https://github.com/apache/lucene/commit/bce10efeb40c11271cb398c37b859408818b8a00 to fix rare random test failures. The issue was the test was poorly thought out when `ignoreCase` was set to `true`. In this case, it could generate Unicode strings that would stem down to the upper case and lower case of the same text, which would cause a collision.

BUG: Lucene.Net.Analysis.Miscellaneous.TestStemmerOverrideFilter::TestRandomRealisticWhiteSpace(): Fixed rare random test failure

---

websites/site/contributing/index.md

Added the slack channel to the contributing page of the website.
Fixes #893

Added the slack channel to the contributing page of the website (Fixes #893)

---

websites/site/quick-start/tutorial.md

Port of https://github.com/apache/lucenenet-site/pull/46
Let's make sample copy-able

website: Added missing namespaces to tutorial

---

.build/build.msbuildproj
.github/github.msbuildproj
Lucene.Net.sln

Simplifies solution with no-targets projects for build folders:
Solution now looks like this:
and removes a lot of hard coded values in the sln file

Simplifies solution with no-targets projects for build folders

---

websites/apidocs/apiSpec/core/Lucene_Net_Codecs.md
websites/site/docs.md
websites/site/download/download.md
websites/site/download/toc.yml
websites/site/download/version-4.8.0-beta00017.md
websites/site/index.md
websites/site/quick-start/tutorial.md

This contains the post-release website changes for 4.8.0-beta00017.
Do NOT merge this prior to the release. Also, be sure to change the release date on the 2 download pages.

Updated website for 4.8.0 beta00017 post-release

---

src/Lucene.Net.Tests/Support/TestCollectionExtensions.cs

Add Support unit tests for CollectionExtensions, #1115
Fixes #1115
This adds some basic unit tests for CollectionExtensions, covering the set, list, and other-collection cases.

Add Support unit tests for CollectionExtensions, #1115

---

src/Lucene.Net.Facet/Taxonomy/CachedOrdinalsReader.cs
src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestCharArraySet.cs
src/Lucene.Net.Tests/Index/TestReaderClosed.cs
src/Lucene.Net/Index/IndexReader.cs
src/Lucene.Net/Search/CachingWrapperFilter.cs
src/Lucene.Net/Search/FieldCacheImpl.cs

Minor IDE auto white space strip. Fix end of files
Fixes #{issue number} (in this specific format)
{Detail}

misc: fix typos
